### ISSUE TITLE
Membership

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#1]
Please post here if you would like to gain membership to the ethereumproject organization. Please introduce yourself, tell us your skillset and how you can contribute to the project. 

We will try to remain open as possible but everyone will needed to be added on a trial basis to prevent potential abuse.

**Comment by whatisgravity** [comment]
Hello Bart, 

Great to hear from you, I would love it if you could take over maintaining EthereumJ, it is a very important project since it is the foundation of mobile application development. I have experience with Scala and Java but it is very limited so you would need to lead the restoration on that client. I will add you to the project. 

Please remember not to just fork, but to git pull, create the project on github, then change the remote and push. This lets us maintain all the commit history while not being a fork. The reason being is forks are treated as second class citizens on github and without doing this we would not get features like full text search on our repos which is really important.

**Comment by dustysesameseed** [comment]
Hello, I'm dustysesameseed (or dusty.) I recently completed my education in computer engineering. I have been coding for about 6 years, primarily in C++, Java, lower level and hardware languages, and some web development. In the past I have worked with more traditional databases, but have recently been studying blockchain and smart contract projects.

I'm posting because I want to help the original/classic Ethereum chain and its core principles succeed. To that end I can contribute to code development and review, documentation and any writing, outreach or miscellaneous roles which need another hand on deck.

**Comment by MrComputerCodes** [comment]
My name is Mr Computer Codes,

I have been in the Ethereum space for a long time, working on core tech and a little bit on the dapp layer. Before the fork I wanted to launch a pure ETH fork, but decided it was inferior to Classic once I saw the support. Refer to https://github.com/permaledger/go-perma

I am a quick learner and have enough software engineering experience to maintain any ETH project fork.

The principles don't matter so much to me as the coordination "shield" enabled by shared princples, which is a net economic gain in the long term.

**Comment by realcodywburns** [comment]
Greetings, I am Cody.

I have been programming off and on for the last 20 years or so. I mainly use python or c++, but know my way around HTML, php, and Go. I can adapt to just about anything with a little time. I am a business major so my programming is mostly a hobby to keep my skills sharp. I've been researching block chains for the last two years and was against the hard fork from the day it was announced. Ethereum classic is the true spirit of the chain, the other is just a shared database. I'm ready to help where I can.

**Comment by CharlesHoskinson** [comment]
Hi guys Charles Hoskinson here. I'd love to help out with Ethereum classic. I can fund several developers. My company also has a PoS algorithm coming out with security proofs around August 14th. Could the lead developer send me an email at Charles.Hoskinson@iohk.io

**Comment by DylanKojiCheslin** [comment]
Hi,  
I'm Dylan Koji-Cheslin. I would like to contribute to Ethereum classic. I am a web developer, most familiar with  meteor.js, requirements analysis, and JavaScript. I'd like to learn some more and help with go/python but can't claim expertise at them yet.

**Comment by splix** [comment]
Hi, I'm Igor. Proffessional software developer since 2001, have been writing code since 1995. Mostly Java and all related. I can take care of ethereumj

**Comment by arvicco** [comment]
Guys, thanks for your introductions. @whatisgravity is a dev lead for ethereumproject, but seems like he's not online today. Should be back online soon.

**Comment by whatisgravity** [comment]
Wow, a lot of great responses. I will try to address all of these soon as possible.

**Comment by whatisgravity** [comment]
To clarify our goals, we are primarily interested in maintaining existing clients at this stage, with any DAO specific code removed. This will allow users to run ETC clients without having to specify they don't want to use the fork network, or use a special flag to use the network. We also need to be ready to maintain our clients in the event the Ethereum Foundation tries to co-opt the network by trying to force changes to the network by leveraging their power over client development.

I'm thinking it may be wise to create a repository to store our PGP keys, this will be useful when begin creating builds too. 

@dustysesameseed We would be happy for whatever time you can volunteer. Even if it is just code review on languages you feel comfortable with. The more eyes on these projects the better the security will be. If you find that you have time, we need someone to begin work on the cpp-ethereum project. Otherwise there is also the EthereumJ project which is being spearheaded by @bart-j0 currently. 

@MrComputerCodes Glad to have your assistance. If you have experience from your time forking your welcome to help out with whatever client you are comfortable with. 

However, if you are interested in volunteering time on the dapp level, we could use a contract to function as a multisig trust. For instance, I would like to donate to development and I have received messages from others wanting to send donations. I would prefer not to maintain sole control over the donated money and in the past managing donations in a volunteer system has been difficult. My proposal is a contract which active developers to share control and have a transparent accounting. Active members could be whitelisted for voting control and whtielisted to be able to receive payments. If you are interested we can create a repo and begin working on the function requirements of the contract. 

@realcodywburns At this stage we don't need mythical 100x coders, we just need people who can volunteer time to merge in commits from the existing clients. 

As we grow we can focus on updating the system ourselves but at this stage your basic skills and an interest to learn are enough. If there is anything you don't know we can assist you if you have the time to invest to learn it.

You are welcome to help out with the Golang project, I'm divided among a lot of tasks and could certainly use the help. We need to start merging in changes from the unstable 1.5.0  so when it become stable we have an alternative client ready for use. 

@CharlesHoskinson I guess I'm the lead developer but I think thats the wrong term because my hope is we can have different people working on different clients and strive for greater client diversity. This prevent one development team with control over the primary client from unilaterally making changes.

If you want to independently hire developers and task them to maintain clients that would be wonderful. It would even be preferable to donating to us because we do not yet have the infrastructure to safely handle donations in a transparent way. 

As I stated to @realcodywburns I could use help with the go-etheruem client while I invest time in structuring. This is the primary client, and so it is an important one to keep maintained. I have started work on restoring the Mist client, so if you have time available to work on that it would be wonderful. Otherwise there is cpp-ethereum too which needs to be maintained. Parity just released a client which operates with our network but requires a flag so that could be a candidate to maintain as well. 

I'm interested to learn more about your ideas regarding PoS. I think it is a difficult subject to tackle, so starting early and creating proposals and test networks is important. I think creating solid methods to do  network simulation should be an important step, that way we can approach this problem scientific method.

I created an email at whatisgravity@tuta.io - I will try to check it regularly. Please send your PGP key for future use and let me know specifically in what client or project you are interested in working on.

@DylanKojiCheslin Your skills may be a good first for managing the Mist Client. It is written in Meteor which is a JS web framework, it has been packaged with webkit to allow it to be used as a UI for system applications. This requires a lot of changes currently, since is currently full of callbacks to a centralized update notification system. It is an important client though because many of our non technical users will rely on it until more GUI clients become available. 

Alternatively, skill with git is primarily needed at this stage, so even a moderate skill level could be useful in maintaining something like the python client if you are more interested in that. You are also welcome to assist on the go-ethereum project, we need to start work migrating on 1.5.0 upstream patches.


@splix A familiar name from your block explorer project, thank you for creating that is has been proven to be a massive help. Is that project open source? Would you be willing to make it open source if it is not already? I think a solid block explorer is worth being under the umbrella of this volunteer organization. In a system like Ethereum the ability to easily verify contract code is critical. Without an easy system in place novice users have no way validate a deployed contracts source code. It would also go a long way in showing that our efforts help the wider Etheruem community and not just the users of our chain.

If you have time to contribute to the EthereumJ project @bart-j0 has started. The project is incredibly important, since it is the foundation to many mobile applications, so the more maintainers the better. We would be happy to have you help with that.

**Comment by whatisgravity** [comment]
If I missed anything feel free to contact me by email, please provide a PGP key.

 I'm also moving this discussion to: https://github.com/ethereumproject/Volunteer/issues/1

So if anyone else is interested please make your request on that new repository. It makes less and less sense to keep this confined in the go-ethereum repository. 

I want to thank everyone who has offered their time, it is really appreciated.

**Comment by whatisgravity** [comment]
https://github.com/ethereumproject/Volunteer/tree/master/Keys I added a basic key repository to the Volunteer project. I encourage everyone to add their keys, if we do start releasing builds of clients we should only release builds which have been signed and can be verified. Having an easy to find repository will make it easier.

**Comment by matthewjamesr** [comment]
Hey all! I am very excited to try to help out this project and keep Ethereum Classic alive and well. I am a web developer, full stack capable but shine on the backend.

Languages: Ruby/PHP/JS (Node)
Frameworks: Rails/Laravel
Extra: Experience tinkering with custom blockchain deployment using Multichain, also wrote a simple block explorer on said custom chain.

Please reach out if there is anything I can help with or even custom development/creation @whatisgravity .

**Comment by whatisgravity** [comment]
I'm closing this, any membership discussion will need to take place in the volunteer section. Sorry for not noticing your post in here matthew, but we talked in the other thread.
