### ISSUE TITLE
gzip: stdin: not in gzip format

### ISSUE THREAD

**Issue by JeroenMerks** [ethereumproject/go-ethereum#10]
#### System information
Geth version: geth-ARM-20160727-1.4.10-6aaf5f3
OS & Version: Ubuntu Mate 16.10 ARM

#### Expected behaviour
The tarred/zipped binary to extract

#### Actual behaviour
tar -zxvf geth-ARM-20160727-1.4.10-6aaf5f3.tar.gz 
_gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now_

#### Steps to reproduce the behaviour
tar -zxvf the latest binary of geth classic

**Comment by yt-bg** [comment]
I can confirm the same for geth-Linux64-20160727-1.4.10-6aaf5f3.tar.gz

**Comment by scorpio18** [comment]
try 

tar xvf geth-ARM-20160727-1.4.10-6aaf5f3.tar.gz

**Comment by JeroenMerks** [comment]
@scorpio18 thank you sir, that worked.
Now I need to try to get the 64-bit binary to run on my raspberry pi 3...

**Comment by whatisgravity** [comment]
I believe you will want the ARM for raspberry pi. If you are able to build it yourself there are a variety of compile options for ARM processors.

**Comment by JeroenMerks** [comment]
@whatisgravity Thanks for the help. So far it seems like the pi _does_ have a 64-bit ARM processor, but no-one has yet built a kernel for it because the pi only has 1 gig of RAM anyway.
It'd be great if you could compile a 32-bit version for me.

**Comment by whatisgravity** [comment]
I built and published the rest of the ARM binaries, hopefully one of those will solve your issue. Let me know if none of those work for you, or if one does work for you. I'm interested in knowing so I can have greater ability to help people using raspberry pi's in the future.

**Comment by whatisgravity** [comment]
Aside: I will use bz2 in the future, it gives better compression rates.

**Comment by LeChuckDE** [comment]
could be closed, not a problem of tar.gz file.
It is a problem of tar !!!

tar xfvz will always work !

the "Z" Flag must be always at last place in parameters...

**Comment by JeroenMerks** [comment]
@whatisgravity Thank you, the arm-7 version is working perfectly!
I'll keep keep a log on how the pi is performing CPU-wise and network-wise . 
If it can indeed contribute the network in a positive way, it could be interesting to build a ready-to-use distro that automatically runs the latest geth. I'm sure _many_ people have pi's laying around - waiting for a next project.

**Comment by whatisgravity** [comment]
tar.gz files updated to tar.bz2
