### ISSUE TITLE
Ethereum Classic Light Client

### ISSUE THREAD

**Issue by JikkuJose** [ethereumproject/go-ethereum#103]
#### System information

Geth version: 
Version: 1.5.4-stable
Git Commit: b70acf3c5bd335d8dedc2a5aa6eff05c4c32105e
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.7.4
OS: darwin

OS & Version: OSX

#### Expected behavior

Light client should be working as for the ETH

#### Actual behavior

Seems no servers exist. Synchronization getting failed with following message:

`eth/downloader/downloader.go:305] Synchronisation failed: peer is unknown or unhealthy`

#### Steps to reproduce the behavior

Run geth with `oppose-dao-fork` flag

**Comment by pascaldekloe** [comment]
Sorry for the long delay @JikkuJose.
It seems you're using a really old version. We're at 3.3.0 now. I'm closing the issue. If you're still seeing problems feel free to reopen this one and I'll help you.

**Comment by JikkuJose** [comment]
Just tried the latest version, v4.1.0. I still don't see an option to run a light client?

**Comment by whilei** [comment]
@JikkuJose That's correct, at this point geth supports only `--fast` and `full [default]` sync.

**Comment by JikkuJose** [comment]
@whilei so the only way is to sync the whole chain?
