### ISSUE TITLE
Remove JIT

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#105]
It's incompatible with new changes, and even EF has removed it from Geth

**Comment by realcodywburns** [comment]
It is extremely annoying, to say the least. Even when it is explicitly disabled, it still randomly starts.

**Comment by splix** [comment]
@realcodywburns right, annoying. I've stopped in in PR #107, please review

**Comment by splix** [comment]
I tried to remove it completely, but I see there're many references in the code, so I'll keep it until HF. Stopping it from random starts is enough for now

**Comment by splix** [comment]
It seems that EF didn't remove it, I probably looked at wrong place. But anyway, I think we need to remove it.
My position is that JIT VM is a premature optimization. OPCODES list and prices aren't finished yet, and also this part doesn't look like a bottleneck (IO & statedb are most expensive), so there is no reason to have such extra complexity and code duplication for now. Better to remove

**Comment by elaineo** [comment]
What was the purpose of JIT VM randomization?

**Comment by splix** [comment]
@elaineo testing on real users :)

**Comment by splix** [comment]
doesn't work, see #148
