### ISSUE TITLE
Accept domain name in enode address

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#118]
Currently in p2p/discover/node.go:
> // The hostname can
> // only be given as an IP address, DNS domain names are not allowed.
> // The port in the host name section is the TCP listening port.

So we can't use `enode://<hex node id>@seed.example.com:30303`
only `enode://<hex node id>@10.3.58.6:30303` is accepted

`ParseNode` should resolve domain name to IP if provided

**Comment by pascaldekloe** [comment]
I'd like to keep the parsing of the URL separate from network lookups. That is, the DNS lookup should be part of the network connection.
