### ISSUE TITLE
Use master branch for development

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#121]
Right now this repository is organized by model called Git Flow (http://nvie.com/posts/a-successful-git-branching-model/) Which means that development is made in develop branch, and merged into master when release is ready. We have two main branches, both protected, merge with review twice, etc

Alternative model is when all development happen in master branch, with PR from branched made for a feature. Release bugfixes you make a special branch. This model is more natural, more usable with GitHub UI and more common this days. Called GitHub Flow http://scottchacon.com/2011/08/31/github-flow.html or even GitLab Flow https://about.gitlab.com/2014/09/29/gitlab-flow/

If there're no disagreement I'm merging current development in master and removing develop branch. All future PRs will be merged into master.

**Comment by mikeyb** [comment]
Either is fine in my opinion.  As long as there is a consensus on flow I don't really see a difference.  I personally use Git Flow method in my projects, but have also done single branch and they both work just fine.  There is definitely a lot less confusion on single branch model, but I prefer a little chaos for the separation.

**Comment by splix** [comment]
GitHub/GitLab Flow doesn't mean single branch, just selecting one master as main branch and all features in separate branch. With Git Flow it's expected to commit directly to _develop_ branch, which is not allowed in our repo anyway. So we have basically GitHub flow with PRs and branch-per-feature but on top of GitFlow's develop. A mix of both models. It just doesn't make sense.

So we're going to have _master_ with stable and tested code. Plus branches for new features, until they merged into master. As soon they got into master CI should automatically make a valid build. Of course we aren't going to release all such builds, only feature complete ones.

**Comment by mikeyb** [comment]
Yep.  Exactly.  I may have worded my comment wrong.  By single branch I mean that there is only a single branch that ever gets merges.  Many feature/bug branches, but they only ever merge into a single branch.

**Comment by splix** [comment]
Ah, yes, right. Right now we have two main branches, _master_ and _develop_, it's confusing

**Comment by mikeyb** [comment]
updated repo docs in https://github.com/ethereumproject/go-ethereum/pull/123 regarding this
