### ISSUE TITLE
Does --fast now work correctly for this version of geth?

### ISSUE THREAD

**Issue by jwg4** [ethereumproject/go-ethereum#13]
Just wanted to check if it is now possible to run geth on the Classic chain using a fast block , if doing this will put on the wrong chain, or if it just doesn't work.

If it is not working yet, it is straightforward to create such a block and add it to the client? Presumably we could use block 2000000 which is a long way downstream of the fork.

**Comment by whatisgravity** [comment]
I was under the impression it did work, please test it and report back your results. Without additional specifics it is hard to assist. If you do not test it before I have the time available I will test.

**Comment by jwg4** [comment]
I will check this as soon as I can.

**Comment by whatisgravity** [comment]
Any information regarding this?

**Comment by whatisgravity** [comment]
It appears to be working at least in the newest 1.4.11 release, if anyone is still having issues fast syncing. Open a ticket with as much information as possible.
