### ISSUE TITLE
Log metrics into a file

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#130]
Add a command line option to log all internal metrics and events into a machine readable format (like a JSON per line) for future import into other systems for monitoring and analytics. Such as Elastic, Splunk and others.

Metrics/events:
* connection (peer count, failures, new peers, etc)
* network (new blocks, new transactions from peers, etc)
* processing (imported block/transactions count, etc)
* api requests

**Comment by pascaldekloe** [comment]
Done: https://godoc.org/github.com/ethereumproject/go-ethereum/metrics
