### ISSUE TITLE
Can't 'make geth' with branch master?

### ISSUE THREAD

**Issue by songhungbk** [ethereumproject/go-ethereum#133]
#### System information

Geth version: `geth version 1.4`
OS & Version: Linux

I want to download block of EthereumClassic. When I clone go-ethereum, i can't make geth with branch master. However, I can 'make geth' when I checkout to branch develop. But I have issuse when i download block with branch develop.

**Comment by pascaldekloe** [comment]
Makefile has been dropped recently. Please see the README.md for buildinstructions.
