### ISSUE TITLE
Support for HW wallets (Ledger Nano S, Blue, Trezor)

### ISSUE THREAD

**Issue by arvicco** [ethereumproject/go-ethereum#136]
ETH dev team implemented some form of HW wallet support into geth: https://github.com/ethereum/go-ethereum/pull/3592

This feature is important for investors and long-term holders. It would be great for classic geth to support it as well.

**Comment by pascaldekloe** [comment]
Our code is pestered by too many native dependencies with C code. The ETH project has enough active developers to deal with those issues.

I'd like to invest into quality as in trade less code / functionality for more reliability. Arguably you get better security from simplicity than hardware support.

Not saying no here; just hesitant. Could you explain why this is important to investors and long term holders?

**Comment by arvicco** [comment]
Private keys that are kept online are target for hackers (https://www.cryptocoinsnews.com/eth-and-augur-investor-hacked-ethereum-price-dives-further/). Currently, the most secure way to keep private keys is in cold (offline, paper) storage. However, this type of storage does not allow transaction flexibility. HW wallets, such as Ledger or Trezor, allow the best combination of security and usability available in crypto space right now. 

Most serious investors in crypto space already employ HW wallets to manage their BTC holdings. However, previously such level of security was not available in altcoin space. ETH is the first major altcoin to offer client-level integration with popular HW wallets which gives them a serious competitive edge. If ETC could replicate this functionality it would be a good indication to crypto investors. Most of them already own Ledger or Trezor wallet and ability to add ETC holdings to their existing storage infrastructure will increase general demand for ETC token and will support further bootstrapping and development of Ethereum Classic ecosystem.

**Comment by splix** [comment]
@arvicco we're also started working on a new wallet for ETC, an HW wallets are planned there. We'll see how we can integrate that with Geth

**Comment by mikeyb** [comment]
If there are plans for a new wallet I would just EOL geth and stop supporting it.  Maintainability, Feature additions, and Security updates for this beast sounds like a grand waste of time if there is something new and built from the ground up coming.

+1 to using hardware wallets

**Comment by splix** [comment]
@mikeyb that different things actually. wallet is a JS application, which connects to Geth/Parity, but it going to have small backend part for signing transactions and other stuff needed only for wallets and other dapps

**Comment by whilei** [comment]
Closing, with reference to https://github.com/ethereumproject/emerald-rs for upcoming HW support.

If there come to be any more specific plans for HW support for geth and/or integration with `emerald`, we'll open a new issue as needed.
