### ISSUE TITLE
--datadir ignored when attaching to a running geth instance

### ISSUE THREAD

**Issue by MatBenetti** [ethereumproject/go-ethereum#15]
#### System information

Geth version: `1.4.10-stable-6aaf5f33`
OS & Version: OSX 10.11.6
#### Expected behaviour

Using
`geth --datadir "/path/to/another/ethereum/data/dir" attach`
should open a JavaScript console attached to the running (if exists, and previous started) geth instance.
#### Actual behaviour

Even if a path is specified with the `--datadir` flag, geth starts using always the default value

```
if runtime.GOOS == "darwin" {
            return filepath.Join(home, "Library", "Ethereum")
        } else if runtime.GOOS == "windows" {
            return filepath.Join(home, "AppData", "Roaming", "Ethereum")
        } else {
            return filepath.Join(home, ".ethereum")
        }
```
#### Steps to reproduce the behaviour

Start a geth instance using a different datadir
`geth --datadir "/tmp/differentdatadir"`
then try to attach to it lunching another geth instance using "attach" command
`geth --datadir "/tmp/differentdatadir" attach`

**Comment by MatBenetti** [comment]
I've found a way to make it works:

`geth --datadir "/tmp/another/data/dir" attach ipc:/tmp/another/data/dir/geth.ipc`

i don't know if this was by design or simply a trick

**Comment by mmgen** [comment]
Thanks.  I was wondering how to fix this.  It is ugly though.  This poorly thought-out stuff in geth is annoying.

**Comment by karalabe** [comment]
`geth attach ipc:/tmp/another/data/dir/geth.ipc`

**Comment by whatisgravity** [comment]
@karalabe Thanks for being awesome and helping to provide
