### ISSUE TITLE
Mist wallet synchronisation

### ISSUE THREAD

**Issue by abidarahma** [ethereumproject/go-ethereum#151]
I have a problem synchronising with ethereum Blockchain as I get the "potential rewrite attack"
What should I do?
I am running on Windows 7
![capturee](https://cloud.githubusercontent.com/assets/26059080/23545033/d86b8cfc-fff9-11e6-8107-9c86e9edf9c2.PNG)

**Comment by pascaldekloe** [comment]
Nothing. You're fine.
We're working on more clear log messages. #111

Thank you for reporting this issue. :+1:

**Comment by abidarahma** [comment]
yes but my wallet is unable to synchronise for a day now :/ 
My transactions are on hold !

**Comment by splix** [comment]
@abidarahma it can take 2 days to do full synchronize of the chain

**Comment by abidarahma** [comment]
Got you. Yet I am working on testnet and this is not my first time using the wallet. 
I have found it really weird that the sync didn't even start :/
![11](https://cloud.githubusercontent.com/assets/26059080/23551819/d1c1799c-0018-11e7-8d51-ae19dc11a3e6.PNG)

**Comment by splix** [comment]
Oh, it's possible that it didn't find peers yet. We're actually working on updated list of peers, initial one is outdated now, most of initial peers are down now. That's especially true for testnet

**Comment by abidarahma** [comment]
Ok thanks !

**Comment by pascaldekloe** [comment]
boot1.etcdevteam.com: enode://afdc6076b9bf3e7d3d01442d6841071e84c76c73a7016cb4f35c0437df219db38565766234448f1592a07ba5295a867f0ce87b359bf50311ed0b830a2361392d@104.154.136.117:30403
boot2.etcdevteam.com: enode://21101a9597b79e933e17bc94ef3506fe99a137808907aa8fefa67eea4b789792ad11fb391f38b00087f8800a2d3dff011572b62a31232133dd1591ac2d1502c8@104.198.71.200:30403

**Comment by abidarahma** [comment]
the same problem persists, what should I do?

**Comment by sjmackenzie** [comment]
![wp_20170313_15_52_05_pro](https://cloud.githubusercontent.com/assets/158321/23862877/276403d2-0849-11e7-96d1-573a29b39a70.jpg)

@buzzlite (on slack just reported an issue) and could be the cause of this issue.

**Comment by pascaldekloe** [comment]
Hi @abidarahma, Unfortunately we are unable to reproduce this problem. It could be the RMI connection with Mist.

**Comment by Shumkar** [comment]
>@splix thinks it's IPC related. Can you verify that the data transfer works @Shumkar?

Sorry... Data transfer between what and what?

**Comment by pascaldekloe** [comment]
Geth and Mist, the IPC connectivity...

**Comment by Shumkar** [comment]
Ethereum Classic Wallet 0.9.1 seems to be unable to detect the presence of Geth neither in its resources/geth folder nor in Windows processes.

It says "Error running downloaded binary" in all 3 cases: there is no Geth in this folder; there is Geth but it is not launched; there is Geth and it's launched.

If I understand correctly, in the 1st case it should download Geth; in the 2nd it should launch it; in the 3rd it should connect to it. But it don't.

When I switch to Ethereum Classic Wallet 0.8.1, it works (very sloooowly but I think it's another issue).

**Comment by sjmackenzie** [comment]
A different user pm'ed me with this issue.

**Comment by Deadwing888** [comment]
Issue for me as well

**Comment by pascaldekloe** [comment]
Two developers tried to reproduce the issue on Windows and failed. Mist has no maintainer at the moment. Our developers are working hard on a replacement. https://github.com/ethereumproject/emerald-wallet

**Comment by abidarahma** [comment]
Great news ! 
FYI: After reinstalling the wallet for so many times, it is now syncing taking only the 10th of the volume it tooks before (I am talking about the ledger 2 GB vs 20 GB before) 
Hope this helped stabilizing the next versions of eth wallet :)

**Comment by marc1968** [comment]
hi Shumkar  

did you solve your issue and what ethereum classic wallet you are using mind to share me the link ?

**Comment by whilei** [comment]
Closing as stale
