### ISSUE TITLE
make geth does not work

### ISSUE THREAD

**Issue by ucwong** [ethereumproject/go-ethereum#155]
anyone show me clearly?

what "go install github.com/ethereumproject/go-ethereum/cmd/..." means?

and how to build from source code?

**Comment by pascaldekloe** [comment]
Duplicates #133

**Comment by pascaldekloe** [comment]
Go is a command you'll get from installing the Go language. http://golang.org/dl

**Comment by Raskal8** [comment]
@ucwong Follow this guide to build from source...

https://github.com/ethereum/go-ethereum/wiki/Developers%27-Guide

**Comment by pascaldekloe** [comment]
Except for that we don't have non vendored dependencies nor any contribution rules.

**Comment by Raskal8** [comment]
True...
My only hurdle was that I wasn't cloning to the correct GOPATH unfortunately my programming knowledge is limited to what I can google ;)

I and I'm sure everyone else appreciates all you've done to keep ETC going Pascaldekloe many many Thanks to you and the other contributors...
