### ISSUE TITLE
Potential rewrite attack logs

### ISSUE THREAD

**Issue by rawodb** [ethereumproject/go-ethereum#16]
I've started noticing warnings for "potential rewrite attack" in geth 1.4.10-stable-6aaf5f33

=======================================

I0805 05:54:43.005168 eth/downloader/downloader.go:1195] Peer fd25cfe81d84cc67 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:55:47.687278 eth/downloader/downloader.go:1195] Peer 78e257fb2aa36dd4 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:55:51.751628 eth/downloader/downloader.go:1195] Peer 01b9089693c3bf39 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:56:11.468304 eth/downloader/downloader.go:1195] Peer 4b1f3a45968d9c89 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:56:18.668953 eth/downloader/downloader.go:1195] Peer a215d5fb6fdec8c5 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:56:27.672463 eth/downloader/downloader.go:1195] Peer f423653efe5fceda [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:56:31.741424 eth/downloader/downloader.go:1195] Peer e56ac587e922a073 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:57:51.540899 eth/downloader/downloader.go:1195] Peer 3fc9fe134408d85e [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:57:52.270435 eth/downloader/downloader.go:1195] Peer 37efa7e32ae675b8 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:58:28.838118 eth/downloader/downloader.go:1195] Peer 4b1f3a45968d9c89 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1921606 [00000000▒] <= #1921606 limit
I0805 05:59:24.985412 eth/downloader/downloader.go:1195] Peer 98f2b6ff1b2fd3d7 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 11.829638946s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit
I0805 05:59:36.790843 eth/downloader/downloader.go:1195] Peer 4b1f3a45968d9c89 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 11.829638946s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit
I0805 05:59:38.699549 eth/downloader/downloader.go:1195] Peer 5228df422a51dcec [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 11.829638946s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit
I0805 05:59:41.244206 eth/downloader/downloader.go:1195] Peer 0ed8a3a4636f5fc0 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit
I0805 05:59:46.988710 eth/downloader/downloader.go:1195] Peer 39c0a789f3680708 [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit
I0805 05:59:55.412711 eth/downloader/downloader.go:1195] Peer c13ee7b82fd3898d [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 20s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit
I0805 06:00:03.302546 eth/downloader/downloader.go:1195] Peer 78129e171bb7484a [hs 0.00/s, bs 0.00/s, rs 0.00/s, ss 0.00/s, miss    0, rtt 11.829638946s]: potential rewrite attack: #1922167 [00000000▒] <= #1922167 limit

**Comment by jwg4** [comment]
I think these are transactions from the forked network.

**Comment by jwg4** [comment]
I believe that you are peering with nodes on the other chain. This piece of code is trying to find the point at which your chain and the peer's chain agree. If if finds that they do not agree over a long chain, of the maximum number of blocks which is allowed as a possible accidental fork, then it gives this error.

I don't know if making these checks is affecting performance. If it is the possible solution could be to configure known bad blocks which allow one to instantly reject the hardforked chain.

**Comment by whatisgravity** [comment]
Badblocks is already being used, but it is currently not disconnecting peers on the other side of the network split. This is being included in the next 1.4 release.
