### ISSUE TITLE
index allocation went beyond available resultCache space

### ISSUE THREAD

**Issue by ADumaine** [ethereumproject/go-ethereum#162]
You've encountered a sought after, hard to reproduce bug. Please report this to the developers <3 https://github.com/ethereumproject/go-ethereum/issues
index allocation went beyond available resultCache space
c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/queue.go:651
goroutine 714 [running]:
runtime/debug.Stack(0x51, 0x0, 0x0)
        C:/go/src/runtime/debug/stack.go:24 +0x80
runtime/debug.PrintStack()
        C:/go/src/runtime/debug/stack.go:16 +0x29
github.com/ethereumproject/go-ethereum/common.Report(0xc0441d57c0, 0x1, 0x1)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/common/debug.go:34 +0x239
github.com/ethereumproject/go-ethereum/eth/downloader.(*queue).reserveHeaders(0xc04a5502c0, 0xc05a2e2900, 0x80, 0xc04f597bc0, 0xc042966110, 0xc04f597bf0, 0xc04f597c20, 0xe048f8, 0xc052eb1a40, 0xc0441d58a0, ...)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/queue.go:651 +0x875
github.com/ethereumproject/go-ethereum/eth/downloader.(*queue).ReserveBodies(0xc04a5502c0, 0xc05a2e2900, 0x80, 0x0, 0xc05a2e2900, 0x0, 0x0)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/queue.go:602 +0xfb
github.com/ethereumproject/go-ethereum/eth/downloader.(*queue).ReserveBodies-fm(0xc05a2e2900, 0x80, 0x0, 0x0, 0x0, 0x0)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:950 +0x45
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).fetchParts(0xc0427e08c0, 0x125f6e0, 0xc0421f82a0, 0xc04a82e5a0, 0xc04ed1ca00, 0xc0495eae70, 0xc0441d5ed0, 0xc0441d5f30, 0xc0441d5f20, 0xc0441d5f10, ...)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:1174 +0x71e
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).fetchBodies(0xc0427e08c0, 0x3028c9, 0xc0525d5f90, 0xc04c508a40)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:951 +0x39b
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).syncWithPeer.func5(0x672227300000008, 0xe064d0)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:444 +0x3e
github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).spawnSync.func2(0xc04ed1c9d0, 0xc04fbec960, 0xc04f2256c0)
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:526 +0x58
created by github.com/ethereumproject/go-ethereum/eth/downloader.(*Downloader).spawnSync
        c:/gopath/src/github.com/ethereumproject/go-ethereum/eth/downloader/downloader.go:526 +0x11b
#### BUG! PLEASE REPORT ####

**Comment by pascaldekloe** [comment]
Ouch! I saw this ugly an hour ago with d2ef7ff17841824ec9dcf9ff148057a2450e97b1. :joy: Thank you for the effort. I'm looking into it now.
