### ISSUE TITLE
docker upgrade

### ISSUE THREAD

**Issue by benjyz** [ethereumproject/go-ethereum#168]
last change is 1 year old
https://github.com/ethereumproject/go-ethereum/blob/master/containers/docker/master-ubuntu/Dockerfile

**Comment by pascaldekloe** [comment]
Yes, I have no idea why you'd want to have a container for a single binary either. Let's drop this madness.

**Comment by benjyz** [comment]
because of OS level dependency isolation

**Comment by pascaldekloe** [comment]
Except for Windows we're fine. Otherwise that's an issue.

**Comment by splix** [comment]
@benjyz there is another project for Docker images https://github.com/ethereumproject/Cloud-Template/tree/master/Docker (it needs to be updated to latest Geth though)
