### ISSUE TITLE
downloader test fails sometimes

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#177]
```
--- FAIL: TestFakedSyncProgress62 (0.71s)
	downloader_test.go:1678: Final progress mismatch: have 0/969/1009, want 0-1009/1009/1009
FAIL
FAIL	github.com/ethereumproject/go-ethereum/eth/downloader	430.515s
```

fails half the time

**Comment by splix** [comment]
@yograterol can you take a look at this?

**Comment by whilei** [comment]
[Still happening](https://travis-ci.org/ethereumproject/go-ethereum/jobs/225756436), albeit less often. Is upping the sleep times the only way out?

**Comment by whilei** [comment]
Noting for reference that it fails in different places. Some recent examples...
- https://travis-ci.org/ethereumproject/go-ethereum/jobs/225724829
- https://travis-ci.org/ethereumproject/go-ethereum/jobs/225756436
- https://travis-ci.org/ethereumproject/go-ethereum/jobs/225985955
- https://travis-ci.org/ethereumproject/go-ethereum/jobs/226165807

**Comment by whilei** [comment]
Since upping to `400 * time.Millisecond` for the sleeps I haven't seen nearly as many issues.

Could be the PR (#189) code is slow, Travis/AppVeyor i/o is inconsistent, we got lucky... Closing until it bothers me or someone else again.
