### ISSUE TITLE
Could install go-ethereum 

### ISSUE THREAD

**Issue by vupv** [ethereumproject/go-ethereum#179]
Hi all, Pls help me can not install go-ethereum  

root@localhost: git clone https://github.com/ethereumproject/go-ethereum

root@localhost: /home/ethereumproject/go-ethereum# make geth
make: *** No rule to make target 'geth'.  Stop.

**Comment by mikeyb** [comment]
da fuq, `Makefile` is gone from repo since https://github.com/ethereumproject/go-ethereum/commit/29b176af0a938b399d7b6d6d9387f19dcfa0313f @splix @pascaldekloe 

Might want to update README & wiki instructions if golang installer is the only applicable method.  The install instructions are not very clear on the README and completely wrong in the wiki ;)

**Comment by splix** [comment]
Oh, I thought readme is already updated. It's `go build ./cmd/geth` now

**Comment by mikeyb** [comment]
It is, but arguably a very confusing instruction, especially for those of us who are not familiar with golang

**Comment by mikeyb** [comment]
You might also want to include instructions how to configure GO properly.  Installing go on an ubuntu/debian system makes no sense.

```
~/p/go-ethereum ❯❯❯ go build ./cmd/geth                                                                                         install_instructions ✱
cmd/geth/flag.go:32:2: cannot find package "github.com/ethereumproject/ethash" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/ethash (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/ethash (from $GOPATH)
cmd/geth/accountcmd.go:24:2: cannot find package "github.com/ethereumproject/go-ethereum/accounts" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/accounts (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/accounts (from $GOPATH)
cmd/geth/chaincmd.go:27:2: cannot find package "github.com/ethereumproject/go-ethereum/common" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/common (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/common (from $GOPATH)
cmd/geth/accountcmd.go:25:2: cannot find package "github.com/ethereumproject/go-ethereum/console" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/console (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/console (from $GOPATH)
cmd/geth/chaincmd.go:29:2: cannot find package "github.com/ethereumproject/go-ethereum/core" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/core (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/core (from $GOPATH)
cmd/geth/chaincmd.go:30:2: cannot find package "github.com/ethereumproject/go-ethereum/core/state" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/core/state (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/core/state (from $GOPATH)
cmd/geth/chaincmd.go:31:2: cannot find package "github.com/ethereumproject/go-ethereum/core/types" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/core/types (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/core/types (from $GOPATH)
cmd/geth/accountcmd.go:26:2: cannot find package "github.com/ethereumproject/go-ethereum/crypto" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/crypto (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/crypto (from $GOPATH)
cmd/geth/flag.go:39:2: cannot find package "github.com/ethereumproject/go-ethereum/eth" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/eth (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/eth (from $GOPATH)
cmd/geth/flag.go:40:2: cannot find package "github.com/ethereumproject/go-ethereum/ethdb" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/ethdb (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/ethdb (from $GOPATH)
cmd/geth/flag.go:41:2: cannot find package "github.com/ethereumproject/go-ethereum/event" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/event (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/event (from $GOPATH)
cmd/geth/accountcmd.go:27:2: cannot find package "github.com/ethereumproject/go-ethereum/logger" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/logger (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/logger (from $GOPATH)
cmd/geth/accountcmd.go:28:2: cannot find package "github.com/ethereumproject/go-ethereum/logger/glog" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/logger/glog (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/logger/glog (from $GOPATH)
cmd/geth/main.go:40:2: cannot find package "github.com/ethereumproject/go-ethereum/metrics" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/metrics (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/metrics (from $GOPATH)
cmd/geth/flag.go:44:2: cannot find package "github.com/ethereumproject/go-ethereum/miner" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/miner (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/miner (from $GOPATH)
cmd/geth/cmd.go:30:2: cannot find package "github.com/ethereumproject/go-ethereum/node" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/node (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/node (from $GOPATH)
cmd/geth/boot.go:19:8: cannot find package "github.com/ethereumproject/go-ethereum/p2p/discover" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/p2p/discover (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/p2p/discover (from $GOPATH)
cmd/geth/flag.go:47:2: cannot find package "github.com/ethereumproject/go-ethereum/p2p/nat" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/p2p/nat (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/p2p/nat (from $GOPATH)
cmd/geth/flag.go:48:2: cannot find package "github.com/ethereumproject/go-ethereum/pow" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/pow (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/pow (from $GOPATH)
cmd/geth/cmd.go:31:2: cannot find package "github.com/ethereumproject/go-ethereum/rlp" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/rlp (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/rlp (from $GOPATH)
cmd/geth/consolecmd.go:26:2: cannot find package "github.com/ethereumproject/go-ethereum/rpc" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/rpc (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/rpc (from $GOPATH)
cmd/geth/flag.go:50:2: cannot find package "github.com/ethereumproject/go-ethereum/whisper" in any of:
	/usr/lib/go/src/pkg/github.com/ethereumproject/go-ethereum/whisper (from $GOROOT)
	/home/miko/apps/go/src/github.com/ethereumproject/go-ethereum/whisper (from $GOPATH)
cmd/geth/monitorcmd.go:32:2: cannot find package "github.com/gizak/termui" in any of:
	/usr/lib/go/src/pkg/github.com/gizak/termui (from $GOROOT)
	/home/miko/apps/go/src/github.com/gizak/termui (from $GOPATH)
cmd/geth/accountcmd.go:29:2: cannot find package "gopkg.in/urfave/cli.v1" in any of:
	/usr/lib/go/src/pkg/gopkg.in/urfave/cli.v1 (from $GOROOT)
	/home/miko/apps/go/src/gopkg.in/urfave/cli.v1 (from $GOPATH)
```

At this point I will have abandoned your go-ethereum implementation

**Comment by pascaldekloe** [comment]
The Go Ethereum project uses Go's standard build tooling. It does not need any additional configuration. This project is not suitable for beginners in any way, so what good would a step by step build guide do?

https://golang.org/doc/code.html

**Comment by splix** [comment]
@pascaldekloe we still some documentation for non-professionals. Because many of miners/business prefer to build directly from sources, they have their reasons. And most of these people have no experience with programming at all.

**Comment by mikeyb** [comment]
As my previous comment showed, it *DOES* need additional configuration.

You cannot just clone the repo and build it after installing golang.  Personally I find GO setup and configuration idiotic, why it doesn just choose sane defaults like every other application out there is beyond me.  Instead you have to configure awkward paths and even then, the build of go-ethereum still fails if you dont have any of the required dependencies (as shown above).

`WontFix` this all you want, but prepare to look unfriendly and lose new users who just want to run a `make` command to build their sources instead of go's silly proprietary configuration methods.

Also,  this project used to be suitable for beginners, as 99% of your user base will be beginners.  Why would you take such a stance against your userbase?

Also, in the repo Installation instructions it says:

`go install github.com/ethereumproject/go-ethereum/cmd/...`

This is flat out wrong and you should put commands that can be copy and pasted such as:

```
git clone https://github.com/ethereumproject/go-ethereum.git
cd go-ethereum
go build ./cmd/geth
```

@vupv good luck running your pool

**Comment by pascaldekloe** [comment]
No @mikeyb, the single line instruction is correct. Your example only works when the `go-ethereum` checkout directory resides in a path ending with `src/github.com/ethereumproject/go-ethereum` and that is confusing.

We have signed releases. If that's not good enough then some will have to support all the questions that will arise from people building stuff they don't understand. Feel free to reopen this issue. :-)

**Comment by mikeyb** [comment]
```
~/projects ❯❯❯ go install github.com/ethereumproject/go-ethereum/cmd/...
../.go/src/github.com/ethereumproject/go-ethereum/accounts/abi/bind/bind.go:32:2: cannot find package "golang.org/x/tools/imports" in any of:
	/usr/lib/go/src/pkg/golang.org/x/tools/imports (from $GOROOT)
	/home/miko/.go/src/golang.org/x/tools/imports (from $GOPATH)
../.go/src/github.com/ethereumproject/go-ethereum/rpc/notification.go:20:2: cannot find package "context" in any of:
	/usr/lib/go/src/pkg/context (from $GOROOT)
	/home/miko/.go/src/context (from $GOPATH)
```

Yep, works just great.  Good luck with that attitude!

**Comment by mikeyb** [comment]
Hint...I know how to make it work.  I am trying to show you the obvious faults in your logic for anyone else who wants to use your application.  Whether you care or not is a different story.

**Comment by pascaldekloe** [comment]
The error you are seeing is because your Go environment is too old. The context package appeared in version 1.7. Every Go developer knows this. You see why this is not that easy @mikeyb ?

**Comment by mikeyb** [comment]
Just showing you what every ubuntu/debian user will see who doesnt compile golang from source or find a repo with an updated version.  I get there is a bit of technical requirement to use an awkward language on a distro that sucks at staying up to date.  My intention is to show you the experience of your users.

Nobody really cares if the core dev of a project can build the project with ease, what matters is your userbase can use the application, otherwise you are programming for no reason,

**Comment by mikeyb** [comment]
Hint...Your users are not Go Developers...

**Comment by mikeyb** [comment]
@arvicco https://github.com/ethereumproject/ECIPs/issues/23#issuecomment-274109839

Still very much the same around here :)

Cheers and hope you are well good buddy!

**Comment by pascaldekloe** [comment]
Demanding that the average user can build a project is an additional burden for the developers. Things are hard enough as is. You are not helping ETC at all @mikeyb! :-(

**Comment by mikeyb** [comment]
`Demanding that the average user can build a project is an additional burden for the developers.` It is your only fu&$ing job!!

**Comment by mikeyb** [comment]
Pointing out severe flaws in your application for the `users who need to use it` is not helping?  Got it.  Maybe it would be better if I just stopped commenting on flawed documentation and left this shit show to show shit

**Comment by lostinblue** [comment]
Im building back in a make file, its up to you if you want it
