### ISSUE TITLE
Wiki is missing

### ISSUE THREAD

**Issue by mmgen** [ethereumproject/go-ethereum#18]
I think we should clone the geth wiki too, so it can be read and edited.

**Comment by mmgen** [comment]
I think we should clone the geth wiki too, so we can read and edit it.

**Comment by whatisgravity** [comment]
I have cloned it and did some minor updates to it. It will need additional information explaining the network split and many updates to match the new repository.

If you are have time to contribute to that please check the volunteer repository in this organization.
