### ISSUE TITLE
Wiki install docs wrong + links pointing to ETH

### ISSUE THREAD

**Issue by mikeyb** [ethereumproject/go-ethereum#181]
https://github.com/ethereumproject/go-ethereum/wiki/Building-Ethereum

**Comment by pascaldekloe** [comment]
Indeed, the script is outdated and Docker is gone. I'll remove the Wiki content, ok @splix?

About ARM, especially with the popular Raspbery this would be a nice to have. The issue is that we don't have a buildserver for it. Suggestions are welcome.

**Comment by whilei** [comment]
Adding to the list: 
- dead link: `bash <(curl -L https://install-geth.ethereum.org)` @ https://github.com/ethereumproject/go-ethereum/wiki/Building-Ethereum
- doesn't exist: [Developers' Guide](https://github.com/ethereumproject/go-ethereum/wiki/Developers'-Guide) @ wiki Home

**Comment by whilei** [comment]
Also I think [Homebrew install instructions for OSX](https://github.com/ethereumproject/go-ethereum/wiki/Installation-Instructions-for-Mac) will point to ETH?
```shell
brew tap ethereum/ethereum
brew install ethereum
```

**Comment by pascaldekloe** [comment]
Contributing should be fun @whilei. We need public contributions, not rules. So yes please, burn'm all. 😊

**Comment by whilei** [comment]
Excellent. I propose we also add a link to https://ethereumclassic.github.io on the repo's website attribute.
