### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#185]
It seems there is a file handles "leak". 

First of all, a customer noticed an issue that Geth sometimes unable to sign transaction because failed to read addr key file (there were thousands of keys on that instance).

After extensive testing with new versions I've noticed that OS starts working incorrectly after few hours of sync. And it seems that the reason is the availability of file handles. For most fs operations OS starts to fail with `Too many open files` and Geth throws errors like `core/database_util.go:312] failed to store block total difficulty into database: write chain/chaindata/059333.log: invalid argument`

**Comment by pascaldekloe** [comment]
Can you provide the `lsof` command results? Also, I see a data race in the map! I think we should start using a DB. There are many native Go key-value instances available these days.

**Comment by whilei** [comment]
@pascaldekloe Correct me if I'm wrong, but isn't `database_util` here using LevelDB already? 

My commit above was informed by reference to 
- https://github.com/google/leveldb/issues/181
- https://godoc.org/github.com/syndtr/goleveldb/leveldb/opt#Options

I haven't been able to reproduce the error (yet!) so I can't confirm that my commit actually works, but it may at least be a starting point... ?

**Comment by splix** [comment]
I'm not sure this is because of LevelDB. But really strange situation. It seems that it's something with the VM. I mean I have QEMU-based VM to run test nodes, and after that "too many open files" it became unusable, even after VM restart. I wasn't able to use Geth after restart. And only complete reboot of the host machine helped. That's quite weird

**Comment by whilei** [comment]
Yep, looks like you're right. Noticed 
```shell
I0414 14:12:32.048257 ethdb/database.go:63] Alloted 128MB cache and 1024 file handles to /Users/ia/Library/EthereumClassic/chaindata
```
and tracked it down. Looks like it's being handled appropriately for LDB.

**Comment by splix** [comment]
It seems that was OS misconfiguration. I think we can close it now
