### ISSUE TITLE
Make does not work

### ISSUE THREAD

**Issue by ethernomad** [ethereumproject/go-ethereum#2]
`make geth` does not work:
    build/env.sh go build -i -v -ldflags '-X main.gitCommit=50dd6cf024ffa6bd363fec783bdf680b2bd3d2ae' -o build/bin/geth ./cmd/geth
    cmd/geth/main.go:31:2: no buildable Go source files in /home/jbrown/go-ethereum/build/_workspace/src/github.com/ethereumproject/go-ethereum/Godeps/_workspace/src/github.com/ethereumproject/ethash
    Makefile:16: recipe for target 'geth' failed
    make: *** [geth] Error 1

**Comment by whatisgravity** [comment]
Ah, sorry about that. The folder exist but its technically a git submodule so I don't think it was pulled down without initializing the submodules. I fixed it locally and thought I had it fixed for the project.I will fix it now.

**Comment by whatisgravity** [comment]
This specific issue is now fixed, sorry about that. 

You should be able to clone it and make without issues, if you do have issues feel free to reopen the ticket and I will help troubleshoot. 

I had to rush a little to try to get this out fast as possible and did not yet have time to setup a dedicated dev environment to manage the upstream changes.
