### ISSUE TITLE
Setup Version Oracle Contract

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#20]
Setup and install version oracle contract

Review ways it can be controlled in a decentralized way

**Comment by whatisgravity** [comment]
http://etherscan.io/address/0xFA7B9770Ca4cb04296Cac84F37736d4041251CDF#code

**Comment by pascaldekloe** [comment]
The versioning oracle is gone with commit 932fe4ee520560bba57a9d4812fb8578e6728b8f.
