### ISSUE TITLE
Signing key '5B0131BE' doesn't appear to be on any public keyserver

### ISSUE THREAD

**Issue by brentalanmiller** [ethereumproject/go-ethereum#21]
I've tried:
http://keys.gnupg.net/
https://pgp.mit.edu/
http://keyserver.pgp.com/
and searching Google, but there doesn't seem to be a way download the public key.

**Comment by whatisgravity** [comment]
Sorry, currently it is just here: https://github.com/ethereumproject/volunteer/tree/master/Keys

I will leave this open until it is added to at least one public key server.

**Comment by whatisgravity** [comment]
Added to MIT PGP Public Key Server.
