### ISSUE TITLE
ECIP1017 feature

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#210]
A fork config feature, to enable ECIP1017 Monetary Policy https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md

With options:
* Era Size (=5,000,000)
* Reward Drop (=0.8)

Uncle reward, which is going to be dropped from 7/8 to 1/32 should be hardcoded and enabled after this feature will take effect

**Comment by whilei** [comment]
Closing via #220
