### ISSUE TITLE
geth crash (SIGSEGV)

### ISSUE THREAD

**Issue by innobrig** [ethereumproject/go-ethereum#218]
After running for a few days, the geth process on my server died with the following error message: 

I0430 00:25:09.355176 core/blockchain.go:947] imported 1 block(s) (0 queued 0 ignored) including 29 txs in 28.249709ms. #3635504 [13f1e6ec / 13f1e6ec]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5a34a6]

goroutine 106 [running]:
panic(0xbc3180, 0xc4200120d0)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/runtime/panic.go:500 +0x1a1
math/big.(*Int).Cmp(0x0, 0xc42020d620, 0x14acb20)
        /home/travis/.gimme/versions/go1.7.linux.amd64/src/math/big/int.go:314 +0x26
github.com/ethereumproject/go-ethereum/core/types.ChainIdSigner.Equal(0xc42020d620, 0xc420968e80, 0x13ec420, 0x14acb20, 0xbf3220)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/core/types/transaction_signing.go:137 +0x92
github.com/ethereumproject/go-ethereum/core/types.(*ChainIdSigner).Equal(0xc4209dc4f0, 0x13ec420, 0x14acb20, 0xc421d85dc0)
        <autogenerated>:36 +0x6f
github.com/ethereumproject/go-ethereum/core/types.Sender(0x13ec420, 0x14acb20, 0xc442b825a0, 0x0, 0x0, 0x0, 0xb77c80, 0xc420312480)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/core/types/transaction_signing.go:87 +0x3d6
github.com/ethereumproject/go-ethereum/core/types.(*Transaction).From(0xc442b825a0, 0x0, 0x0, 0xc400000000, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/core/types/transaction.go:172 +0x5b
github.com/ethereumproject/go-ethereum/eth.(*PublicTransactionPoolAPI).subscriptionLoop(0xc42329a960)
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/eth/api.go:962 +0x159
created by github.com/ethereumproject/go-ethereum/eth.NewPublicTransactionPoolAPI
        /home/travis/gopath/src/github.com/ethereumproject/go-ethereum/eth/api.go:952 +0x19f

**Comment by whilei** [comment]
Thanks for letting us know, @innobrig. I've got a patch in to (hopefully!) fix this.

**Comment by whilei** [comment]
And a note that it looks like this wasn't the first time: #178 _nil pointer dereference on tx sign_

**Comment by simulanics** [comment]
Problem still exists

Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51873e]

**Comment by simulanics** [comment]
> INFO [12-29|13:05:01.621] Block synchronisation started
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x51873e]

goroutine 590 [running]:
math/big.(*Int).Cmp(0xc00a5a71c0, 0x0, 0xac64d316de982260)
        /home/travis/.gimme/versions/go1.11.2.linux.amd64/src/math/big/int.go:319 +0x2e
github.com/ethereum/go-ethereum/core.(*BlockChain).insertSidechain(0xc008742000, 0xc00c00f6e0, 0xc00006b5d0, 0xc00006b501, 0x1, 0x1, 0xc00be7b378, 0x1, 0x1, 0xc00bb49f20, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1333 +0x10b2
github.com/ethereum/go-ethereum/core.(*BlockChain).insertChain(0xc008742000, 0xc008d3a1e0, 0x1, 0x1, 0x1, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1139 +0x2e15
github.com/ethereum/go-ethereum/core.(*BlockChain).InsertChain(0xc008742000, 0xc008d3a1e0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/core/blockchain.go:1088 +0xb89
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).importBlockResults(0xc000254000, 0xc008d3a1d8, 0x1, 0x1, 0x1, 0x0)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1490 +0x40e
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent(0xc000254000, 0x0, 0xc00a4c3f98)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:1464 +0x79
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).processFullSyncContent-fm(0x8, 0x1028320)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:479 +0x2a
github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync.func1(0xc000254000, 0xc00bee35c0, 0xc00b907830)
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0x59
created by github.com/ethereum/go-ethereum/eth/downloader.(*Downloader).spawnSync
        /home/travis/gopath/src/github.com/ethereum/go-ethereum/eth/downloader/downloader.go:491 +0xaf
