### ISSUE TITLE
Registrar Oracle Contracts

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#22]
These will need to be replaced with complementary contracts or re-evaluated. 

https://github.com/ethereum/go-ethereum/blob/290e851f57f5d27a1d5f0f7ad784c836e017c337/common/registrar/registrar.go

**Comment by pascaldekloe** [comment]
The version Oracle is gone with commit 932fe4ee520560bba57a9d4812fb8578e6728b8f.
