### ISSUE TITLE
Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

### ISSUE THREAD

**Issue by vupv** [ethereumproject/go-ethereum#232]
Hi Sammy,

I got very many  error while running your pool with Ethereum Classic Project. Could you pls help 

2017/05/12 14:30:56 Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)

**Comment by whilei** [comment]
Hi @vupv, I've got a couple of questions for you that may help us figure it out:
- What version of Geth are you running? 
- Are you using custom bootnodes, using a proxy, or customizing IPC or RPC in any way? _ie_ any flags that might be relevant?
- That URL there looks like a local address... are you connecting locally or through a private server in some way?

Also, if you can copy more of the log (as much as possible!) when this happens that would be helpful, too.

**Comment by vupv** [comment]
Hi  whilei ,
Thank for answer 

- "What version of Geth are you running?"
--> instance: Geth/v3.3.0-1-gdd95f05/linux/go1.7

-"Are you using custom bootnodes, using a proxy, or customizing IPC or RPC in any way? ie any --flags that might be relevant?"
--> No

-"That URL there looks like a local address... are you connecting locally or through a private server in some way?"
--> I'm connecting locally.
Log error 

2017/05/13 20:04:19 Policy state refresh complete
2017/05/13 20:04:24 Stats collection finished 6.804289ms
2017/05/13 20:04:29 Stats collection finished 5.824259ms
2017/05/13 20:04:34 Stats collection finished 5.834566ms
2017/05/13 20:04:39 Stats collection finished 6.089008ms
2017/05/13 20:04:44 Stats collection finished 11.835748ms
2017/05/13 20:04:45 Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/05/13 20:04:45 Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/05/13 20:04:47 Valid share from 0xa99db65eb7f5e1b565170d95e39b662db8fbd902@42.117.142.232
2017/05/13 20:04:49 Stats collection finished 5.430972ms
2017/05/13 20:04:54 Stats collection finished 4.16639ms
2017/05/13 20:04:59 Stats collection finished 4.57352ms
2017/05/13 20:05:04 Stats collection finished 7.334697ms
2017/05/13 20:05:05 Valid share from 0xa99db65eb7f5e1b565170d95e39b662db8fbd902@42.117.142.232
2017/05/13 20:05:09 Stats collection finished 5.09401ms
2017/05/13 20:05:14 Stats collection finished 4.4309ms
2017/05/13 20:05:15 Purged stale stats from backend, 46 shares affected, elapsed time 4.736823ms
2017/05/13 20:05:15 Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/05/13 20:05:15 Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/05/13 20:05:19 Stats collection finished 7.667345ms
2017/05/13 20:05:19 Policy state refresh complete

**Comment by whilei** [comment]
Joining with issue #235:
>Hi All,
My geth version below and I got very many error while download block. Could you pls help
instance: Geth/v3.3.0-1-gdd95f05/linux/go1.7

via @vupv
```
I0513 19:49:39.776589 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:49:47.443629 eth/downloader/downloader.go:299] Synchronisation failed: block header download canceled (requested)
I0513 19:50:08.681365 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:21.481392 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:25.501531 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:40.589863 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:54.810641 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:51:05.070043 eth/downloader/downloader.go:299] Synchronisation failed: block header download canceled (requested)
I0513 19:51:25.352517 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:51:30.941364 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:51:39.890809 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:26.098758 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:38.785240 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:45.799315 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:59.397332 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:03.653759 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:06.778238 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:22.322549 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:23.639988 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:25.309342 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:28.356923 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:31.508863 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
```

**Comment by whilei** [comment]
@vupv  

`Post http://127.0.0.1:5545: net/http: request canceled` makes me wonder if something is interfering with your outgoing requests. Is your port `5545` available and open during these transactions?

I'm also unable to find any log or error variables in our source code matching:
```
2017/05/13 20:05:15 Error while refreshing pending block on main: Post http://127.0.0.1:5545: net/http: request canceled (Client.Timeout exceeded while awaiting headers)
2017/05/13 20:05:19 Stats collection finished 7.667345ms
2017/05/13 20:05:19 Policy state refresh complete
```

**Comment by vupv** [comment]
@whilei 

We must restart geth after sometime for work fine and restart  sometime

**Comment by odeke-em** [comment]
This may or may not be directly related to this problem but I recall a bug in Go1.7(which matches the report https://github.com/ethereumproject/go-ethereum/issues/232#issuecomment-301247147)  https://github.com/golang/go/issues/16094 in which cancellations erroneously returned 'Timeout exceeded' errors. That Go bug is fixed Go1.8.

**Comment by odeke-em** [comment]
This may or may not be directly related to this problem but I recall a bug in Go1.7(which matches the report https://github.com/ethereumproject/go-ethereum/issues/232#issuecomment-301247147)  https://github.com/golang/go/issues/16094 in which cancellations erroneously returned 'Timeout exceeded' errors. That Go bug is fixed in Go1.8.

**Comment by vupv** [comment]
@odeke-em
My  instance: Geth/v3.5.0/linux/go1.8

**Comment by whilei** [comment]
Closing as stale and possibly resolved.
