### ISSUE TITLE
Test with 100k+ accounts

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#233]
Let's test how Geth works with tens and hundreds of thousands accounts.

* Is it able to create new accounts after that
* Is it able to list accounts through RPC
* Is it able to list accounts through command line
* Is it able to sign transaction

1k/10k/50k/100k/200k accounts

**Comment by whilei** [comment]
Possibly related to #185.

**Comment by whilei** [comment]
Addressed in PR/commit c5a701ea18715dc3fffddbb36d51815b30fdff71 and feature included in 3.5.0.
