### ISSUE TITLE
Synchronisation failed: block download canceled (requested)

### ISSUE THREAD

**Issue by vupv** [ethereumproject/go-ethereum#235]
Hi All,
My geth version below and I got very many error while download block. Could you pls help 
instance: Geth/v3.3.0-1-gdd95f05/linux/go1.7

I0513 19:49:39.776589 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:49:47.443629 eth/downloader/downloader.go:299] Synchronisation failed: block header download canceled (requested)
I0513 19:50:08.681365 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:21.481392 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:25.501531 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:40.589863 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:50:54.810641 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:51:05.070043 eth/downloader/downloader.go:299] Synchronisation failed: block header download canceled (requested)
I0513 19:51:25.352517 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:51:30.941364 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:51:39.890809 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:26.098758 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:38.785240 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:45.799315 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:52:59.397332 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:03.653759 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:06.778238 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:22.322549 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:23.639988 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:25.309342 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:28.356923 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)
I0513 19:53:31.508863 eth/downloader/downloader.go:299] Synchronisation failed: block download canceled (requested)

**Comment by whilei** [comment]
@vupv Please find this issue merged with your earlier issue #232. I think they're related.
