### ISSUE TITLE
Am I crazy or this ETC client does not support sending transactions?

### ISSUE THREAD

**Issue by letssee1** [ethereumproject/go-ethereum#240]
I mean, I may be wrong, but as far as I read the README file this program cannot send values to another address. What's the point to a cryptocurrency that cannot transfer? Whoever downloads this, needs to access unsafe web applications and send'em the private keys to transfer ETC? Is this true?

**Comment by whilei** [comment]
Hey @letssee1 -- I'm happy to say you can indeed send transactions with geth. One way to do it is via the javascript console (via web3.js). The command might look something like:
```bash
geth --exec='eth.sendTransaction({from: "0x036a03fc47084741f83938296a1c8ef67f6e34fa", to: "0xa8ade7feab1ece71446bed25fa0cf6745c19c3d5", value: web3.toWei(1, "ether")})' console
```
For more information on using the console, see:
- https://github.com/ethereumproject/go-ethereum/wiki/Contracts-and-Transactions
- https://github.com/ethereumproject/wiki/wiki/JavaScript-API#web3ethsendtransaction

For a more graphic (and still safe) experience you can also follow the instructions at https://classicetherwallet.com/#help __5. How do I run ClassicEtherWallet.com offline/locally?__

For more information about managing accounts, check out [the Accounts Wiki page](https://github.com/ethereumproject/go-ethereum/wiki/Managing-your-accounts).

Hope this helps! Feel free to reopen the issue if you have any more questions.

**Comment by letssee1** [comment]
Wow, that's great! You just explained me in ten lines WHY ETC WILL NEVER HAVE MASS ADOPTION!
Looks like bitcoin back in 2009!
Only skilled nerds can transact with this!
Such a lazy team, eh?

**Comment by letssee1** [comment]
RSK being deployed, forget about my question. 
https://s3.amazonaws.com/media.coindesk.com/live-stream/Day1_RSK_Lunch.html

With RSK Ethereum is already dead anyway.

**Comment by whilei** [comment]
FYI if you use https://classicetherwallet.com you don't have to send your private keys, and it requires no setup besides visiting the site (which doesn't store your key).
