### ISSUE TITLE
tests fail sporadically on CI

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#245]
Multiple tests fail seemingly without relation to one another and all unpredictably/inconsistently. Often in `downloader_test.go`. Seemingly most frequently on Travis.

My best guess is either insufficient sleep time to set data, which may mean that a solution involves swapping `sleep` for a waiter for anticipated value.

This Issue should be used to track downloader CI test fails in order to establish a better picture of when and where they happen, and propose/address solution attempts. Tracked failures should be when _only_ the presented test is the source of failure.

----
Branch: `master`, Commit: 5d69faf
Failed on: __Linux__ [Travis]
```
--- FAIL: TestFailedSyncProgress63Full (1.09s)
	downloader_test.go:1596: failed to synchronise blocks: retrieved hash chain is invalid
	downloader_test.go:1611: Final progress mismatch: have 0/940/1009, want 0-504/1009/1009
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/235704306

----
Branch: `monetary-policy`, Commit: 8d344a8
Failed on: __Linux__ [Travis]
```
--- FAIL: TestFastCriticalRestarts63 (15.26s)
	downloader_test.go:1788: failed to synchronise blocks in slow sync: no peers available or all tried for download
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/235838136

----
Branch: `accounts-cachedb`, Commit: 44d9eaa
Failed on: __OSX__ [Travis]
```
--- FAIL: TestPeerProtoReadMsg (0.00s)
	peer_test.go:93: peer returned: Subprotocol error
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/234563051

----
Branch: `release-3.4.0`, Commit: 712e861
Failed on: __OSX__ [Travis]
```
--- FAIL: TestFastCriticalRestarts64 (9.17s)
	downloader_test.go:1788: failed to synchronise blocks in slow sync: no peers available or all tried for download
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/234563051

----
Branch: `changelog`, Commit: f97403c2
Failed on: __Windows__ [AppVeyor]
```
--- FAIL: TestMissingHeaderAttack62 (0.50s)
	downloader_test.go:1170: failed to synchronise blocks: retrieved hash chain is invalid
```
https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.390#L137

----
Branch: `account-filepath`, Commit: ba03cb3
Failed on: __Linux__ [Travis]

```
--- FAIL: TestFastCriticalRestarts63 (12.82s)
	downloader_test.go:1788: failed to synchronise blocks in slow sync: no peers available or all tried for download
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/236465111

----

Branch: `add-status-command`, Commit: abae4da
Failed on: __Linux__ [Travis]

```
--- FAIL: TestFakedSyncProgress63Full (1.49s)
	downloader_test.go:1677: failed to synchronise blocks: retrieved hash chain is invalid
	downloader_test.go:1693: Final progress mismatch: have 0/936/1009, want 0-1009/1009/1009
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/237559982

----
Branch: `add-status-command`, Commit: 81fb1d9
Failed on: __Linux__ [Travis]
```
--- FAIL: TestPeerProtoReadMsg (0.00s)
	peer_test.go:93: peer returned: Subprotocol error
```
https://travis-ci.org/ethereumproject/go-ethereum/jobs/238081913

----
Branch: `monetary-policy`, Commit: e2b8789f
Failed on: __Windows__ [AppVeyor]
```
--- FAIL: TestDirectMessage (1.16s)
	whisper_test.go:118: direct message receive timeout
```
https://ci.appveyor.com/project/splix/go-ethereum/build/1.0.435

**Comment by whilei** [comment]
50ff54c: An attempt to solve `TestFastCriticalRestarts`

**Comment by tzdybal** [comment]
Accidentally found, that running tests locally with `-test.memprofilerate=1 -memprofile memprof.out` helps to reproduce the errors.
