### ISSUE TITLE
`--unlock` option get interrupted by log output

### ISSUE THREAD

**Issue by r8d8** [ethereumproject/go-ethereum#247]
Problem : CLI option `--unlock`, get's interrupted by log output (user unable to input password), so accounts can't be unlock

Expected: to unlock csv list fo accounts with `geth  --unlock <value>`

Enviroment: Ubuntu 16.04 LTS

**Comment by whilei** [comment]
One workaround is to use 

```
geth --password <passwordfile>
```

**Comment by whilei** [comment]
This happens on OSX, too, but I can unlock the account as long as I close my eyes (geth is still listening for input but log does not wait for input)
