### ISSUE TITLE
Geth shouldn't run with unknown chain

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#252]
Right now:
```
$ geth --chain mpnet.json
I0530 20:03:44.242868 ethdb/database.go:63] Alloted 128MB cache and 1024 file handles to /Users/splix/Library/EthereumClassic/mpnet.json/chaindata
I0530 20:03:44.256198 cmd/geth/flag.go:695] Did read chain configuration from database: /Users/splix/Library/EthereumClassic/mpnet.json/chaindata
I0530 20:03:44.256904 cmd/geth/flag.go:742] --------------------------------------------------------------------------------------------------------------
I0530 20:03:44.256939 cmd/geth/flag.go:744] Starting Geth Classic source
I0530 20:03:44.256950 cmd/geth/flag.go:745] Geth is configured to use blockchain: mpnet.json (ETC)
I0530 20:03:44.256965 cmd/geth/flag.go:747] 4 blockchain upgrades associated with this configuration:
I0530 20:03:44.256988 cmd/geth/flag.go:750]  1150000 Homestead
I0530 20:03:44.256998 cmd/geth/flag.go:750]  1920000 The DAO Hard Fork
I0530 20:03:44.257008 cmd/geth/flag.go:752]          with block 0x94365e3a8c0b35089c1d1195081fe7489b528a84b22199c916180db8b28ade7f
I0530 20:03:44.257017 cmd/geth/flag.go:750]  2500000 GasReprice
I0530 20:03:44.257065 cmd/geth/flag.go:750]  3000000 Diehard
I0530 20:03:44.257082 cmd/geth/flag.go:757] --------------------------------------------------------------------------------------------------------------
I0530 20:03:44.257595 cmd/geth/flag.go:317] WARNING: No etherbase set and no accounts found as default
I0530 20:03:44.258956 ethdb/database.go:63] Alloted 128MB cache and 1024 file handles to /Users/splix/Library/EthereumClassic/mpnet.json/chaindata
I0530 20:03:44.284299 ethdb/database.go:63] Alloted 16MB cache and 16 file handles to /Users/splix/Library/EthereumClassic/mpnet.json/dapp
```

I've used `--chain` instead of `--chain-config` there, but Geth succesfully launched with Mainnet config, but a different directory. It should fail with an error message instead

**Comment by whilei** [comment]
So it should check that the provided argument to `--chain` should not look like a <path> in general? Or maybe that it should not look like <path.json>?

_ie_
- ok: `--chain private.1`
- notok: `--chain private.json`
- ok: `--chain private`
- notok: `--chain ./private`

**Comment by splix** [comment]
I mean it knows all available preconfigured chains, right? `{id: ...}`. so anything not from that list is invalid

**Comment by whilei** [comment]
Currently it knows preconfigured chains `mainnet`, `morden`, and `testnet` (as an alias for morden). 

However, if users want to specify a `privatenet`, it currently allows that because with a custom external `--chain-config` users can create their own configurations for private networks and keep them in respective subdirs, and should read configuration from that db.

**Comment by splix** [comment]
yes, but I didn't specify `--chain-config` there, so `mpnet.json` is an invalid id for current configuration set (which has only mainnet, morden, and testnet)

**Comment by whilei** [comment]
Ok, I see -- so it should check default ids as well as available `/subdir`s for existing matching candidates?

**Comment by splix** [comment]
Only default ids only I think.

For available subdirs it will be not clear what configuration to use.

**Comment by whilei** [comment]
Yes, either we must either make a new feature to store chain configuration in chaindata db, or users must always use `--chain-config` to run custom networks. The latter makes more sense to me.

I will go ahead and make only default id's for `--chain`.

**Comment by splix** [comment]
It could be more usable to make `--chain` working for both cases:
* `--chain testnet` run by `id` if known (mainnet, testnet, morden, etc)
* `--chain mycustom.json` run with passed json config path

Let's use only ascii alphanumeric lowercase characters for ID plus few special symbols, say `[a-z0-9-_]{3,64}`. So you'll be able to distinguish if it's an id passed, or a path to config file

**Comment by whilei** [comment]
Do you imagine this would replace `--chain-config` or exist alongside?

I'm also wondering about storing external chain configuration in the `/mycustom` subdir, because it seems awkward that a user would be able to run `--chain=morden` but not `--chain=mycustom` for a DATA_DIR like:
```
/mainnet/...
/morden/...
/mycustom/...
```
... and what the specifics of that might be. I am thinking about it.

**Comment by splix** [comment]
We can do that: 
1. if a path to a json config specified, use it 
2. If an id, check bundled configs ids (mainnet/testnet/etc)
3. if it's not a standard config id, check directories, and if we found one with a `chain.json` file inside this directory, use it
4. nothing found - fails with error message

And yeah, that will replace --chain-config

**Comment by whilei** [comment]
I like that -- I was wondering too about for initial runs when using a new chain, potentially copying the specified `chain.json` (from an argument path) to the appropriate `/customnet` subdir, but think that is more messy than just saying "put your custom config files in their respective subdirectories."
