### ISSUE TITLE
--chain should replace --chain-config

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#254]
Desired usage:
```shell
# toggles morden testnet settings and uses '/morden' subdir
geth --chain morden 

# checks for existing subdir named "/custom"
# looks for valid `/custom/chain.json`
# if exist: use as external chain config, if not exist: error
geth --chain custom 
```

This makes setup flow:
```shell
mkdir -p $DATA_DIR/customnet
geth dump-chain-config $DATA_DIR/customnet/config.json
vi $DATA_DIR/customnet/config.json # make edits
geth --chain customnet
```

**Comment by whilei** [comment]
@splix do you think we should allow the `subdir/config.json` file to be named anything? or whitelisted names? or just one name?

**Comment by splix** [comment]
@whilei let's use just `subdir/chain.json`. With _anything_ it will be hard to find that file :) and maybe we'll introduce additional json files to that dir, for other configuration options (this one is for chain)
