### ISSUE TITLE
Configure Dev Mode chain from Chain Config

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#266]
Currently configured from code. Should be configurable in chain config file

**Comment by whilei** [comment]
@splix See #269 for how I handled this -- I made dev mode compatible with `--chain` option, so dev can be run with the same chain configuration options as normal, but did not add any fields to `chain.json` that are specific to dev mode settings and can be set with flags (max-peers, PoW, listen-port, gas-price, whisper).

For more (and persistent) dev mode configuration it might be worth considering implementing a config file that would parse flags (#116).

**Comment by splix** [comment]
I think you can ignore max-peers and ports. 

Most important part is PoW implementation. Basically we should allow to configure different consensus algorithms, with PoW type `ethash` and `ethash-test`
