### ISSUE TITLE
Docker repo

### ISSUE THREAD

**Issue by beholder0x2a** [ethereumproject/go-ethereum#27]
README was linking to non-existent Docker repo. I grabbed the ethereumproject namespace on Docker, so now it's a link to an empty repo instead. If someone wants to take Docker responsibilities, let me know and I'll make you owner.

**Comment by whatisgravity** [comment]
Thanks for taking the initiative on that task, great work

**Comment by realcodywburns** [comment]
Docker repo is setup and builds the master branch.  I will update the readme to point to docker https://hub.docker.com/r/ethereumclassic/etc-geth.  Azure template, aws script, juju charm, and vagrant instance will be added shortly pending testing. ETC BaaS image scripts are now in the cloud-template repo for easy reference
