### ISSUE TITLE
Sign commits and tags?

### ISSUE THREAD

**Issue by kleetus** [ethereumproject/go-ethereum#273]
Thanks for providing digital signatures for your release artifacts, this really helps!

Would you consider signing both git tags and commits as well?

Example, upon committing: 

git commit -S 

after code review and upon merging into main branch, the reviewer must check out the pull request topic branch locally and perform the merge and sign as well:

git merge --verify-signatures -S  topic-branch

I realize this is added burden on developers and possibly others, but we are dealing with people's money and I am sure you guys want the very best security for our community.

Slightly orthogonal to this issue, but the signature that is applied to release 3.5.0 is signed by Isaac, yet this key is only publicly available for 8 days as of this writing and it isn't signed by anyone else. So, even if I wanted to perform web of trust, I can't. I did some light googling, but I could not find out if Isaac's other communication channels state that this is his key and if he still has custody of it. I'll reach out to the email address and ask for this (not a great solution, but better than nothing).

**Comment by whilei** [comment]
@kleetus Thanks for bringing this to light -- a worthy point indeed.

I'm happy to begin signing my commits from here on out, and will begin to do so (as well as tags!).

To your point about my ethereal GPG presence; it is indeed a new key for me. Please find a [twit of mine](https://twitter.com/isaacardis/status/873545339734810624) and a [gist of mine](https://gist.github.com/whilei/5d5653a42bd490f0e652d935187e97c4) using Keybase to validate across networks. I'll also be happy to confirm with you via email, and to that point I also uploaded a [GPG clearsigned document to Google Drive](https://drive.google.com/file/d/0By_eWz3gwQwnTV9QcThFQ2piS28/view?usp=sharing). 

To your point about verifying merges, I just did some light looking-into about what it entails and found:

> ### Everyone Must Sign
> Signing tags and commits is great, but if you decide to use this in your normal workflow, 
> you’ll have to make sure that everyone on your team understands how to do so. 
> If you don’t, you’ll end up spending a lot of time helping people figure out how to 
> rewrite their commits with signed versions. Make sure you understand GPG and 
> the benefits of signing things before adopting this as part of your standard workflow.
> - https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work

So at this point I can't guarantee it, but will certainly bring it up with the team /+ community. I expect one of the challenges in this regard to be maintaining a balance between verifiable security, and public-facing accessibility, given a wide range of contributors and potential contributors -- as you mentioned. Currently neither https://github.com/ethereumproject/volunteer nor https://github.com/ethereumproject/rfc/blob/master/1/README.md define specs for signing/verifiability (at least to my knowledge), so there will need to be some level of consensus, documentation, and an agreed-upon timeframe.

Speaking personally, and with respect and still curiosity, my opinion at this point is that the added benefit of "Everyone Must Sign" is outweighed by the cost of time and accessibility. _However_, if you're interested in pursuing it -- and I welcome you to, if you want -- a good place to start might include a PR to the RFC as reference for a community discussion.
