### ISSUE TITLE
debug_traceTransaction does not exist, but it shows up in web3 API

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/go-ethereum#294]
See https://github.com/ethereumproject/go-ethereum/blob/9239a68f4217af0b251def997b74bc3399c9073f/internal/web3ext/web3ext.go#L294

Either we need to merge ETH's go-ethereum's code of TraceTransaction or remove the above API.

**Comment by whilei** [comment]
Thanks for noticing this -- and apologies for taking so long to reply. 

It seems worth adding the code to me; if it also does for you @sorpaas, I will work on that and submit a PR.

**Comment by sorpaas** [comment]
Adding this would allow Remix (https://github.com/ethereum/remix) to run over ETC's blockchain. So yeah, personally I'm for adding it.

**Comment by whilei** [comment]
Resolved with #329
