### ISSUE TITLE
raw tx signed by 'ChainIDSigner' would be removed accidentally

### ISSUE THREAD

**Issue by shawdon** [ethereumproject/go-ethereum#298]
Hi, team. @woodywang and I are colleagues, both working in Huobi.
Recently we found the transaction, which was signed by 'ChainIDSigner'([EIP155](https://github.com/ethereum/EIPs/blob/master/EIPS/eip-155.md)) and broadcast through RPC [SendRawTransaction](https://github.com/ethereumproject/go-ethereum/blob/master/eth/api.go#L1249-L1272), would not be included in a certain block in private network. The direct reason is that the tx was removed in function [validatePool](https://github.com/ethereumproject/go-ethereum/blob/master/core/tx_pool.go#L526).
However, my solution differs from @woodywang  (#293) . I prefer to set the original signer for the transaction decoded from raw transaction(#297).

**Comment by shawdon** [comment]
Here is the [code](https://github.com/ethereumproject/go-ethereum/blob/master/core/tx_pool.go#L537-L560) cause the tx removed:
```go
	for hash, tx := range pool.pending {
		sender, _ := tx.From() // ------------> sender.Hex() = "0x00...00"

		// Perform light nonce and balance validation
		balance := balanceCache[sender]
		if balance == nil {
			balance = state.GetBalance(sender)  // ------------> balance = 0
			balanceCache[sender] = balance
		}
		if past := state.GetNonce(sender) > tx.Nonce(); past || balance.Cmp(tx.Cost()) < 0 {
                        // ------------> balance.Cmp(tx.Cost()) < 0 = true, so the tx was removed
			// Remove an already past it invalidated transaction
			if glog.V(logger.Core) {
				glog.Infof("removed tx (%v) from pool: low tx nonce or out of funds\n", tx)
			}
			delete(pool.pending, hash)

			// Track the smallest invalid nonce to postpone subsequent transactions
			if !past {
				if prev, ok := gaps[sender]; !ok || tx.Nonce() < prev {
					gaps[sender] = tx.Nonce()
				}
			}
		}
	}
```

**Note the commet with "------------>"**

**Comment by shawdon** [comment]
#297

**Comment by whilei** [comment]
Thank you both!  It's nice to see to two different implementations side by side.

I prefer the solution in #297 as well

**Comment by shawdon** [comment]
@whilei ok, we are glad to contribute a little

**Comment by whilei** [comment]
Closing via merge of #297
