### ISSUE TITLE
Error every 12 hours

### ISSUE THREAD

**Issue by slavserver** [ethereumproject/go-ethereum#30]
#### System information

Geth version: `geth version`1.4.10
OS & Version: Windows/
Commit hash : (if `develop`)
#### Backtrace

```
[backtrace]
```

Error every 12 hours . System eror

**Comment by mikeyb** [comment]
Can you elaborate a little more @slavserver?

**Comment by whatisgravity** [comment]
Can you provide the error message? It is practically impossible to diagnose the issue without a copy of the error message, thanks.

**Comment by mikeyb** [comment]
@slavserver closing this issue in 24 hours if no response is heard.  Let us know if you are still having issues along with details of the issue you are having.
