### ISSUE TITLE
p2p: respTimeout is too small

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/go-ethereum#311]
`respTimeout` controls when for the DPT discovery protocol, the response becomes invalid after the request has sent.

Any idea why currently DPT's `respTimeout` (https://github.com/ethereumproject/go-ethereum/blob/ef25ae0d791d14eacff2c759862c84c7927b9d05/p2p/discover/udp.go#L85) is only 500ms? This basically means that any peer needs to respond `pong` within 500ms for a `ping`. `go-ethereum` is not a real-time system, and I personally think this might just be too restrictive.

**Comment by whilei** [comment]
I don't know the reason why it is set to 500ms, and it does seem short to me as well; what would you suggest?

**Comment by sorpaas** [comment]
I don't have a number in mind, either. There are few things that I think we might want to consider first:

- Longer time means heavier memory and CPU usage of go-ethereum -- it needs to keep track of "pending" replies for a longer time, and the check for timeouts will also happen more often.
- `respTimeout` do affect P2P network connectivity, however. Sending node discovery packet `FindNeighbours` requires first sending `ping` or responding `pong` in time (for go-ethereum case), which depends on `respTimeout`. I do see nodes trying to connect to my client but got `unsolicited reply` error. This means some nodes, whose user might just be in a place where UDP packets are slow, would have a hard time finding other peers.
- Parity does not have the above restrictions, however.

**Comment by whilei** [comment]
I wonder if we might be able to use the quality-of-service metrics, which measure network latency, to dynamically scale the `respTimeout`; where if `qosTuning` for a client was low (fast) then `respTimeout` would be kept low, but if service was slow (high latency), then `respTimeout` would get pushed higher.  Possibly even also taking into account allowed `cache` value as an indicator of possibly-user-defined memory capacity.  Just an idea.

**Comment by sorpaas** [comment]
The original problem has been resolved in the [devp2p-rs](https://github.com/sorpaas/devp2p-rs) library, but I'll leave this open because this behavior indeed might cause problem for clients located in disadvantaged network areas.

**Comment by whilei** [comment]
@sorpaas Can you please elaborate on that? Or just point me where to look in that lib?

**Comment by sorpaas** [comment]
@whilei it was just a bug in devp2p-rs that caused more-than-500ms delay.

**Comment by whilei** [comment]
Just noting -- this might be related to discovery and import issues on Morden since there are fewer and less powerful nodes
