### ISSUE TITLE
Basic peer discovery log

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#317]
Put to a file log.

Example:
```
2001-07-04T12:08:56.225-0700 PEER PING 123.45.67.89 30303 7909d51011d8a153 252
2001-07-04T12:08:59.634-0700 PEER PONG 123.45.67.89 30303 7909d51011d8a153 151
2001-07-04T12:09:01.020-0700 PEER PONG 231.45.67.89 30303 30a1fd71f28aa6f6 154
2001-07-04T12:09:01.020-0700 PEER FIND_NODE 123.45.67.89 30303 7909d51011d8a153 454
2001-07-04T12:09:04.162-0700 PEER NEIGHBORS 123.45.67.89 30303 7909d51011d8a153 1819 7
```

**Comment by whilei** [comment]
Is the primary goal here to 
1. provide more clear "PEER DISCOVERY" logging specifically or, 
2. more generally, to enable module-per-file logging, _eg._ 

```
/log-dir/my-computer.2001-07-04T12:08:56.225-0700/<p2p.log, eth.log, core.log>
```

1. Requires straightforward modifications and additions to existing `glog` logging for `p2p/discovery` behavior
2. Requires more complex modifications to `logger` module, piggybacking `--log-dir` to enable rotating/writing logs to separate files based on their traced file path (eg ` p2p/server.go:427]`), and would likely want to introduce a new boolean flag modifying `--log-dir` to toggle this behavior

IMHO, option 2 may be more trouble than it's worth, considering similar functionality can be achieved with the use of `--log-dir` (to create timestamped and symlinked per-session archivable log files) and something like `(tail|cat) log-dir/geth.INFO | grep p2p`

**Comment by splix** [comment]
Just one file, with basic name (`/var/log/geth-classic.log` by default). Type of log line is specified by 2nd column (`PEER` in the example above) 

See https://github.com/natefinch/lumberjack also

**Comment by whilei** [comment]
Flag `--log-dir=/var/log/geth-classic` accomplishes some similar features to this already, and can be used in conjunction with `--verbosity=4 --vmodule="p2p=6,core=5" flags.

```
~/Desktop/geth_trials/log-files/logs  ⟠ l
total 19M
lrwxr-xr-x 1 ia staff   41 Jul 26 11:14 geth.INFO -> geth.mh.ia.log.INFO.20170726-111412.36894
-rw-r--r-- 1 ia staff 2.1M Jul 26 11:08 geth.mh.ia.log.INFO.20170726-110738.35434
-rw-r--r-- 1 ia staff 2.1M Jul 26 11:08 geth.mh.ia.log.INFO.20170726-110830.35780
-rw-r--r-- 1 ia staff 8.3M Jul 26 11:10 geth.mh.ia.log.INFO.20170726-110834.35812
-rw-r--r-- 1 ia staff 6.3M Jul 26 11:21 geth.mh.ia.log.INFO.20170726-111412.36894
~/Desktop/geth_trials/log-files/logs  ⟠ tail geth.INFO
I0726 11:21:12.622067 core/database_util.go:300] stored block body [19267293…]
I0726 11:21:12.622106 core/database_util.go:285] stored header #15645 [19267293…]
I0726 11:21:12.622120 core/blockchain.go:929] [1501086072622111427] inserted block #15645 (0 TXs 0 G 0 UNCs) (19267293...). Took 471.621µs
I0726 11:21:12.622319 core/state/state_object.go:231] f927a40c8b7f6e07c5af7fa2155b4864a4112b13: #0 9652812500000000000000 (+ 5000000000000000000)
I0726 11:21:12.622512 core/database_util.go:350] stored block receipts [00e9b1a4…]
I0726 11:21:12.622607 core/database_util.go:315] stored block total difficulty [00e9b1a4…]: 6572674897902348
I0726 11:21:12.622631 core/database_util.go:300] stored block body [00e9b1a4…]
I0726 11:21:12.622671 core/database_util.go:285] stored header #15646 [00e9b1a4…]
I0726 11:21:12.622685 core/blockchain.go:929] [1501086072622675633] inserted block #15646 (0 TXs 0 G 0 UNCs) (00e9b1a4...). Took 495.678µs
I0726 11:21:12.622758 core/blockchain.go:960] imported 20 block(s) (0 queued 0 ignored) including 0 txs in 66.115927ms. #15646 [d69480ec / 00e9b1a4]
```

... though it does not provide the automated rotation and size-limit features of lumberjack; my inclination would be to leave those functionalities (log backups, size-limits, and rotation schedules) to a user's own discretion and implementation (cron+script,  separate from the geth client -- since otherwise it would involve hardcoded configuration or ~3 more flags (`--log-max-age`, `--log-max-size`, `--log-max-backups`). Do you agree?

As for 
> Type of log line is specified by 2nd column (PEER in the example above)

is this a pattern you imagine implementing for just PEER discovery behavior, or more generally, _eg_. `BLOCKCHAIN`, `DATABASE`, ... ?

**Comment by splix** [comment]
It's hard to produce KPI and log analysis with existing format of the log, we need some formalization and parseable log structures.

Agree that log rotation is better to leave for a user. 

This particular issue is for peer discovery, so let's use `PEER` there. For other stuff we'll introduce other markers, but that's out of the scope of this issue.
