### ISSUE TITLE
Block reverts my transaction, maybe p2p problem

### ISSUE THREAD

**Issue by iFA88** [ethereumproject/go-ethereum#337]
Greetings!

Have serious problem with sending transactions.
I use `"Geth/v3.5.0+86-db60074/linux/go1.8"` node for Ethereum Classic network was downloaded from https://github.com/ethereumproject/go-ethereum/releases/download/v3.5.86/geth-classic-linux-v3.5.0.86-db60074.tar.gz .

The first step that i have send a transaction. Few blocks later the transaction is processed into a block like the first image below. Few block later the block hash has been changed and my transaction is vanished ( second image below). This is normal if the block has been reverted.
The problem is, that my transaction are stuck in this loop. Processed.. vanished.. processed .. etc..etc
It will be never processed a block who really stay in.
Currently have send this TX soon 30 min, and in this time has several times processed and vanished.

I have tried for hoping solution this:
 - Many time restarted the node
 - Deleted the node DB ( datadir/nodes/* )
 - Deleted the nodeKey ( datadir/nodekey )

I'm really curious what can be the problem.

This transaction should call a contract. If I send a normal ETC transaction without any input data, then works everything perfect.

![img1](https://user-images.githubusercontent.com/18205395/29522662-3b04d8ac-868a-11e7-85a7-258bd370d5c8.png)
![img2](https://user-images.githubusercontent.com/18205395/29522663-3b053248-868a-11e7-8a98-0ceb62953f74.png)

**Comment by iFA88** [comment]
I have started an another client in my desktop PC:
```
I0821 17:04:34.427816 downloader.go:298] peer "cead4e4e11dd7bb5" sync complete
I0821 17:04:35.147651 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 6 txs in 6.0179ms. #4321716 [318ab0f6 / 318ab0f6]
I0821 17:04:54.813224 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.9134ms. #4321717 [eb2927bd / eb2927bd]
I0821 17:05:03.153778 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.8503ms. #4321718 [e7736202 / e7736202]
I0821 17:05:08.593916 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 2.5092ms. #4321719 [7e7004c0 / 7e7004c0]
I0821 17:05:36.867068 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 2.9353ms. #4321720 [e4819780 / e4819780]
I0821 17:05:44.633801 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 3.9136ms. #4321721 [9ab0acaa / 9ab0acaa]
I0821 17:05:52.650233 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 17 txs in 12.7188ms. #4321722 [0bff1973 / 0bff1973]
I0821 17:06:04.326868 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 1.9555ms. #4321723 [94f21b97 / 94f21b97]
I0821 17:06:33.442926 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 9 txs in 10.7627ms. #4321724 [fc397353 / fc397353]
I0821 17:06:54.400600 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 5.5194ms. #4321725 [86a7e31a / 86a7e31a]
I0821 17:07:25.007327 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 3.9119ms. #4321726 [d052e1fa / d052e1fa]
I0821 17:07:42.994979 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 4.5121ms. #4321727 [2feedff3 / 2feedff3]
I0821 17:08:01.359083 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 19 txs in 13.698ms. #4321728 [4e979da4 / 4e979da4]
```

On the linux client:
```
I0821 17:04:15.254822 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 8 txs in 54.856021ms. #4321716 [56e3f43e / 56e3f43e]
I0821 17:04:33.785471 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 6 txs in 25.466912ms. #4321716 [318ab0f6 / 318ab0f6]
I0821 17:04:52.667288 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 21.51304ms. #4321717 [eb2927bd / eb2927bd]
I0821 17:05:01.145905 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 21.955351ms. #4321718 [e7736202 / e7736202]
I0821 17:05:06.539074 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.466398ms. #4321719 [7e7004c0 / 7e7004c0]
I0821 17:05:12.639638 eth/handler.go:290] Peer 435bf88c01af81de [eth/63]: error requesting headers by number
I0821 17:05:25.992730 eth/handler.go:290] Peer 95bac945692a9144 [eth/63]: error requesting headers by number
I0821 17:05:35.210993 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 5.432874ms. #4321720 [e4819780 / e4819780]
I0821 17:05:42.581759 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.787163ms. #4321721 [9ab0acaa / 9ab0acaa]
I0821 17:05:50.980466 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 17 txs in 40.940778ms. #4321722 [0bff1973 / 0bff1973]
I0821 17:06:02.605283 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 8.05925ms. #4321723 [94f21b97 / 94f21b97]
I0821 17:06:02.891222 eth/handler.go:290] Peer 57a8d9362dba2126 [eth/63]: error requesting headers by number
I0821 17:06:03.952408 eth/handler.go:290] Peer 70a4a2b3fd11d791 [eth/63]: error requesting headers by number
I0821 17:06:05.534120 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 11 txs in 43.177532ms. #4321724 [8fb7d6cd / 8fb7d6cd]
I0821 17:06:19.375784 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 10.093693ms. #4321725 [47013d5c / 47013d5c]
I0821 17:06:31.312452 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 9 txs in 17.145614ms. #4321724 [fc397353 / fc397353]
I0821 17:06:41.825125 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 4 txs in 36.926132ms. #4321726 [58529861 / 58529861]
I0821 17:06:52.855262 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 11.871292ms. #4321725 [86a7e31a / 86a7e31a]
I0821 17:07:20.152035 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 17.169644ms. #4321727 [0919a7be / 0919a7be]
I0821 17:07:23.138085 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 7.868012ms. #4321726 [d052e1fa / d052e1fa]
I0821 17:07:42.109431 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 1.325508865s. #4321727 [2feedff3 / 2feedff3]
```

I receive many block what are doubled..

**Comment by whilei** [comment]
It looks to me like you have invalid transaction -- the `gas` is too low compared to the `gasPrice`. 

And in the case of your linux client, that would be normal behavior for "reordering" that happens when "better" blocks are found, causing the chain to reset to last best block, and thus appearing like a re-import (notice, for example, that the hashes are different for "repeated blocks"). 

So if you're trying to submit your transaction via the linux machine, these behaviors would make sense together.

**Comment by iFA88** [comment]
The nonce was too high.. Its really interesting why are then in block processed!

**Comment by iFA88** [comment]
Again with the same situation with TX `0x86224b056bb393699cb68d926767415b3c04264d362f662ffe28ab83a6a2bc6a`
`{"nonce": "0x3", "hash": "0x86224b056bb393699cb68d926767415b3c04264d362f662ffe28ab83a6a2bc6a", "blockHash": "0x323e11017fa62ed5aa976b262be1bc5d9e3d8f2b235da8787967149bdef178e0", "gas": "0x5208", "value": "0x1bc16d674ec80000", "blockNumber": "0x41f5e6", "to": "0x610e3b4e804b367c182c5fc4d65d09c089723389", "input": "0x", "from": "0x8628c28c94e1e0d9eac4ccce170e517a18278266", "replayProtected": false, "transactionIndex": "0x1", "gasPrice": "0x4a817c800"}`
```
I0821 21:14:31.011314 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 3.9133ms. #4322790 [323e1101 / 323e1101]
I0821 21:14:36.033276 core/blockchain.go:960] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 3.5097ms. #4322790 [febd4eee / febd4eee]
```

My transaction is still not in block after 41 blocks..

**Comment by iFA88** [comment]
In block on `4322951` height after 161 block!

**Comment by whilei** [comment]
> The nonce was too high.. Its really interesting why are then in block processed!

They're "processed" because transactions can arrive at a client "out of order," and the client needs to be able to build blocks without knowing a complete set of available transactions.

Your gas seems to me still to be an issue:

```bash
⟠ fromhex 0x5208
21000
⟠ fromhex 0x4a817c800
20000000000
```

**Comment by iFA88** [comment]
> Your gas seems to me still to be an issue:

`eth.gasPrice` was `20000000000`.
For normal address to normal address transaction is `21000` gas limit enough.

**Comment by whilei** [comment]
You're right about the gas -- my mistake. 

Can you give more information about your situation -- are you mining? How are you submitting your transactions? Are you allowing geth to manage your `nonce` value or specifying it manually?

**Comment by iFA88** [comment]
Ofc.
No I'm not mining.
I have signed the transaction with my own script in browser. The Nonce I get it from the Node with `eth.getTransactionCount("address", 'pending')`. When I send the transaction I do that with `eth.sendRawTransaction` to the same Node.

**Comment by whilei** [comment]
Closing -- it seems like you found a solution via Slack 👍

**Comment by iFA88** [comment]
Yes, thanks!
