### ISSUE TITLE
Incorrect estimateGas

### ISSUE THREAD

**Issue by iFA88** [ethereumproject/go-ethereum#339]
Greetings.

I have issue with the geth ( `Geth/v3.5.0+86-db60074e/windows/go1.8` and `Geth/v3.5.0+86-db60074/linux/go1.8` ) on `estimateGas` :
```
> eth.estimateGas({from:"0x9f3f11eae0c9efb4d8e8dec3c8f2182461762cbc", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0"})
50000000
> eth.sendTransaction({from:"0x9f3f11eae0c9efb4d8e8dec3c8f2182461762cbc", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0", gas:350000})
0x811bef485180713e3ab87853708fcf385a114f0715ff24f713e7f6345d2fe0e7
```
http://gastracker.io/tx/0x811bef485180713e3ab87853708fcf385a114f0715ff24f713e7f6345d2fe0e7

On parity works as excepted:
http://gastracker.io/tx/0xdeccc6af3588a4c1d7b66560760f050b693817c664cf97113b5fa8a47ecfeca1

**Comment by whilei** [comment]
I am unable to reproduce 😕 

Geth:
```
Welcome to the Geth JavaScript console!

instance: Geth/source/darwin/go1.8
coinbase: 0xed0ab9153ab4f412b1a6c061b04d50ebaea7c10f
at block: 1686293 (Sat, 11 Jun 2016 14:41:16 CDT)
 datadir: /Users/ia/Library/EthereumClassic/mainnet
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> eth.estimateGas({from:"0x9f3f11eae0c9efb4d8e8dec3c8f2182461762cbc", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0"})
23000
```

Parity:
```
Welcome to the Geth JavaScript console!

instance: Parity//v1.6.7-beta-e128418-20170518/x86_64-macos/rustc1.17.0
coinbase: 0x0000000000000000000000000000000000000000
at block: 0 (Wed, 31 Dec 1969 18:00:00 CST)
 modules: eth:1.0 net:1.0 parity:1.0 parity_accounts:1.0 rpc:1.0 traces:1.0 web3:1.0

> eth.estimateGas({from:"0x9f3f11eae0c9efb4d8e8dec3c8f2182461762cbc", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0"})
23000
```

Also note that an estimation of `50000000` is reported to occur as a result of a call throwing an exception.

**Comment by iFA88** [comment]
Yes i know that the transaction is throwed on 50M estimated gas.
I still got that..
```javascript
Welcome to the Geth JavaScript console!

instance: Geth/v3.5.0+86-db60074/linux/go1.8
coinbase: 0xed95cc32e856048f9ace78caec8682af94c9c022
at block: 4382998 (Thu, 31 Aug 2017 19:36:01 CEST)
 datadir: /mnt/etc/mainnet
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> {182461762cbc", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0"})
50000000
```
The window client is on my home PC. The linux client is on my VPS.

**Comment by iFA88** [comment]
Your clients seems not be synced!

**Comment by whilei** [comment]
that shouldn't make a difference unless your contract cost depends on changes implemented in the gas reprice upgrades; to test this I ran the estimation on a custom chain to verify against the new gas prices and got the same result.

I also ran it on my linux machine with the same result:
```
Welcome to the Geth JavaScript console!

instance: Geth/v3.5.0+86-db60074/linux/go1.8
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

> {c", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0"})
23000
> exit
```

**Comment by sorpaas** [comment]
I cannot reproduce the problem either. But I found that in the contract of `0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A`, it contains opcodes like `0x45` (GASLIMIT). If Geth/Parity uses different block parameters when doing call/estimategas, that may cause the problem.

Cannot say for sure, however. 😿

**Comment by sorpaas** [comment]
@iFA88, if you know the source code of that contract, that may help a little bit.

**Comment by iFA88** [comment]
Sure: https://github.com/CORIONplatform/solidity/tree/rc
`token.sol` `transfer` call and I transfer the tokens to the `exchangeLight.sol`
On parity I got great `estimategas`, only in the geth is the problem.
I sync now new on my PC.

**Comment by sorpaas** [comment]
I actually think this might be some problems with the contract. Running a random address to call `0xc1..6A` would give me error. This is using Parity v1.6.8.

```
curl -XPOST -d '{"jsonrpc":"2.0","method":"eth_estimateGas","params":[{"from":"0x405816b92254946881c744dc6ed6eb03db749185", "to":"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", "data":"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000002dc6c0"}],"id":1}' -H 'Content-Type: application/json' 127.0.0.1:8545
{"jsonrpc":"2.0","error":{"code":-32015,"message":"Transaction execution error.","data":"Internal(\"Requires higher than upper limit of 1000000000000\")"},"id":1}
```

**Comment by iFA88** [comment]
If you run from an address who arent tokens it will be throwd. If your ETC balance is greater than 0.2 ether it will be also throwd.

**Comment by sorpaas** [comment]
@iFA88 then can you try to full-sync your geth and call the contract again?

Above showed that your geth it's currently `at block: 4382998 (Thu, 31 Aug 2017 19:36:01 CEST)`. But there's only a deposit happening at 4383060 for the from address you're using. So that might be the reason that it throws the error.

**Comment by iFA88** [comment]
Yes, I still resync the whole chain. I will report tomorrow!

**Comment by iFA88** [comment]
The sync has been finished.
The geth still have some bug.
![same](https://user-images.githubusercontent.com/18205395/29961251-4809648c-8eff-11e7-9954-59968937615a.png)

**Comment by iFA88** [comment]
Whats next? How can I debug what happens during the `estimateGas`?

**Comment by iFA88** [comment]
The issue is still exist, and now i have an another call what on parity goes, but on this client not!
I use now `Geth/v4.0.0/linux/go1.8` ..

**Comment by whilei** [comment]
Can you share your contract(s) code (or something very like it) so we can try to reproduce?

**Comment by iFA88** [comment]
Yes ofc, the contract source code is full available here: https://github.com/CORIONplatform/solidity
The contracts addresses which are deployed on the blockchain (the most important for this case):
 - ModuleHandler: 0x5865F6e97c795A8f5904673aAD8d713A8aE10914
 - Provider: 0x51855b40c75dC3eD7daC9481cfE33DEBd0cE5b88
 - ProviderDB: 0xD4254EB72d60091CAc10AA5ad621FB0d93d8FB43
 - ProviderCheckrewardLib: 0x1757E0ee084330D4ED6e21B674ECafCF3537e9fa

The situation was:
 - 0x781b29c7313e39157a428d3330b68464d1915e39 address has created providerUID 1 ( `provider.openProvidert()`
 - The same address want to close the provider `provider.closeProvider()` but the estimateGas has returned 50M gas (throwed) both on windows and linux client. With windows parity works everything as excepted.

**Comment by iFA88** [comment]
I have replaced the contracts now..

**Comment by whilei** [comment]
There's quite a few contracts and address there... I'm not sure where you're seeing the problem coming from. Can you give a few specific steps so we can try a reproducible example?

**Comment by iFA88** [comment]
Not anymore, as I said i have replaced the contracts, they are not callable anymore.
This issue is still available:
```
eth.estimateGas({from:"0x646421Fe34c60a05bdf69A9F3d27b65B0ECBefAA", to:"0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A", data:"0xa9059cbb000000000000000000000000bee690c64368d5be65783246a0057cd3bab7ad7200000000000000000000000000000000000000000000000000000000001e8480"})
```
I got throw on linux geth 4.0.0 and on windows geth 4.0.0 too.
On parity works fine.

Is there any opportunity to debug this? I have seen that `debug.traceTransaction` is added, but is completely useless.

**Comment by sudachen** [comment]
As I see contract 0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6 contains two instructions 0xfd (REVERT) and 0хfe (ABORT) which currently is unsupported by Ethereum Classic VM and can be used only in Ethereum EF after metropolis fork. Since execution of invalid contract will consume all available gas, the geth estimates gas accuratley. So there is no bug.

I guess classic will support those instructions after switching to sputnikVM.

**Comment by iFA88** [comment]
The contacts have worked on the etc blockchain. The bug is inside in the geth evm processor.

**Comment by sudachen** [comment]
http://gastracker.io/contract/0xc1fd237d844c0a1a4f18a5d6bd44f57df48e5e6a ?
I see no transations here at all. However I can disaasemble and also execute with tracing and I see unsupported instractions here. I have wrote before where it is. You can disassemble contract by yourself and see to offset 6282, for example. However there are many places with unsupported opcodes.

**Comment by sudachen** [comment]
By the way

https://github.com/CORIONplatform/solidity/blob/master/exchangeLight.sol#L49

**Comment by iFA88** [comment]
Alright,
Can you explain this:
Geth/v4.0.0/linux/go1.8:
```javascript
> eth.estimateGas({from:'0x646421Fe34c60a05bdf69A9F3d27b65B0ECBefAA', to:'0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A', data:"0xa9059cbb0000000000000000000000001e77d720daa7d852b894e0138636e39454abd91c0000000000000000000000000000000000000000000000000000000000200000"}
50000000
```
Parity/v1.7.6-stable-1953533-20171013/x86_64-linux-gnu/rustc1.20.0
```javascript
.eth.estimateGas({'from':'0x646421Fe34c60a05bdf69A9F3d27b65B0ECBefAA', 'to':'0xc1FD237D844C0A1A4F18A5d6bd44F57dF48E5e6A', 'data':"0xa9059cbb0000000000000000000000001e77d720daa7d852b894e0138636e39454abd91c0000000000000000000000000000000000000000000000000000000000200000"})
567035
```
