### ISSUE TITLE
Release 4.1 - Server management

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#344]
**Goal of the milestone**: improve server management
**Release timeframe**: end of September

## Bugs

- [x] #300 

## New features

- [x] #319 
- [x] logging tasks #318

## Refactoring

- [x] chain config in json only #342 

## Other

- [ ] setup a demo cluster with monitoring of the network, a public accessible Logstash/Kibana (rel #318)

**Comment by whilei** [comment]
Closing in favor of using milestone system, see https://github.com/ethereumproject/go-ethereum/milestone/12
