### ISSUE TITLE
fromshanghaiwithlove (geth crashes)

### ISSUE THREAD

**Issue by mikeyb** [ethereumproject/go-ethereum#35]
We have pulled in fixes from the original maintainers and are currently testing.

If any golang enthusiasts want to take a whack at comparing un-synced changes between this repo and [ETHF](https://github.com/ethereum/go-ethereum) reach out.

**Comment by Hou5e** [comment]
I was running the last released ETC geth v1.4.10 binary. I just built from source on Ubuntu for the first time, and I'm getting this:

> I0918 22:24:31.757834 eth/downloader/downloader.go:301] Synchronisation failed: block header download canceled (requested)
I0918 22:24:32.282423 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)

Do I need to resync from scratch or something?  Thanks!

**Comment by whatisgravity** [comment]
I'm back in this, I will take a look later today.
