### ISSUE TITLE
geth 1.6.7 rpc(http) can not get current block number via API: eth_blockNumber

### ISSUE THREAD

**Issue by yangliw3** [ethereumproject/go-ethereum#350]
[root@tim wallet]# curl -X POST --data '{"jsonrpc":"2.0","method":"net_peerCount","params":[],"id":88}' 127.0.0.1:8545
{"jsonrpc":"2.0","id":88,"result":"0x4"}
[root@tim wallet]# 
[root@tim wallet]# curl -X POST --data '{"jsonrpc":"2.0","method":"eth_syncing","params":[],"id":88}' 127.0.0.1:8545
{"jsonrpc":"2.0","id":88,"result":{"currentBlock":"0x4d7d3","highestBlock":"0x41713e","knownStates":"0x29cf2","pulledStates":"0x27214","startingBlock":"0x37f8d"}}
[root@tim wallet]# 
[root@tim wallet]# curl -X POST --data '{"jsonrpc":"2.0","method":"eth_blockNumber","params":[],"id":88}' 127.0.0.1:8545
{"jsonrpc":"2.0","id":88,"result":"0x0"}

**Comment by yangliw3** [comment]
i use this args to running geth:
/data/wallet/geth/geth --datadir /data/wallet/geth-data --rpc --rpcapi eth,web3,personal,net --rpcaddr 0.0.0.0 --rpcport 8545

**Comment by splix** [comment]
strange, It usually returns `0x0` only on a first fast sync

**Comment by splix** [comment]
btw, to use Ethereum ETC chain, you have to use Geth at lest version 3.x.x currently, and latest one is 4.0.0

**Comment by yangliw3** [comment]
@spix
thanks 
i want to run eth , not etc
i will not update stat untill sync all the block, maybe tomorrow

**Comment by whilei** [comment]
@yangliw3 I believe you're looking for here, then https://github.com/ethereum/go-ethereum
