### ISSUE TITLE
ECIP-1017 monetary policy: possible misinterpretation

### ISSUE THREAD

**Issue by rtkaczyk** [ethereumproject/go-ethereum#352]
As stated in the [ECIP-1017](https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md):

> An extra reward to the winning miner for including uncles as part of the block, in the form of an extra 1/32 (0.125ETC) per uncle included, up to a maximum of two (2) uncles

Usage of the singular form and the placement of commas suggests that it's a single reward for all of the uncles included. Therefore any rounding down of the possibly non-integer result should be done for the whole reward.

[This code](https://github.com/ethereumproject/go-ethereum/blob/cc45e5f7ac43b2454570057c6b595224214498cf/core/state_processor.go#L221-L223) however, calculates a reward per uncle individually and sums them up (in practice - multiplies). This may lead to accumulation of rounding errors.

The code is perfectly fine if we interpret the above definition to mean that these are separate rewards per each uncle, which have already been subjected to rounding down. However, we at Mantis team, interpreted it as explained above, and the difference may lead a network split in further eras.

All that being said, the [ECIP-1017](https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md) definitely requires some clarification.

**Comment by whilei** [comment]
Agreed that this wording could use clarification. My interpretation had emphasized the `in the form of ... per uncle` clause, which moves `reward` to a more abstract idea, _eg_ 

> "For earning first place, Joseph received a reward of a blue ribbon and a knitted hat."

**Comment by whilei** [comment]
Resolved with the merge of https://github.com/ethereumproject/ECIPs/pull/83
