### ISSUE TITLE
addpeer command

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#353]
A command to add a new peer to an existing running geth instance from command line (instead of js console).

For example:
```
geth peer add enode://fb28713820e718066a2f5df6250ae9d07cff22f672dbf26be6c75d088f821a9ad230138ba492c533a80407d054b1436ef18e951bb65e6901553516c8dffe8ff0@104.155.176.151:30304

geth --datadir /gethdata --chain morden enode://fb28713820e718066a2f5df6250ae9d07cff22f672dbf26be6c75d088f821a9ad230138ba492c533a80407d054b1436ef18e951bb65e6901553516c8dffe8ff0@104.155.176.151:30304
```

**Comment by whilei** [comment]
What is reason for adding `addpeer` instead of just using js console or rpc? 

Maybe it's worth considering implementing a subcommand to expose _all_ enabled ipc api methods? 
```
geth api admin addPeer enode://fb28713820e718066a2f5df6250ae9d07cff22f672dbf26be6c75d088f821a9ad230138ba492c533a80407d054b1436ef18e951bb65e6901553516c8dffe8ff0@104.155.176.151:30304

geth --datadir /gethdata --chain morden api admin addPeer enode://fb28713820e718066a2f5df6250ae9d07cff22f672dbf26be6c75d088f821a9ad230138ba492c533a80407d054b1436ef18e951bb65e6901553516c8dffe8ff0@104.155.176.151:30304
```

along with other methods, like

```
geth api net peerCount
geth api eth getBalance "0x728089402ae351323ede8f3de4042cc58afac109" "latest"
geth api txpool inspect
geth api debug metrics true
```

where required method arguments (like `"0x728089402ae351323ede8f3de4042cc58afac109" "latest"`) would need to be either valid JSON or space-separated set of args that could then be parsed to JSON and sent to ipc rpc

**Comment by splix** [comment]
js console is cool when you want to do it manually, but looks weird when you try to do it from a script:
```
touch peer.js
echo "admin.addPeer('enode://$PEER_ID@$PEER_IP:30303');" >> peer.js
geth --exec "loadScript('peer.js')" attach
rm peer.js
```

RPC methods, such as get balance, works well through Emerald CLI, just admin operations are unsupported there

**Comment by whilei** [comment]
> just admin operations are unsupported there

you mean unsupported in Emerald CLI? 

geth has `--rpc-api="admin"`
```
curl -X POST --data '{"jsonrpc":"2.0","method":"admin_addPeer","params":["enode://4f3a63cd2c6c863293c9d5fb88877f67f15e5c90159670aac18f4bcb510e9ee50b0cfdfcf0741b6c177e34d85fbba9e4be390ad9b9bae5a747519a739e7be67c@172.20.10.8:30303"],"id":1}'
```

And/or what do you think about the subcommand `api` idea to make it a more generic tool?

**Comment by splix** [comment]
Yeah, admin operations are unsupported by Emerald CLI.

I've missed that it works with `admin_` RPC prefix. Still ugly from command line, but better than console. Ok, we'll need to think what commands we want to see then

**Comment by whilei** [comment]
I was thinking we could just expose all enabled api methods using the IPC-RPC interface, so 
```
geth api admin addPeer enode://fb28713820e718066a2f5df6250ae9d07cff22f672dbf26be6c75d088f821a9ad230138ba492c533a80407d054b1436ef18e951bb65e6901553516c8dffe8ff0@104.155.176.151:30304
```
becomes an rpc client request
```go
// pseudo code
	req := map[string]interface{}{
		"id":      new(int64),
		"method":  ctx.Args()[0] + "_" + ctx.Args()[1], // "admin_addPeer"
		"jsonrpc": "2.0",
		"params":  []interface{}{
          ctx.Args()[2:] // "enode://fb28713820e718066a2f5df6250ae9d07cff22f672dbf26be6c75d088f821a9ad230138ba492c533a80407d054b1436ef18e951bb65e6901553516c8dffe8ff0@104.155.176.151:30304"
        },
	}
```
and then return normal JSON `response` which will be already in JSON format

**Comment by tzdybal** [comment]
I agree with @whilei that exposing all commands from all APIs can be done in a generic way, so it's better to do than explicitly coding single command / limited set of commands.

Should the resulting JSON be 'pretty printed' to be more human-friendly?

**Comment by whilei** [comment]
I don't see any reason not to pretty print :lipstick: if it's easy and doesn't require any extra dependencies. Not a high priority though.
