### ISSUE TITLE
JSON-RPC response handling

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#355]
Currently, it's not possible to properly handle errors from JSON-RPC responses.

There are two separate structs: `rpc.JSONSuccessResponse` and `rpc.JSONErrResponse`.
During `rpc.Client.Recv` JSON data is extracted from stream and response object is unmarshalled.
User of `Client` need to know whether response is Success or Error before receiving response, to be able to properly unmarshal it. 

To fix this, the two response types should be replaced with one, containing both `Result` and `Error` field, both annotated `omitempty`.

**Comment by whilei** [comment]
Resolved with #354
