### ISSUE TITLE
--exec option isn't working!

### ISSUE THREAD

**Issue by muhammednagy** [ethereumproject/go-ethereum#359]
Hello
i'm trying to use --exec option but it is not seeing the parameters
my test
`geth attach --exec "console.log('not working')"`
i get this error

> Incorrect Usage.

attach [arguments...]

The Geth console is an interactive shell for the JavaScript runtime environment
which exposes a node admin interface as well as the Ðapp JavaScript API.
See https://github.com/ethereum/go-ethereum/wiki/Javascipt-Console.
This command allows to open a console on a running geth node.

flag provided but not defined: -exec

Can you please help?
Thanks

**Comment by splix** [comment]
works as `geth --exec "console.log('not working')" attach`, which is not so intuitive

**Comment by muhammednagy** [comment]
ahhh okay 
that's weird 
i used to execute my command with ethereum geth and it worked

**Comment by splix** [comment]
PR #360 will allow to work both ways
