### ISSUE TITLE
geth respawns in the background even after computer restart

### ISSUE THREAD

**Issue by okwme** [ethereumproject/go-ethereum#363]
After `control z` quitting geth and running `killall -9 geth` multiple times i saw my bandwidth going crazy and geth listed as the culprit. I ran `killall -9 geth` twice to shut it down only to have it pop up again a couple hours later. After restarting my machine geth popped up in my list of bandwidth processes again. How did geth become a daemon and how do i stop it from spawning? 

I'm running v 1.7.1-stable on mac 10.12.5

**Comment by okwme** [comment]
solution [here](https://github.com/ethereum/go-ethereum/issues/1348)

**Comment by splix** [comment]
v1.7.1 is Geth ETH, but we have Geth ETC here (which have version 4.0.0)

You can find ETH repo at https://github.com/ethereum/go-ethereum
