### ISSUE TITLE
is there any document show how to send token via cmd, thanks

### ISSUE THREAD

**Issue by yangliw3** [ethereumproject/go-ethereum#367]
hello 
i want to send token via command line interface
but i can not find the docment , i known ABI, but i do not known how to use it ,and how to brodcast the transaction

regards

**Comment by whilei** [comment]
Check out the wiki page [Sending Ether Tutorial](https://github.com/ethereumproject/go-ethereum/wiki/Sending-Ether-Tutorial)

**Comment by whilei** [comment]
@yangliw3 hope that helps! 😄 💸
