### ISSUE TITLE
5 orphan with geth 4.0.0

### ISSUE THREAD

**Issue by alptolga** [ethereumproject/go-ethereum#378]
I have a small farm and I am mining etc with open ethereum pool software. I found 7 blocks. 2 of them are uncle and 5 of them are orphan. I never see such a problem before. I used geth and open ethereum pool many times. This is an incredible orphan rate.

**Comment by whilei** [comment]
Without more information this is impossible to debug; please include logs.

Perhaps try setting `max-peer-count` to a higher number?
