### ISSUE TITLE
New command: reset

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#381]
Add new command `reset` to `geth`. It should completely reset blockchain database. This command could be used as a clean, documented, last resort way of dealing with misbehaving node.

**Comment by whilei** [comment]
How will this differ from `geth rollback 0` or js: `debug.setHead(0)`?

**Comment by tzdybal** [comment]
In my opinion `reset` should be drastic. It should be implemented to remove the entire database directory, to give 100% confidence that no data is broken/stalled/orphaned in database.

**Comment by whilei** [comment]
So essentially `rm -rf chaindata/`? I can see value in that 👍  -- it provides a simple (albeit drastic) way for a user to manage geth's data without having to lookup geth's filesystem storage locations and/or additional command line tools, eg `rm`.

And while nuking the chain database isn't pretty, it's a safe and common way of handling certain issues.
