### ISSUE TITLE
New command: recover

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#382]
New command `recover` for `geth`. It should attempt to recover blockchain database to the latest consistent and safe block. 
This should be the first thing to do with misbehaving node.

**Comment by whilei** [comment]
Just to clarify -- this would simply expose the [existing proposed `blockchain.Recover()`](https://github.com/ethereumproject/go-ethereum/pull/277/files#diff-30184e52dfee0fbd0ba21f92638b2ec1) method to a CLI command?

**Comment by tzdybal** [comment]
Exactly.
