### ISSUE TITLE
New command: rollback-fast

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#383]
New command `rollback-fast` for `geth`. It should remove all the full blocks to re-enable fast syncing.
Optional parameter (block number/hash) could be provided to remove the full and fast state newer than given block. Without the parameter, by default, all full blocks should be removed to the point where fast sync ended.

**Comment by whilei** [comment]
What are your thoughts on alternate implementations (one as a command flag, other as own command)

```
$ geth rollback --fast 42
```
vs
```
$ geth rollback-fast 42
```

**Comment by tzdybal** [comment]
I prefer the flag version.

**Comment by whilei** [comment]
me too

**Comment by whilei** [comment]
@tzdybal I'm having second thoughts about this feature, and would like to do a little more consideration before pushing forward. 

My reasoning is that constraining fast sync to the initial sync is a safety precaution, and I want to make sure we think through the implications of offering a feature to undo the security and network health provided by full sync, even if it does seem convenient for cases like "oops-I-ran-geth-wthout-the-fast-flag" and "I'd-like-to-free-up-some-disk-space". 

Do we need to consider our plan for handling pivot points? Would rollback-fast verify and processes the full block transactions before removing them to ensure the new fast head is valid? Any other questions? Thoughts?

**Comment by tzdybal** [comment]
I was thinking mostly about "oops-I-ran-geth-wthout-the-fast-flag" case. And from my perspective, in this case, there is no security difference with introduction of `rollback --fast` feature, because if someone needs to go with fast sync, he will anyways (but will have to wait for fast sync from genesis). 

Now I think, that we shouldn't give the ability to provide block number, to limit the usage to 'undo the full sync'. That way processing is much simpler, and there are less security concerns (we're back in the same point where fast sync finished last time).

**Comment by whilei** [comment]
I agree with you to not give ability for block number. Would we need to roll back to point where fast sync finished last time? Maybe we can just unset the `HeadBlockHash`? Here's a quick and dirty sketch for what that might look like https://github.com/whilei/go-ethereum/commit/c057541bb4e04603fe9871cec046beeb38ced0e0

**Comment by tzdybal** [comment]
Resetting `HeadBlockHash` should be sufficient. But I think that we shouldn't leave some 'dangling' block data in database anyways.
