### ISSUE TITLE
Complete sync after fast sync

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#384]
It would be nice to be able to force full sync of entire blockchain (from genesis block) after finishing fast sync. This should be done "in the background" - in the way that doesn't interfere with normal sync.

This feature would enable user to quickly bootstrap a new server (in fast mode) and than convert it to full/archive node.

**Comment by pyskell** [comment]
:pray:

**Comment by Frankenmine** [comment]
I was thinking this too.
