### ISSUE TITLE
go-ethereum error

### ISSUE THREAD

**Issue by AlexKhare4** [ethereumproject/go-ethereum#385]
**Ubuntu Server 16.04.3, 2 x Intel(R) Xeon(R) CPU X5570 @ 2.93GHz 8 Core, 44GB RAM
Linux 4.4.0-87-generic 
Today received the following errors:**
> I1025 09:02:47.875696 core/blockchain.go:1010] imported 1 block(s) (0 queued 0 ignored) including 2 txs in 5.970732ms. #4712288 [4eac22bc / 4eac22bc]
I1025 09:02:53.837912 core/blockchain.go:1010] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 13.633603ms. #4712289 [46e8aaf9 / 46e8aaf9]
I1025 09:03:03.703264 core/blockchain.go:1010] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.282627ms. #4712290 [ac6f71bf / ac6f71bf]
I1025 09:03:08.130484 core/blockchain.go:1010] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 8.10491ms. #4712291 [5ff81e5f / 5ff81e5f]
I1025 09:03:25.363039 core/blockchain.go:1010] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 4.584709ms. #4712292 [18c6249d / 18c6249d]
I1025 09:03:36.022749 core/blockchain.go:1010] imported 1 block(s) (0 queued 0 ignored) including 5 txs in 8.634106ms. #4712293 [c7adf210 / c7adf210]
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0xa81385]
goroutine 1220813 [running]:
github.com/ethereumproject/go-ethereum/core.(*TxPool).add(0xc4201b0280, 0xc4e967ab40, 0xc4201b02d8, 0x0)
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/core/tx_pool.go:322 +0x525
github.com/ethereumproject/go-ethereum/core.(*TxPool).AddTransactions(0xc4201b0280, 0xc4e10b8100, 0x1, 0x4)
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/core/tx_pool.go:381 +0xcc
github.com/ethereumproject/go-ethereum/eth.(*ProtocolManager).handleMsg(0xc4247cc750, 0xc4b4708d80, 0x0, 0x0)
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:674 +0x1095
github.com/ethereumproject/go-ethereum/eth.(*ProtocolManager).handle(0xc4247cc750, 0xc4b4708d80, 0x0, 0x0)
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:309 +0x85d
github.com/ethereumproject/go-ethereum/eth.NewProtocolManager.func1(0xc446ee86c0, 0x1594380, 0xc4a7ba0150, 0x0, 0x0)
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/eth/handler.go:134 +0x17f
github.com/ethereumproject/go-ethereum/p2p.(*Peer).startProtocols.func1(0xc4a7ba0150, 0xc446ee86c0)
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/p2p/peer.go:303 +0x5d
created by github.com/ethereumproject/go-ethereum/p2p.(*Peer).startProtocols
        /home/pool/go/src/github.com/ethereumproject/go-ethereum/p2p/peer.go:312 +0x238

**Comment by whilei** [comment]
Thanks for reporting this @AlexKhare4. I've just submitted a fix: https://github.com/ethereumproject/go-ethereum/pull/386, and expect it will be merged to master today ✅
