### ISSUE TITLE
Bootstrap Nodes

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#4]
To help us maintain our own network and further limit issues with the ETHF chain we need to run our own bootstrap nodes.

If you can run a dedicated bootstrap node, a node which can stay connected 24/7, typically on servers dedicated to this purpose: please provide the enode, ip address/domain, and port of the node.

**Example**
    enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303"

**Comment by bardacuda** [comment]
Not sure how dedicated this node will be but it is up for now.

enode://7380948a43c765e54fbfedb79dd32d755e97f0548cf0fef232adb49ac4a2525f02c84075dae217663199e45d92f3c1bf7b2c3746417677bdae668e05b8b6c202@174.112.32.157:30303

**Comment by dooglus** [comment]
I had been trying for hours to connect to the ETHC p2p network without success.

Typing the following at the `geth console` prompt fixed the problem instantly:

    admin.addPeer('enode://a979fb575495b8d6db44f750317d0f4622bf4c2aa3365d6af7c284339968eef29b69ad0dce72a4d8db5ebb4968de0e3bec910127f134779fbcb0cb6d3331163c@52.16.188.185:30303')
    admin.addPeer('enode://7380948a43c765e54fbfedb79dd32d755e97f0548cf0fef232adb49ac4a2525f02c84075dae217663199e45d92f3c1bf7b2c3746417677bdae668e05b8b6c202@174.112.32.157:30303')

Thanks guys!

**Comment by whatisgravity** [comment]
That first node was an example from the original code, the thanks goes to bardacuda who is running the second one which is an actual ETC node. 

I hope now that we have more exposure we can get more people to volunteer dedicated nodes and we can move towards becoming an independent network.

**Comment by arvicco** [comment]
I put the request for people to run nodes and post here on a Reddit sticky, so hopefully they'll reply.

**Comment by the-real-eth** [comment]
My node is syncing. I will leave it up permanently.

enode://8729c18654dcddf2e277be8ba7c4058f49a131059e6d95e776f9d8575da0af9be1698dd2c02a228dc5db3202834d2d8a302f289d8156b9aa2bb90adf7aa49e4c@95.183.51.229:30303

Let me know if you can connect to it.

**Comment by elaineo** [comment]
"enode://6e538e7c1280f0a31ff08b382db5302480f775480b8e68f8febca0ceff81e4b19153c6f8bf60313b93bef2cc34d34e1df41317de0ce613a201d1660a788a03e2@52.206.67.235:30303"

**Comment by JikkuJose** [comment]
How can I add these nodes so that client wakes up after restart with these?

**Comment by vroomDotClub** [comment]
I'm switching my node over to classic 
https;//vroom.club
First i guess i have to resync from scratch no?

**Comment by dooglus** [comment]
@vroomDotClub I'm not sure, but I think --fast will get you onto the longest (ie. wrong) chain, unless you use the https://github.com/ethereumproject/go-ethereum version of geth (which knows to reject the hard fork block).

**Comment by LeChuckDE** [comment]
enode://217ebe27e89bf4fec8ce06509323ff095b1014378deb75ab2e5f6759a4e875                                                                                                             0a3bd8254b8c6833136e4d5e58230d65ee8ab34a5db5abf0640408c4288af3c8a7@188.138.1.237:30303

up and running since one week, fresh node installation for a pool. up 24/7

**Comment by whatisgravity** [comment]
All of these bootstrap nodes have been added to the source so there should not be any remaining issues initializing the node. I will leave this thread open if anyone else would like to volunteer their node. We have 4 currently. 

My goal is at least six. 

Then in the future I will add dedicated test net nodes.

**Comment by whatisgravity** [comment]
enode://b61123cc535d6bac44f9e6ff8637a30a10198f80b5582148dcd84ef8039a4b90e326bb7f6964588a46bcf1ccd8e8bba65db514fc72e3026ff13b20959f45f654@etc.naphex.rocks:30303

**Comment by NelsonGaldeman** [comment]
I have a 27/7 windows dedicated server where I would like to run a full dedicated node. I've installed ETC (non-forked) wallet, what should I do to start the full node? I've never did it.

**Comment by VladimirReshetnikov** [comment]
enode://debe388f704b0a13df4e7e5098b907af763ed1778a7b158363329e36bc6b0ec571ae0d01d4ed3ac5470591124cdbd7b7803defbab91284c66d93caffba55459b@52.178.161.27:30303

**Comment by whatisgravity** [comment]
@NelsonGaldeman You need to attach the the cli after starting geth. 

    geth attach

Then output your node's info with

    admin.nodeInfo.enode

If you want more general information about your node you can just use

    admin.nodeInfo

**Comment by VladimirReshetnikov** [comment]
Another one:
enode://fa20444ef991596ce99b81652ac4e61de1eddc4ff21d3cd42762abd7ed47e7cf044d3c9ccddaf6035d39725e4eb372806787829ccb9a08ec7cb71883cb8c3abd@50.149.116.182:30303

**Comment by vroomDotClub** [comment]
@dooglus  Thanks mate .. i am indeed using the geth from ethereumproject ;)

**Comment by NoMoSnacks** [comment]
enode://4bd6a4df3612c718333eb5ea7f817923a8cdf1bed89cee70d1710b45a0b6b77b2819846440555e451a9b602ad2efa2d2facd4620650249d8468008946887820a@71.178.232.20:30304

**Comment by danwxyz** [comment]
enode://08c7ee6a4f861ff0664a49532bcc86de1363acd608999d1b76609bb9bc278649906f069057630fd9493924a368b5d1dc9b8f8bf13ac26df72512f6d1fabd8c95@45.32.7.81:30303

**Comment by mbush78** [comment]
How 'powerful' do bootstrap nodes need to be?

I wanted to try and get this up and running tonight and it's actually working. The box it's running on now is not all that powerful since I was unsure I'd get it to work here. But, if a bootstrap node doesn't need to be all that strong, this thing is on box is on 24/7 with very little downtime so I'd be willing to help out.

Anyway, if it can be used here's the enode and if not oh well I tried :)

enode://b061e49069525297af19d86c8bf6b5345539a4649275150b11d357ec873097e52c04020605086b5676743d3d485ed0e38b08ae538d3415c02330518fdbfcce14@50.171.54.188:30303

**Comment by artyma** [comment]
Hi there!  I want to contribute my powerful system to the Ethereum Classic network. 

It seems I have an issue. I downloaded Ethereum wallet (I use Win 10 pro), then I run Ethereum Wallet.exe, chose NO to hardfork and then it started "Ethereum node needs to sync , please wait LOOKING FOR PEERS" for 2 days.  Time is synchronized. 

Could anyone help on the issue please?

**Comment by jaichange** [comment]
enode://921cf8e4c345fe8db913c53964f9cadc667644e7f20195a0b7d877bd689a5934e146ff2c2259f1bae6817b6585153a007ceb67d260b720fa3e6fc4350df25c7f@51.255.49.170:30303

synced and running 24/7 on dedicated vps.

**Comment by whatisgravity** [comment]
Thanks to all the new volunteers, they

@artyma You may want to try with the release in this git repository, it will directly connect you to volunteers running bootstrap nodes. Alternatively, you can specify bootstrap nodes, use the:

    geth --help

command and you will find a flag that will let you specify a node. It would be better not to use the GUI version if you wish to be a dedicated node but rather run it on a server.

**Comment by phrac** [comment]
Running with a build from this repo:

enode://d55f15f28317c21c359c8f62b93b7059aa2fcd586c0b0d431f97c4b8f27ee8f58fbe060b72eff95790b7ecd34c2a9b02458a783e61d8ec2aa37cdad6b0fc6d9a@node1.ethc.io:30303

Dynamic DNS but updates on DNS change

**Comment by pyskell** [comment]
Running on parity using the 4 bootstrap nodes present in geth. Static IP.

enode://ffea3b01c000cdd89e1e9229fea3e80e95b646f9b2aa55071fc865e2f19543c9b06045cc2e69453e6b78100a119e66be1b5ad50b36f2ffd27293caa28efdd1b2@162.243.55.45:30303

`parity --pruning=fast --chain=classic --tracing=on --identity=pyskell-node-chillest-node --reserve-nodes=...`

**Comment by igetgames** [comment]
Also Parity always running node with static IP:

enode://ca5ae4eca09ba6787e29cf6d86f7634d07aae6b9e6317a59aff675851c0bf445068173208cf8ef7f5cd783d8e29b85b2fa3fa358124cf0546823149724f9bde1@138.68.1.16:30303

`parity --chain classic --tracing on --identity hv-do-ubuntu-2gb-sfo2-parity-classic-01 ...`

**Comment by whatisgravity** [comment]
Very nice to see a greater client diversity.

**Comment by JeroenMerks** [comment]
@phrac unfortunately I wasn't able to add your node.
All others are working ;-)

**Comment by JikkuJose** [comment]
You can use the following to extract all the node addresses in this page:

`curl -s 'https://github.com/ethereumproject/go-ethereum/issues/4' | grep -oE "enode\:.*\:\d{5}" | tr -d " "`

Note: Tested in Mac only.

**Comment by whatisgravity** [comment]
@JikkuJose Thank you for providing that. If you have more time I encourage you to consider volunteering some time to the project.

**Comment by JikkuJose** [comment]
@whatisgravity I wish to, have some ideas. Will it be possible to have a chat?

**Comment by whatisgravity** [comment]
Very happy to hear you are interested.

I'm in the IRC listed above, I would be interested in listening to your ideas regarding the project. I have been busy it is dependent on my variable availability. Over the next 2 weeks I will be more busy than usual too which adds additional difficulty for scheduling. 

You can also email me and my key is the volunteer repository.

**Comment by JikkuJose** [comment]
Sure thanks, will ping you later today.

**Comment by msornay** [comment]
enode://ee3da491ce6a155eb132708eb0e8d04b0637926ec0ae1b79e63fc97cb9fc3818f49250a0ae0d7f79ed62b66ec677f408c4e01741504dc7a051e274f1e803d454@91.121.65.179:40404

**Comment by msornay** [comment]
enode://ee3da491ce6a155eb132708eb0e8d04b0637926ec0ae1b79e63fc97cb9fc3818f49250a0ae0d7f79ed62b66ec677f408c4e01741504dc7a051e274f1e803d454@91.121.65.179:40404

**Comment by pyskell** [comment]
Second node located in Singapore:
enode://ffea3b01c000cdd89e1e9229fea3e80e95b646f9b2aa55071fc865e2f19543c9b06045cc2e69453e6b78100a119e66be1b5ad50b36f2ffd27293caa28efdd1b2@128.199.93.177:30303

**Comment by chek2fire** [comment]
enode://53368afb96ab78d4185a1a1421288615a1b06126631543b69aedf9d7f6497cc99c9640a3565f65beef44c204de83ccd8f70bf847d2bcef0674aac00325477bd9@0.0.0.0:30303
in Lithuania

**Comment by VladimirReshetnikov** [comment]
@chek2fire 0.0.0.0 is a reserved IP address, and cannot be the address of your node. Check you IP here: http://whatismyipaddress.com

**Comment by Codzart** [comment]
May want to try this revision:

`curl -s 'https://github.com/ethereumproject/go-ethereum/issues/4' | grep -oE "enode\:.*\:[0-9]{2,5}" | tr -d " "`

_Not tested on Mac_
;-)

**Comment by mikeyb** [comment]
enode://48e063a6cf5f335b1ef2ed98126bf522cf254396f850c7d442fe2edbbc23398787e14cd4de7968a00175a82762de9cbe9e1407d8ccbcaeca5004d65f8398d759@159.203.255.59:30303

USA West

**Comment by whatisgravity** [comment]
Migrating this discussion to the general volunteer repository as it relates to all classic client developers https://github.com/ethereumproject/volunteer/issues/20

**Comment by whatisgravity** [comment]
@Codzart Thank you! That is very well done. I may need to edit a few posts to improve the autogen list.
