### ISSUE TITLE
(proposal/idea) db: bloom index for account transactions

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#400]
A common use case for interacting with account transactions is to render an account's entire transaction history.

Currently there is no "clean" way to achieve this. With a little Javascript the solution is not difficult, but is time and energy consuming because it requires checking each block for relevant transactions. 

As a solution, one idea has been to use a bloom filter on addresses to create a database index that would make this query much more efficient, and readily exposed to the JS/RPC API.

One arguable opposition to this feature is, as it becomes easier to uncover account transaction history, it diminishes the privacy of pseudo-anonymity. Personally, while I'm all for fungibility (if possible) and/or pseudo-anonymity, it seems to me that simply "leaving it hard/annoying" isn't a convincing reason. Rendering account transaction history is currently in use by pretty much every block explorer, exchange, and developer enthusiast I've seen. Given that the feature is currently widely in use via external workarounds, I see very little drawback in making it easier for users to do accomplish what they're already doing.

eg.
```
admin.accountTransactions(eth.accounts[0])
> ["0xfirsttransaction", "0xsecondtransaction", "0xthirdtransaction"]
```

More detailed specs would of course need to be decided, but this just to put it up for consideration.

**Comment by tzdybal** [comment]
I like the idea. This feature is so widely used, that it would be nice to have it implemented in `geth`. As you said, indexing should provide performance benefits.

Can you elaborate more on why/how you want to use bloom filters? (From my experience they are typically used to check if element is contained in a set, but not for enumerating elements, not for key->values mapping.)

**Comment by splix** [comment]
We can use block bloom, as a set of addresses that were changed in that block, that will improve speed of looking for history of transactions that changed address value/storage.
