### ISSUE TITLE
investigate dependency management

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#404]
Dependencies are currently manually vendored, which can be pretty annoying. At one point it looks like godep [was used](e75d6e147205e32b87f85209a014ce94285e21b9), but was removed for some reason. 

Possibly worth investigating govendor, dep, ... ?

This in light of #403 #402 #392

**Comment by tzdybal** [comment]
Some reading (with many references): https://hackernoon.com/the-state-of-go-dependency-management-6cc5f82a4bfa

I have positive experience with govendor, but it's tempting to try dep ;)
