### ISSUE TITLE
Detect failed via eth_getTransactionReceipt

### ISSUE THREAD

**Issue by khelle** [ethereumproject/go-ethereum#407]
Hi, I have a question regarding detection of failed transactions (out of gas error) in Geth Classic. In last fork Ethereum introduced change in protocol allowing `eth_getTransactionReceipt` to return additional `status` field which can be used for validation. However, this flag is not present in Ethereum Classic protocol. How can I detect that incoming contract transaction was failed or not? I was using a trick with marking as failed each transaction that used all of its gas, however its not 100% accurate. I see the block explorers somehow can distinguish this. Is there a solution for this in Classic yet I dont know of?

**Comment by khelle** [comment]
Ok, I found out that I should use geth's `debug_traceTransaction` and its returned structLogs to determine if the transaction was failure or not when transaction used up all the gas. However, the docs says this call should return something like this:

```
{
  gas: 85301,
  returnValue: "",
  structLogs: [{
      depth: 1,
      error: "",
      gas: 162106,
      gasCost: 3,
      memory: null,
      op: "PUSH1",
      pc: 0,
      stack: [],
      storage: {}
  },
    /* snip */
  {
      depth: 1,
      error: "",
      gas: 100000,
      gasCost: 0,
      memory: ["0000000000000000000000000000000000000000000000000000000000000006", "0000000000000000000000000000000000000000000000000000000000000000", "0000000000000000000000000000000000000000000000000000000000000060"],
      op: "STOP",
      pc: 120,
      stack: ["00000000000000000000000000000000000000000000000000000000d67cbec9"],
      storage: {
        0000000000000000000000000000000000000000000000000000000000000004: "8241fa522772837f0d05511f20caa6da1d5a3209000000000000000400000001",
        0000000000000000000000000000000000000000000000000000000000000006: "0000000000000000000000000000000000000000000000000000000000000001",
        f652222313e28459528d920b65115c16c04f3efc82aaedc97be59f3f377c0d3f: "00000000000000000000000002e816afc1b5c0f39852131959d946eb3b07b5ad"
      }
  }]
```

But in reality, when I try to check the transaction (which failed) I get

```
{
    "jsonrpc": "2.0",
    "id": 1,
    "result": {
        "gas": 21000,
        "returnValue": ""
    }
}
```

soo... am I missing something here?

**Comment by whilei** [comment]
Hey @khelle, I'm looking at this now. Here are some things I'm reasoning around:
- the wiki documentation is inherited from the Foundation (Ethereum HF) and is incongruent with the existing code. Somehow either the documentation was written before the code or pulled after the fork. I wish I had seen it when I wrote #329, and when we resolve this issue will be sure to address it as well.
- there was some talk around this API in slack a while back and I'm looking for it to reference

I've begun writing an first pass at including vm logs in the result [here](https://github.com/whilei/go-ethereum/tree/trace-transaction-fix), but there the `vm.Logs` return value from the tx receipt is also incongruent with the "documented" result:
```
> debug.traceTransaction("0x05e5ec0496c20fe51265a41fae56eff3f310f7f218d583ed691354156e08a001");
{
  gas: 30416,
  returnValue: "",
  structLogs: [{
      address: "0xb09cbe4f7e845184d8c6e4607cd816bfc9bc08d3",
      blockHash: "0x431b0f12c76ce84eb8b58ce825c4f7837c4e116b7a8a07f5068b538392593bea",
      blockNumber: "0x48bacc",
      data: "0x000000000000000000000000c0d332838f14ef42fcde1cf2518c427ddb676729",
      logIndex: "0x0",
      topics: ["0x23919512b2162ddc59b67a65e3b03c419d4105366f7d4a632f5d3c3bee9b1cff"],
      transactionHash: "0x05e5ec0496c20fe51265a41fae56eff3f310f7f218d583ed691354156e08a001",
      transactionIndex: "0x0"
  }]
}
```

Thanks for your patience

cc @tzdybal @sudachen @sorpaas

**Comment by whilei** [comment]
Also noting from the documentation:

> In this mode, tracer is interpreted as a JavaScript expression that is expected to evaluate to an object with (at least) two methods, named step and result.
> stepis a function that takes two arguments, log and db, and is called for each step of the EVM, or when an error occurs, as the specified transaction is traced.
> 
> log has the following fields:

while, of course, the documented example doesn't use the optional `tracer` second argument, but somehow gets the logs returned:

```
> debug.traceTransaction("0x2059dd53ecac9827faad14d364f9e04b1d5fe5b506e3acc886eff7a6f88a696a")
{
  gas: 85301,
  returnValue: "",
  structLogs: [{
      depth: 1,
      error: "",
      gas: 162106,
      gasCost: 3,
```

Geth Classic doesn't implement the `tracer` interface.

**Comment by khelle** [comment]
@whilei hey, thank you for your detailed answer. I really appreciate it as being involved in few cryptocurrency projects on github its rarely seen to have this kind of specific, long answer. Just to be sure - do you suggest to wait for upcoming releases where this will be implemented. When would this be added?

**Comment by khelle** [comment]
Its not possible to determine this now then?

**Comment by whilei** [comment]
Hey @khelle Thanks for checking in again and reminding me about this. You'll notice I'm working a PR in to resolve it now.
