### ISSUE TITLE
Log rotation

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#421]
Currently, if logs are stored in files, there is no way to control the resulting files - with verbose logging, disk space required by logs can grow very fast.
Unfortunately with `glog` it's not possible to use standard `logrotate` command. 
See: https://github.com/google/glog/pull/19 and https://github.com/google/glog/issues/36.

In my opinion, we need two features:
- [ ] removal of old log files (older than configurable duration)
- [ ] enforcing total logs size limit (also configurable)

Bonus feature:
- [ ] compress all archive (not current) log files

**Comment by splix** [comment]
Maybe we can use timestamped log filenames instead? compression/removal could be done by system

**Comment by tzdybal** [comment]
Actually, currently we use timestamped filenames and this is the cause of the problem, because standard tools (`logrotate`, `newsyslog`) expect the filename to be static (without the timestamp part). 

`glog` filename pattern is following: `<program>.<host>.<user>.log.<tag>.<timestamp>.<pid>`. New log file is created after reaching file size limit (so `glog` does part of the job of `logrotate`/`newsyslog`), and there is a symlink always pointing to the latest log file.

I don't know any standard tool able to compress/remove files in such scheme. And I think that possibility to configure the log rotation without any external tools would be very convenient.
