### ISSUE TITLE
Unable to generate DAG > ~2GB

### ISSUE THREAD

**Issue by ppooladmin** [ethereumproject/go-ethereum#425]
Running 4.1.1 and trying to create the DAG on Windows Server 2012 R2. Works fine when the resulting file < 2GB. 

- Block number 4948980. 
- Server has 234GB free on the drive
- Server using 2.9GB of 12GB so plenty free
- 64-Bit System

geth.exe : I1205 09:06:57.256230 cmd/geth/cmd.go:706] making DAG, this could take awhile...
At line:1 char:1
+ &$gethExe makedag $blockNumber .
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (I1205 09:06:57.... take awhile...:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
I1205 09:06:57.256230 vendor/github.com/ethereumproject/ethash/ethash.go:259] Generating DAG for epoch 164 (size 
2449472384) (d5d85ca51867514082660716ef2bedbb55a65250622456390b4a76c4fe98db95)
ERROR unknown Action error: ethash_full_new IO or memory error. See 
https://github.com/codegangsta/cli/blob/master/CHANGELOG.md#deprecated-cli-app-action-signature

**Comment by whilei** [comment]
You're getting an out-of-memory error from the C ethash library, and it's causing geth to `panic`.

I'm afraid I'm not too familiar with Windows memory monitoring tools... it looks like there might be a tool `RAMMap`?

**Comment by ppooladmin** [comment]
Feels like its running a 32-bit version of it and its out of virtual address space. Not too familiar with the C libraries and GO integration myself.
