### ISSUE TITLE
problem: tests inherited from `tests` repository are disabled instead of removed

### ISSUE THREAD

**Issue by sorpaas** [ethereumproject/go-ethereum#427]
Found by @tzdybal. Those tests are [here](https://github.com/ethereumproject/go-ethereum/tree/master/tests/files) and some of them are outdated. We should probably figure out what to do with them.

**Comment by whilei** [comment]
Just for a little detail - the tests in question which are being skipped can be found here: https://github.com/ethereumproject/go-ethereum/blob/master/tests/init.go#L37-L56. 

```
~/gocode/src/github.com/ethereumproject/go-ethereum ⟠ go test -v ./tests | grep PASS | wc -l
      95
~/gocode/src/github.com/ethereumproject/go-ethereum ⟠ go test -v ./tests | grep SKIP | wc -l
       9
```
