### ISSUE TITLE
Create build script for building with SputnikVM

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#429]
### problem
Currently building to include SVM requires cloning, compiling, and copying `sputnikvm-ffi`,
and setting `CGO_LDFLAGS` for the `go build`. This is kind of complicated and
prone to developer/user error.

Instructions are currently as follows, taken from https://github.com/ethereumproject/go-ethereum/pull/428:

----

#### Building with [SputnikVM](https://github.com/ethereumproject/sputnikvm)
Have Rust (>= 1.21) and Golang (>= 1.9) installed.

> For __Linux__ and __macOS__:

```
cd $GOPATH/src/github.com/ethereumproject
git clone https://github.com/ethereumproject/sputnikvm-ffi
cd sputnikvm-ffi/c/ffi
cargo build --release
cp $GOPATH/src/github.com/ethereumproject/sputnikvm-ffi/c/ffi/target/release/libsputnikvm_ffi.a $GOPATH/src/github.com/ethereumproject/sputnikvm-ffi/c/libsputnikvm.a
```
And then build geth with CGO_LDFLAGS:

- In Linux:

```
cd $GOPATH/src/github.com/ethereumproject/go-ethereum/cmd/geth
CGO_LDFLAGS="$GOPATH/src/github.com/ethereumproject/sputnikvm-ffi/c/libsputnikvm.a -ldl" go build -tags=sputnikvm .
```

- In macOS:

```
cd $GOPATH/src/github.com/ethereumproject/go-ethereum/cmd/geth
CGO_LDFLAGS="$GOPATH/src/github.com/ethereumproject/sputnikvm-ffi/c/libsputnikvm.a -ldl -lresolv" go build -tags=sputnikvm .
```

> For __Windows__:

```
cd %GOPATH%\src\github.com\ethereumproject
git clone https://github.com/ethereumproject/sputnikvm-ffi
cd sputnikvm-ffi\c\ffi
cargo build --release
copy %GOPATH%\src\github.com\ethereumproject\sputnikvm-ffi\c\ffi\target\release\sputnikvm.lib %GOPATH%\src\github.com\ethereumproject\sputnikvm-ffi\c\sputnikvm.lib
```
And then build geth with CGO_LDFLAGS:
```
cd %GOPATH%\src\github.com\ethereumproject\go-ethereum\cmd\geth
set CGO_LDFLAGS=-Wl,--allow-multiple-definition %GOPATH%\src\github.com\ethereumproject\sputnikvm-ffi\c\sputnikvm.lib -lws2_32 -luserenv
go build -tags=sputnikvm .
```

----

### solution
Create a build script to automate this process. Could be a [mage file](https://magefile.org/),
make file, or maybe even a deft use of go build tags. Undecided.

Before tackling a specific solution please post what solution seems best to you
and why.

🛠  _Update_:
Looks like we'll go with `makefile`.
- `make build`, aka `make`, defines a build process which includes grabbing dependencies and compiling sputnikvm. This is the important one. Specs are as documented above.
- Up for consideration: `make chain-config` would define a build process for compiling chain configuration from JSON to Go, rel #351 and documented here https://github.com/ethereumproject/go-ethereum/blob/master/core/assets/README.md. This would enable us to remove the raw https://github.com/ethereumproject/go-ethereum/blob/master/core/assets/assets.go chain configuration from source, or the script could just be used as a "developer tool" to document and automate the process for when changes to the default chain config happen (...which is rarely).

**Comment by sorpaas** [comment]
@whilei @tzdybal I have some questions:

1. How does go handle git submodules when running `go get`? What would happen if the submodule is in the vendor folder?
2. Is it a good practice to use [binary-only packages](https://tip.golang.org/pkg/go/build/#hdr-Binary_Only_Packages)?

**Comment by r8d8** [comment]
We can use [dep](https://github.com/golang/dep)
Maybe we can add docker image, for those that just want to play with geth?
It would be nice to have containers for geth, it's much easier to run docker

**Comment by whilei** [comment]
Dep looks good to me. (Rel #404, too)

Docker images would be great to have as well... note that splix has already setup https://github.com/ethereumproject/ecip1017test/blob/master/docker/geth/Dockerfile, maybe we can piggy back that.

I'm inclined to use a makefile over a mage file since it typically won't require installing any extra dependencies, like mage. It looks like there's `nmake` for Windows...

**Comment by tzdybal** [comment]
Just a thought - create _universal_ build script that can be started both in Travis and locally, using `janus` if available, setting version correctly, able to build with SputnikVM and without.
