### ISSUE TITLE
geth.* tests are failing on Windows

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#44]
Bunch of tests:

- geth.TestAccountNewBadRepeat
- geth.TestUnlockFlagAmbiguousWrongPassword 	
- geth.TestUnlockFlagPasswordFileWrongPassword 	
- geth.TestUnlockFlagWrongPassword 	
- geth.TestWalletImportBadPassword

And it seems there're same reasons, test code ignores one of the output lines (maybe because it goes to stderr). Notice that tests expects `Fatal: Passphrases do not match`, which is exists `run_test.go:259: (stderr) Fatal: Passphrases do not match` but got unnoticed by test

````
Failed
run_test.go:259: (stderr) Fatal: Passphrases do not match
run_test.go:149: Not enough output, got until ◊:
    ---------------- (stdout text)
    Your new account is locked with a password. Please give a password. Do not forget this password.
    !! Unsupported terminal, password will be echoed.
    Passphrase: 
    Repeat passphrase: 
    
    ---------------- (expected text)
    Your new account is locked with a password. Please give a password. Do not forget this password.
    !! Unsupported terminal, password will be echoed.
    Passphrase: 
    Repeat passphrase: 
    ◊Fatal: Passphrases do not match
````

http://build.ethereumclassic.org/viewLog.html?buildId=260&tab=buildResultsDiv&buildTypeId=GoEthereumClassic_Develop_TestWindows

**Comment by ericsomdahl** [comment]
the problem was STDOUT redirection in the Windows build environment.  I reconfigured TeamCity to use Powershell as a shell environment rather than Windows console to fix the issue
