### ISSUE TITLE
timed out fork-check, dropping

### ISSUE THREAD

**Issue by NameNull** [ethereumproject/go-ethereum#441]
![image](https://user-images.githubusercontent.com/11754843/34248717-04207ab0-e672-11e7-9b08-de2f9b9f2b41.png)

was there a fork in block 5000000?

**Comment by whilei** [comment]
@NameNull Hi - there was indeed a [scheduled protocol fork at block 5M](https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1017.md), but this log is just from a normal peer check for the DAO fork (block 1920000) to see if a given peer is on the Classic chain or not.
