### ISSUE TITLE
too many open files

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#447]
```
I1229 13:41:21.882670 server.go:2753] http: Accept error: accept tcp [::]:8545: accept4: too many open files; retrying in 1s
```

Just started getting these errors, plus node consumes 100% CPU. Restart doesn't help.

Version: 4.1.2

**Comment by whilei** [comment]
Doing a little digging on this one...
- https://groups.google.com/forum/#!topic/golang-nuts/u1tgNiC51Uc
- http://craigwickesser.com/2015/01/golang-http-to-many-open-files/
- https://github.com/drone/drone/issues/644
