### ISSUE TITLE
Sync problem geth 4.1.1

### ISSUE THREAD

**Issue by jorgeog96** [ethereumproject/go-ethereum#450]
Currently, I´m still downloading the ETC blockchain on my device...I cross the border of 2.4-2.5 M (so slow). I was in 4370000 block number and during a few days...I was experimenting problems with peers (a lot) and not going ahead with the sync. The messages are like this:

     peer "....." drop: empty header set by peer
     peer "....." drop: retrieved hash chain is invalid
     peer "......" drop: timeout

After a week and a half, I am about 4400000 but the problem is the same, a lot of problems with peers and doesn´t sync.  I am also using these flags: --cache=2048 and --max-peers=60 (ensure rising the numbers of peers). I have checked the system clock and is completely correct (time, time zone and server). 

This is frustrating...I can´t start the client...

    Geth version: 4.1.1
    OS: Windows 7 Professional 64 bits

**Comment by jorgeog96** [comment]
Sorry, there is a mistake...The current geth classic version is 4.1.1

**Comment by tzdybal** [comment]
@jorgeog96 Have you tried to restart geth? This should help.
I think this is similar issue to #448.

**Comment by jorgeog96** [comment]
What do you mean with restart?. @tzdybal Can you give me the instructions to restart properly the client? Windows user.

**Comment by tzdybal** [comment]
@jorgeog96, just stop it gently (press <kbd>CTRL</kbd>+<kbd>C</kbd>) and then [start it again](https://www.youtube.com/watch?v=p85xwZ_OLX0).

**Comment by jorgeog96** [comment]
@tzdybal ah ok, I thought you were meaning to another process like start again the sync and do the checkpoint process. Yes, I´ve done that process many times...stop it gently and start..but the same issue. He starts to synchronize and he just takes a few blocks..like 200 or 1000 and then, the problem appears again. Peers retrieved and those stuff.... 

By the way, why a lot of commands of javascript console don´t work in this geth classic? like admin.chainSyncStatus, etc.

**Comment by tzdybal** [comment]
We have a new release - [v4.2.0](https://github.com/ethereumproject/go-ethereum/releases/tag/v4.2.0) - could you please try it out?

The `admin.chainSyncStatus` [was deprecated](https://github.com/ethereum/go-ethereum/issues/1959#issuecomment-154020080) (before the fork). Probably same for other JS console commands.

**Comment by whilei** [comment]
Also worth ensuring that you're using web3 0.2x and not the unreleased 1.x

**Comment by jorgeog96** [comment]
@tzdybal  Today, i´ve launched geth 4.1.2 but something weird it´s happening. Maybe it´s an issue or a bug in this version. Before, on 4.1.1. I usually have between 11 or 13 peers while synchronization process, but now I have 0/25 and he returns the following message:

       Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered

**Comment by jorgeog96** [comment]
@whilei do I need have web3.js install on my device? Because I have an issue with that.

**Comment by whilei** [comment]
@jorgeog96 No, you don't need to install web3 manually, it comes inside of geth `console`/`rpc`. 

The udp mapping issue might be a firewall problem -- have you double-checked that your firewall is open for tcp and udp on the required ports?

**Comment by jorgeog96** [comment]
The same problem...also I´ve checked out the ports with the firewall, in fact, I´ve created new rules opening the ports to ensure that they are working. I attach the following images:

![sync-1](https://user-images.githubusercontent.com/29740800/34969075-a0ebe1da-fa32-11e7-9007-2f45ccd2dfef.png)

![sync-2](https://user-images.githubusercontent.com/29740800/34969078-a4a34d86-fa32-11e7-8378-662c360a92b8.png)
 
So, if you prefer we can open a new issue for the try with geth 4.2.0?  I don´t know what else I have to do in order to have the blockchain complete. It can´t be too complicated!

**Comment by whilei** [comment]
This is definitely a network connection issue --  

@gagarin55 if I remember right you had and resolved a similar problem with configuring your firewall on Windows for geth?

**Comment by jorgeog96** [comment]
@whilei for this task, i´m running a device with windows 7 professional and a HDD hard drive by the way. I´ve created two new rules (inbound rules) : geth 30303 TCP and geth 30303 UDP. The name of each rule indicates the specifications related to protocols and ports. In programs and services, I specified run this rule with the geth.exe (saved in the proper dir (in a folder inside users don´t in a roaming folder I mean), version 4.2.0 latest).
