### ISSUE TITLE
geth 4.1.2. pre-release return me virus on the scanner

### ISSUE THREAD

**Issue by jorgeog96** [ethereumproject/go-ethereum#451]
If you scan the .zip folder for windows 64 version client in virustotal, he will return a malicious file inside. 

Kaspersky -> not-a-virus:NetTool.Win32.TorJok.tc
ZoneAlarm -> not-a-virus:NetTool.Win32.TorJok.tc

So, he detects a potentially unwanted tool inside.

**Comment by whilei** [comment]
Does it only do this for 4.1.2?

**Comment by jorgeog96** [comment]
4.1.1 latest release also give me alerts, even more! But the good new is that geth 4.1.2. latest release doesn´t show any alert or warning.
