### ISSUE TITLE
How to work with nodejs

### ISSUE THREAD

**Issue by thomsonimjd** [ethereumproject/go-ethereum#463]
How can I connect the geth-classic to nodejs or other platforms to generate new address, balance check, sendTransactions functions to happen.  Is there any testnet network for this like kovan, ropsten.

**Comment by splix** [comment]
morden is a default testnet for etc

**Comment by thomsonimjd** [comment]
@splix thanks a lot for your reply, I am just new to this ETC, how to can I work with the morden. coyuld you please give me any samples on this

**Comment by thomsonimjd** [comment]
you meant to say that. geth --testnet --fast --cache=512 console`, thanks for that if so.  How can I get the testnet coins and how to access rpc ?

**Comment by splix** [comment]
I suggest to continue discussion at https://forum.ethereumclassic.org/c/dev
