### ISSUE TITLE
trying to launch private network using geth 4.2.0 and returns me error

### ISSUE THREAD

**Issue by jorgeog96** [ethereumproject/go-ethereum#466]
Currently, I am using VPS Ubuntu and trying to run a private solo network for testing purposes.

I´ve executed this command: 

       sudo ./geth --chain ovxchain.json

Have this output on the console:

F0111 02:14:03.273312 cmd/geth/flag.go:215] Invalid chain config file at --chain: 'ovxchain.json': Invalid chain configuration file. Please check the existence and integrity of keys and values for: diehard chainid
Assuming literal identity argument.

This is my configuration file (ovxchain.json):

    {
      "identity": "OVX",
      "network": 25296,
      "name": " OVX ETCTestNetwork",
      "genesis": {
        "nonce": "0x0000000000000055",
        "timestamp": "",
        "parentHash": "",
        "extraData": "",
        "gasLimit": "0x2DC6C0",
        "difficulty": "0x000200",
        "mixhash": "",
        "coinbase": "",
        "alloc": {
       }
     },
     "chainConfig": {
        "forks": [ {}
       ],
        "badHashes": [ {}
       ]
      },
     "bootstrap": [ 
      ]
    }

**Comment by whilei** [comment]
Hm -- currently the chain config validator requires that a value `chainID` for replay projection (eip 155, Diehard Fork) to be set.  I'm looking at what it would mean to remove this requirement right now.

In the meantime, this is working for me:

```
{
  "identity": "OVX",
  "network": 25296,
  "name": " OVX ETCTestNetwork",
  "genesis": {
    "nonce": "0x0000000000000055",
    "timestamp": "",
    "parentHash": "",
    "extraData": "",
    "gasLimit": "0x2DC6C0",
    "difficulty": "0x000200",
    "mixhash": "",
    "coinbase": "",
    "alloc": {
   }
 },
 "chainConfig": {
    "forks": [
       {
            "name": "Diehard",
            "block": 1,
            "features": [
                {
                    "id": "eip155",
                    "options": {
                        "chainID": 62
                    }
                }
            ]
        }

   ],
    "badHashes": [ {}
   ]
  },
 "bootstrap": [
  ]
}
```

**Comment by jorgeog96** [comment]
Ok, it works for me also!! :D And...you guys should remove that requirement... Thanks a lot

**Comment by whilei** [comment]
See associated issue for this change, closing this one now ✅
