### ISSUE TITLE
gopkg.in/qml.v1/webengine error

### ISSUE THREAD

**Issue by gnikitin2012** [ethereumproject/go-ethereum#467]
An error occurred during building on fedora 24:

Parsing meta tags from https://gopkg.in/qml.v1?go-get=1 (status code 200)
package github.com/ethereumproject/go-ethereum/vendor/gopkg.in/karalabe/cookiejar.v2/tools/arenas/codingame
        imports gopkg.in/qml.v1/webengine: cannot find package "gopkg.in/qml.v1/webengine" in any of:
        /usr/lib/golang/src/gopkg.in/qml.v1/webengine (from $GOROOT)
        /root/rpmbuild/BUILD/go-ethereum-4.2.0/src/gopkg.in/qml.v1/webengine (from $GOPATH)
github.com/codegangsta/cli (download)
error: Bad exit status from /var/tmp/rpm-tmp.F2gahE (%build)
    Bad exit status from /var/tmp/rpm-tmp.F2gahE (%build)

**Comment by tzdybal** [comment]
@gnikitin2012 What's your version of go? Please also share commands used to build the package (the `go` invocation, not the entire RPM build commands).

**Comment by tzdybal** [comment]
@gnikitin2012, I think, I know the problem. As this is a normal `go` source, you need to keep everything in the correct paths. Correct way of work is more or less following:
```
mkdir buildroot
cd buildroot
export GOPATH=$PWD

wget -c https://github.com/ethereumproject/go-ethereum/archive/v4.2.0.tar.gz 
tar xzf v4.2.0.tar.gz
mkdir -p src/github.com/ethereumproject
mv go-ethereum-4.2.0 src/github.com/ethereumproject/go-ethereum
cd src/github.com/ethereumproject/go-ethereum
go build -ldflags "-X main.Version=v4.2.0" ./cmd/geth
./geth version
```

**Comment by gnikitin2012** [comment]
It's didn't help.  I got such mistake in rezult:

**Comment by gnikitin2012** [comment]
Version of ethereum-classic - 4.2.0. The version 4.1.2 and earlier were build without problems.

**Comment by whilei** [comment]
I may be wrong, but it seems like there may be something strange with your Go configuration or directory structure...? 

```shell
/usr/lib/golang/src/github.com/ethereumproject/ethash (from $GOROOT)
/root/rpmbuild/BUILD/go-ethereum-4.2.0/src/github.com/ethereumproject/ethash (from $GOPATH)
```

Can you give the output of `$ go env`?

**Comment by gnikitin2012** [comment]
I usually install GOPATH to build dir. The output of go env:
GOARCH="amd64"
GOBIN=""
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOOS="linux"
GOPATH=""
GORACE=""
GOROOT="/usr/lib/golang"
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
CC="gcc"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build795189158=/tmp/go-build -gno-record-gcc-switches"
CXX="g++"
CGO_ENABLED="1"

**Comment by whilei** [comment]
So I think the issue is coming from confused `GOPATH` and `GOROOT` values. `GOROOT` should be where the actual Go language is installed and executed from, and `GOPATH` should be where you keep your go code packages (`GOPATH/src`) and compiled binaries (`GOPATH/bin`).

See [this SO answer](https://stackoverflow.com/questions/7970390/what-should-be-the-values-of-gopath-and-goroot#10847122) for some more background information and references.

**Comment by tzdybal** [comment]
@whilei `/usr/lib/golang` looks like a valid `GOROOT`, and setting `GOPATH` into RPM build directory also seems right.
@gnikitin2012 are you using gccgo or plain go? What version of `go` are you using?

**Comment by gnikitin2012** [comment]
@tzdybal I use  go version go1.7.4 linux/amd64

**Comment by tzdybal** [comment]
As stated in [README](https://github.com/ethereumproject/go-ethereum#dependencies): *Building geth requires both Go >=1.9*. Please update and try to rebuild.

**Comment by gnikitin2012** [comment]
@tzdybal yes, it solved the problem. Thank you!
