### ISSUE TITLE
Releasing .deb packages

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#469]
As @pyskell suggested on Slack/Discord, it would be nice to create `.deb` packages for `geth`.
Technically it should be very easy as binary is static, so there are no dependencies, and there is only one file - all we need to do is to create `DEBIAN/control` file with proper version number.

**Comment by r8d8** [comment]
Do we need to put it into deb repository, or it will be just `.deb` file attached to releases ?

**Comment by whilei** [comment]
I'd say getting into the deb repository (for `dpkg` and/or `apt`) would be great, but maybe a separate issue/project. Do you agree?

**Comment by r8d8** [comment]
yeap, sure
