### ISSUE TITLE
Problems with resolver in v4.2.1

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#473]
After changes related to linking introduced in v4.2.1, on some systems there is a problem with resolver.

To reproduce the problem, simply run `geth --rpc`. This cause resolving `localhost`, and depending on distribution, may work, display fatal error message or crash the app.

The error message is following: `Fatal: Error starting protocol stack: listen tcp: lookup localhost: no such host`

Known affected distributions:
* Ubuntu 17.04 (fatal error)
* Fedora Core 27 ([crash](https://github.com/ethereumproject/go-ethereum/files/1640527/crash_fc27.log))
* Arch Linux (fatal error)
* CentOS 7 ([crash](https://github.com/ethereumproject/go-ethereum/files/1640591/crash_centos7.log))
* Debian 9.3.0 (fatal error)

Known unaffected distributions:
* Amazon Linux
* openSUSE (42.3 and Tumbleweed)
* Slackware 14.2

**Comment by tzdybal** [comment]
I have some positive results with binary build with `-tags netgo` (but it was my local build). I'll make full CI build to get binaries, and then I'll check on as many distros as I can ;)

**Comment by tzdybal** [comment]
[Test build](http://builds.etcdevteam.com/go-ethereum/v4.2.x/geth-classic-linux-v4.2.1-netgo-5f7e79f.tar.gz) is ready.

Test results:
* Amazon Linux ✅ 
* Debian 9.3.0 ✅ 
* Fedora Core 27 ✅

**Comment by tzdybal** [comment]
@whilei do you think we should re-release `v4.2.1` or make a bugfix release `v4.2.2`?

**Comment by whilei** [comment]
i would say 4.2.2. there’s no rewriting history ;)

**Comment by tzdybal** [comment]
There is very easy workaround to resolve the issue - pure Go resolver [can be forced](https://golang.org/pkg/net/#hdr-Name_Resolution) at runtime with:
```export GODEBUG=netdns=go```
