### ISSUE TITLE
check deb keys

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#48]
In commit [15e5b90] coming from Forked Geth there're following line in `.travis.yml`:

```
- go run build/ci.go debsrc -signer "Felix Lange (Geth CI Testing Key) <fjl@twurst.com>" -upload ppa:lp-fjl/geth-ci-testing
```

Which should probably be changed to our configs

**Comment by ericsomdahl** [comment]
@realcodywburns and I are working on this.  We aren't using Travis so we could probably just delete the .travis.yml file altogether.

**Comment by pascaldekloe** [comment]
No more Debian packaging. The single binaries are simple enough as they are.
