### ISSUE TITLE
mlog: implement mlog file rotation and compression

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#492]
mlog files get big pretty fast. So I'd say either implement a set of options much like existing debug log rotation options, or lower the max file size (current max file size is `1073.74 MB`) to make externally-handled log-rotation more practical.

**Comment by tzdybal** [comment]
What do you think about removing files after processing by filebeat? 
(filebeat registry can be used to get information about 'processing status' of each file, see https://github.com/andrea-romagnoli/filebeat-cleaner)

**Comment by tzdybal** [comment]
https://github.com/tzdybal/filebeat-cleaner - version with `--remove` option.
