### ISSUE TITLE
circleci deploy should depend on passing unit and bats tests

### ISSUE THREAD

**Issue by whilei** [ethereumproject/go-ethereum#495]
Currently, CircleCI will deploy regardless of test suite output. Not sure that this is necessarily a bug, but should be at least considered.

![screen shot 2018-02-05 at 18 41 57](https://user-images.githubusercontent.com/10228550/35797876-73cd8bb8-0aa4-11e8-88db-85094ccb86c6.png)

**Comment by tzdybal** [comment]
This is strange. Workflow is configured in a way, that deploy step depends on both testing steps... I'll double-check.

**Comment by tzdybal** [comment]
Double checked the `.circleci/config.yml`, and deploy step requires both test steps. Have you checked the CircleCI workflow page to ensure that it's not just a display/github integration issue?

**Comment by whilei** [comment]
I followed the link and the CircleCI GUI showed that the deploy had been successful. I didn't, however, follow up and check the builds page, but took only Circle+janus's word for it ;)

**Comment by tzdybal** [comment]
Let's take [a recent workflow execution](https://circleci.com/workflow-run/456a18ed-f9ed-4b1f-bf79-f5637e4e448a) as example.

1. dependency graph is displayed correctly
1. job numbers seems legit - there is even one job between test jobs and deploy job (it's from Linux worklow)
1. job timestamps seems legit (see screenshots below

![mac_bats_tests](https://user-images.githubusercontent.com/1138893/35947105-8c7b82d2-0c66-11e8-955d-9a4b79a253fe.png)
![mac_unit_tests](https://user-images.githubusercontent.com/1138893/35947103-8c59bbd4-0c66-11e8-9c10-948549c902bf.png)
![mac_deploy](https://user-images.githubusercontent.com/1138893/35947102-8c35249a-0c66-11e8-975e-a15c0e390d5c.png)

From your screenshot I can't find the exact changes / job numbers for 100% verification.

**Comment by whilei** [comment]
You're right. Closing issue for now, pending more conclusive evidence.
