### ISSUE TITLE
broken link in repo desc

### ISSUE THREAD

**Issue by MrComputerCodes** [ethereumproject/go-ethereum#5]
points to ethereumproject.github.io

**Comment by whatisgravity** [comment]
Thanks, the README and description need a lot of love. 

We will need to get our on continuous development setup too to match the previous README. 

I will leave this issue open until we can address both the description and the README

**Comment by whatisgravity** [comment]
I believe splix solved these, an automated build server and traviscl sever would be beneficial but that can be opened as a separate ticket. If you notice any other broken links reopen this.
