### ISSUE TITLE
1.4.15 Builds

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#50]
Looks like these have not been released yet. It appears the changes have already been merged in though, I will go ahead and sign and release these builds after some testing. If anyone has any objections or comments please share them.

I'm still reading about the DOS attacks but I should have some fixes proposed as pull requests soon as I'm able to.

**Comment by mikeyb** [comment]
The builds 1.4.13 - 1.4.15 are failing tests and do not work on the blockchain for processing blocks [as commented here](https://github.com/ethereumproject/go-ethereum/pull/46#issuecomment-251666652)

Also, the current `develop` branch compiles but fails tests as well with some of the difficulty bomb additions

```
~/p/go-ethereum ❯❯❯ go test ./tests                      develop ✭
# _/home/miko/projects/go-ethereum/tests
tests/vm_test_util.go:244: undefined: params.DiehardBlock
tests/vm_test_util.go:244: undefined: params.ExplosionBlock
FAIL	_/home/miko/projects/go-ethereum/tests [build failed]
```

**Comment by whatisgravity** [comment]
Thanks for the additional information. I was notified about issues with tests but the specific information is very helpful.

**Comment by ericsomdahl** [comment]
@whatisgravity :  the teamcity build system is building, signing, and uploading to Bintray anything that gets checked in, including release tags.  [Bintray link](https://bintray.com/ethereumproject/GoEthereumClassic/go-ethereum)

Well, TC is polling github every 20 minutes.  I think intermediate changesets get rolled into the same build.

I generated a keypair for doing the code signing.  [PK is here](https://github.com/ethereumproject/volunteer/tree/master/Client-Restoration)

**Comment by realcodywburns** [comment]
I'm a little tardy to the party, but, etc-geth-dev builds and passes on docker

**Comment by ericsomdahl** [comment]
the merge or PR #49 dropped these changes onto **develop**.  All tests are passing except for the ARM builds -- which are failing due to Out of Memory errors rather than any actual issues.
