### ISSUE TITLE
genesis.json

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#500]
Move genesis state from `chain.json` to a separate file called `genesis.json` located in same directory. This is biggest part of config and you are not going to edit it after launch, so better to move it out.

**Comment by splix** [comment]
It makes sense to make it more flexible in implement in same way as other fork configurations. Let's consider following:
```
"chainConfig": {
"forks": [
  {
    "name": "Genesis",
    "block": 0,
    "features": {
      "id": "alloc",
      "options": { "path": "genesis.json" }
    }
  }
]
}
```

That will allow for a private chain to change state after launch

**Comment by whilei** [comment]
This was implemented via https://github.com/ethereumproject/go-ethereum/pull/556, using and `includes` field for separate genesis and bootnodes files, per https://github.com/ethereumproject/go-ethereum/blob/master/core/config/mainnet.json#L107
