### ISSUE TITLE
The currency was not sent to my wallet

### ISSUE THREAD

**Issue by ysamir48** [ethereumproject/go-ethereum#507]
Hi my friend
 I have a problem I have sent to the portfolio of the site so far has not reached Lia Shi and this address of the transmitter

0x5a10b5e4eb7a0ba32d1788ba30a86b8f04ba79125824e9b49f6fc3eee1c5957d

![2018-02-16_141038](https://user-images.githubusercontent.com/36533810/36305087-381c6abc-1323-11e8-8fd4-a287d22d5e0d.png)

**Comment by ysamir48** [comment]
This is the title of the wallet that has been sent to her and nothing has come of it so far
0x3af801bce9cbb60fbf0375a55117a053d0002843
![2018-02-16_131954](https://user-images.githubusercontent.com/36533810/36306440-cabe0ec0-1328-11e8-8aa7-ee45a48e3129.png)

**Comment by tzdybal** [comment]
Look at the header of Emerald Wallet - it is still synchronizing with blockchain - on the screenshot it at block 833733, while transaction was made in block 5392135. You can either:
* wait for synchronization (may take some time and disk-space)
* use remote endpoint (click on `Mainnet` (top right) and select `Mainnet (epool.io)` or `Mainnet (gastracker.io)`)
