### ISSUE TITLE
Geth Export/Import chain data

### ISSUE THREAD

**Issue by GeoSkyGPS** [ethereumproject/go-ethereum#518]
When I  run the command `geth export file` on a latest synced ETC mainnet chain. I get a 6Gb file.

When I import it, it's already taking about 14 hours and the chaindata is 35Gb at the moment. Here is some output I see in the `geth.INFO` log file. This starts happening after the log stops showing inserting new blocks. Someone mentioned the bloom_filter decompression in the discord development channel.

Thank you.

Log output.
`c170241388a35b37ba2910fa1 13 0233acf8d87488ad70b4dd08d297d90d759272518e8ec1b262dfb161f0d37e67 0]}
I0228 21:40:58.371607 core/vm/vm.go:113] running byte VM 6e315a09
I0228 21:40:59.078307 core/vm/vm.go:116] byte VM 6e315a09 done. time: 706.676221ms instrc: 571985
I0228 21:40:59.078894 core/state_processor.go:136] receipt{med=e99736a5c645b3b231e71a617e24ff2128f8bd68379ef6f7916389e598c09333 cgas=2710573 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
I0228 21:40:59.082080 core/blockchain.go:1510] [1519854059082042738] inserted block #1722968 (15 TXs 2710573 G 0 UNCs) [0x0233acf8d87488ad70b4dd08d297d90d759272518e8ec1b262dfb161f0d37e67]. Took 747.39669ms
I0228 21:40:59.084745 core/state_processor.go:136] receipt{med=7205d2b2c5848beee15e865f74d0615990363554e5c233f44c42edd48d121d3f cgas=21000 bloom=00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 logs=[]}
I0228 21:40:59.085824 core/state_processor.go:136] receipt{med=bd43df5f787bd77bdbe8a01aab12f7c5ba83841
f3b2bc0598a4bd4c6259d0fdf cgas=42000 `

**Comment by whilei** [comment]
This looks to me like the import is working, although apparently very slowly.

**Comment by whilei** [comment]
I’ve made a couple of exploratory changes locally to the implementation and have been able to reduce the import time by approximately 50% if the import methods assume that the data is “already safe,” and skip the validations that usually happen before block insertion. But this is just one idea, and I think the import method design could be more largely refactored if safety is assumed.

**Comment by DialogueSolutions** [comment]
I think anytime anyone bootstraps or downloads chaindata from an unknown source should always be doing so with caution.

Maybe another idea is to give the user a safe/unsafe flag for export/import.

So if you're bootstrapping for yourself or between trusted parties it's much faster and for the more cautious ones they can do the full safe import/export.

**Comment by tzdybal** [comment]
I think that giving a choice is a nice feature.

**Comment by eellund** [comment]
Some feedback for you in this, my first post. Maybe need to consider handling non-standard data directories. Starting _geth_ with the '_-datadir_' option followed by _export_ <filename>, the 100+ gigabytes of data does not get included. However, the 'most recent' headers appear to be the correct age and number. Hope that helps.
