### ISSUE TITLE
The method personal_send Transaction does not exist/is not available

### ISSUE THREAD

**Issue by sakis123** [ethereumproject/go-ethereum#526]
i try to send eth but i get the message "The method personal_send Transaction does not exist/is not available"

i work on windows 10

can anyone help me please?

**Comment by splix** [comment]
Correct method name is `eth_sendTransaction`, see https://github.com/ethereumproject/wiki/wiki/JSON-RPC#eth_sendtransaction

**Comment by sakis123** [comment]
i really don't understand what you want to say , i try to send etc and i get the above message 
![default](https://user-images.githubusercontent.com/20616905/37062913-7a9ad3ca-21a0-11e8-84a0-e3b74571b835.png)

**Comment by splix** [comment]
I'm not really sure what application do you use (mist probably?), but it's definitely not go-ethereum

**Comment by sakis123** [comment]
I belive that you are correct about the app. Can you help me? I have a ballance in that wallet but i can't transfer it.

**Comment by splix** [comment]
You'll need to contact developers of the wallet. Or, if you just want to transfer ballance, you can export your private key from it, and import into another wallet, such as MyEtherWallet or [Emerald Wallet](https://github.com/ETCDEVTeam/emerald-wallet)

**Comment by sakis123** [comment]
Thank you very much , i didn't know that you can use the private key file to an other wallet , thank you very much , i am trying to find a solution over 2 months now
