### ISSUE TITLE
personal_sendTransaction returns error

### ISSUE THREAD

**Issue by dukle** [ethereumproject/go-ethereum#547]
Although the personal namespace is installed, the personal_sendTransaction returns error 
`Error: Returned error: The method personal_sendTransaction does not exist/is not available`

I can see that the **SendTransaction**  method is implemented 
https://github.com/ethereumproject/go-ethereum/blob/master/eth/api.go#L507 
but I'm currently using the **SignAndSendTransaction** method which is supposed to be deprecated
https://github.com/ethereumproject/go-ethereum/blob/master/eth/api.go#L536

**Comment by whilei** [comment]
Thanks for reporting this @dukle. There's a PR in now to fix this issue: #549

**Comment by dukle** [comment]
Thanks @whilei
