### ISSUE TITLE
Windows cant build

### ISSUE THREAD

**Issue by huuhadz2k** [ethereumproject/go-ethereum#551]
![image](https://user-images.githubusercontent.com/36265491/38145205-5ff71ddc-3472-11e8-9cc8-630a48c8e6a8.png)
I cant build geth

**Comment by whilei** [comment]
Did you `go get github.com/ethereumproject/go-ethereum/...` already?

**Comment by huuhadz2k** [comment]
![image](https://user-images.githubusercontent.com/36265491/38174733-3438234a-35fc-11e8-96a0-cde72655106e.png)
can't :(

**Comment by whilei** [comment]
This looks like a `c` problem to me -- maybe an issue with having requirements installed or correctly configured.

What do you think @tzdybal?

**Comment by huuhadz2k** [comment]
I'm using windows 10 and have done the tutorial correctly but can not build: '(please help me
TKS

**Comment by tzdybal** [comment]
Damn!, sorry for late reply - somehow I missed the notification. 

For me it looks like you're missing C compiler in your environment.
Similar problem (with solution): https://stackoverflow.com/questions/43396453/golang-cgo-exit-status-2-on-windows
