### ISSUE TITLE
Update bootnodes

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#553]
There're few updates at https://github.com/ethereumproject/volunteer/issues/20

Also I'm going to provide few from ETCDEV and Gastracker. Especially important for testnet

**Comment by DialogueSolutions** [comment]
Hey, 

just an FYI I've been hosting this for a while, was never aware of the above link.

http://mordenexplorer.ethertrack.io/
http://mordenstats.ethertrack.io/

I'm compiling a list of all my test enodes and will post them in here.

bakon

**Comment by Techjar** [comment]
Here's my node, which is listed on http://teststats.epool.io/

enode://f4a1805a51cfdf5afdddf0b43b8d4b687657497311797464046dce65388b9e5a538b55bdb23ae4eac54485a81d47adad48731294efc9d73fbc9f297f625aec70@198.27.80.32:30303

**Comment by MatthewCroughan** [comment]
I have multiple nodes, sorry for the long delay.

**Canada:**
enode://d79b12fc48a494ba7053bbc30cbe510060ebb3a2ce9bb4f88076303e97e31e2af263c61e797af0af20419b7268b2bfb2d2f196b57242a454035ecb6001cc69a2@94.23.49.75:30303

**France:**
enode://a329e2399e6d72009690faa15a82ae13ef2015bc5e72ffb22f92ea83cf3bfc9ce45d43c38b3c2289c148939d3911e9d1a9e940f41698dba54508b59489072b2a@5.135.157.4:30303

**UK:**
enode://f570df80b5589dfb0a7657adb62b93dc55e76d491694d8965c6382964e6f397ae0b8c3548ef0a108151f3b1485c75769ff203df2db7ace385ee98fdb2766ba3b@86.8.233.254:30303

**Comment by whilei** [comment]
Thanks for these contributions! Ya'll rock! Can you please edit your comments to specify if the nodes are for `mainnet` or `morden`?

**Comment by ethernodeio** [comment]
All these nodes are for the morden chain.

admin.addPeer("enode://681c68e3291e2cd922aeda3c0357dbaeeee5f9837c061714b1f27b56b72d01c11fefd33ff157d2c9b055892494a690be08c79d340efb34c2876ec3ab0976a88c@45.32.190.69:30303")
Australia Node

admin.addPeer("enode://3b5440da2afe365c1bb934cbf6a48beaf223adee95b16af39229b9e3db4c54f428ad463b69b0c2e88fca87b68e538ee33c6067a66491187b5aa77ac1112520fd@45.77.17.124:30303")
Japan Node

admin.addPeer("enode://ad51158470fb86686cbe6e49eaf0abde3a117c50b7522f1d994addf154cd6ae35674b8580f30f3589586c8585c13ce8c634e9df1fe65f16723727970c27baf9f@207.148.120.221:30303")
Singapore node
