### ISSUE TITLE
Modify block mining to be ASIC resistant.

### ISSUE THREAD

**Issue by jamking** [ethereumproject/go-ethereum#555]
Any plan on this for etc project?

This will be a good market oportunity for ETC to get miners from eth with anti ASIC effort. Monero's hashrate drops dramatically after hard fork. 

Such move will show the community that ETC really cares about miners.

**Comment by splix** [comment]
ETCDEV is currently monitoring hash distribution and doesn't have plans to change mining algorithms, but it can be reconsidered later
