### ISSUE TITLE
How I detect that smart contract call failed ?

### ISSUE THREAD

**Issue by gagarin55** [ethereumproject/go-ethereum#560]
Ethereum [provides `Status` attribute in `TransactionReceipt`](https://ethereum.stackexchange.com/questions/28077/how-do-i-detect-a-failed-transaction-after-the-byzantium-fork-as-the-revert-opco/28078?stw=2)

I didn't find Status in out RPC code. So, how to detect that TX 0x430d9d9df7900750c48e3475a97b58dae9d4e0f2752478ef8aa695b1b67f34ed on Morden network is failed ?

**Comment by whilei** [comment]
Rel #431, see there for related discussion

**Comment by gagarin55** [comment]
I suggest make hard fork to implement these critical feature (https://github.com/ethereum/EIPs/blob/master/EIPS/eip-658.md)

**Comment by tzdybal** [comment]
Closed via #634.
