### ISSUE TITLE
Previously installed Geth for Ethereum

### ISSUE THREAD

**Issue by saifiifazal** [ethereumproject/go-ethereum#563]
i have installed this ethereum classic geth. But in version its showing as Geth 1.8.2 stable .is this correct?

**Comment by splix** [comment]
No, it should be 5.x.x. Please make sure you've installed it from Classic repository at https://github.com/ethereumproject/go-ethereum/releases

**Comment by saifiifazal** [comment]
Thanks. I built it again. Its working now. And showing 5.1.1
