### ISSUE TITLE
etc geth cannot sync

### ISSUE THREAD

**Issue by taczc64** [ethereumproject/go-ethereum#57]
#### System information

Geth version: `2.0`
OS & Version: /Linux  ubutu 14.0.4
Commit hash : (if `develop`)
#### Expected behaviour

sync blockChain 
#### Actual behaviour

stop sync at 172778 block, total may 242xxxx
#### Steps to reproduce the behaviour

./build/bin/geth --rpc --cache=512 --unlock 0xf28cc406d38ecb861973xxxxxxxxxxxxxxxxxxxx
#### Backtrace

```
[backtrace]
```

what 's  wrong with geth ? it runs normally two days before, it cannot sync from yesterday, how to fix it?

**Comment by taczc64** [comment]
now, i restart geth, it sync again, but very slow

**Comment by splix** [comment]
There is a ddos attack against ETH & ETC for past two days, and so far there're no permanent solution for it. I suggest for follow this recommendations and discussion: https://np.reddit.com/r/EthereumClassic/comments/572vx9/etc_network_issues_discussion/

**Comment by taczc64** [comment]
@splix yesterday i have increased swap to 64g, my ram is 16G also. but sync still very slow, like this:
I1014 00:53:04.887053 core/blockchain.go:960] imported 2048 block(s) (0 queued 0 ignored) including 5618 txs in 7h47m59.485383587s. #2423326 [0c960f1a / 7df26782]
its over 7 hours to import 2048 blocks...
do you have any other suggest to make it better?thank you
