### ISSUE TITLE
WS Origin is undefined on Ubuntu 16.04, therefore only viable option is wsorigins set to "*"

### ISSUE THREAD

**Issue by Bunjin** [ethereumproject/go-ethereum#575]
Running geth with 
/usr/bin/geth --ws --wsport 8540 --wsorigins 127.0.0.1

But ws is not available:

wscat -c ws://127.0.0.1:8540
error: Error: unexpected server response (403)

and the geth log:
geth[5403]: WARN [04-30|09:16:38] origin '' not allowed on WS-RPC interface

Noticing that the origin is empty, I found out that it's related to this : 
https://stackoverflow.com/questions/41257455/how-to-get-origin-from-request-headers

In this line:
https://github.com/ethereumproject/go-ethereum/blob/master/rpc/websocket.go#L79

req.Header.Get("Origin") should be changed to req.Header.Get("origin")

see PR:
https://github.com/ethereumproject/go-ethereum/pull/576

**Comment by whilei** [comment]
This appears to be an issue arising from `wscat` usage, see feedback in #576

**Comment by whilei** [comment]
Closing since user/+tooling issue, not a geth problem. Thanks for your interest and offering a possible solution, though, @Bunjin.
