### ISSUE TITLE
Wow, you are deceptive liars for choosing 'ethereumproject' as your github repo name

### ISSUE THREAD

**Issue by mrcybermac** [ethereumproject/go-ethereum#58]
#### System information

Geth version: `geth version`
OS & Version: Windows/Linux/OSX
Commit hash : (if `develop`)

#### Expected behaviour

What possible reason do you have for not choosing 'ethereumclassic' (which is bad enough) as your github name?  The only reason that I can think of is pure ill-willed deception.  Shame on you.

#### Backtrace

````
[backtrace]
````

**Comment by mikeyb** [comment]
[Donny, you're out of your element.](https://www.youtube.com/watch?v=3foXJfWlgoM)

**Comment by arvicco** [comment]
Using Github account for trolling? This must be the new low...
