### ISSUE TITLE
remove "--add-std" arg, deprecated in solidity 0.4.21

### ISSUE THREAD

**Issue by yushizhao** [ethereumproject/go-ethereum#583]
https://github.com/ethereum/go-ethereum/pull/16289

**Comment by yushizhao** [comment]
Will ETC do the same, or stick to an older version of solidity?

**Comment by splix** [comment]
I would prefer to remove solidity compiler from geth. It's unnecessary extra complexity

**Comment by whilei** [comment]
@splix Do you see foreseeable drawbacks to removing the deprecated flag from the command argument in the meantime (until discussion or decision around removing compiler completely happens)?

**Comment by splix** [comment]
I don't see any drawback, safe to remove

**Comment by whilei** [comment]
Closing via #589
