### ISSUE TITLE
E0509

### ISSUE THREAD

**Issue by liyanhrxy** [ethereumproject/go-ethereum#587]
what's wrong with my geth ????? whenever i start it ,i always got the message like this --"E0509 13:11:31.215032 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered"  ?? tell me why ???

**Comment by r8d8** [comment]
Do your 30303 port is opened?

**Comment by whilei** [comment]
I have seen "errors" like this logged before, though they've never actually correlated with or predicted a failing network connection... maybe an issue with either logging timing/verbosity, or error expecting or handling?

**Comment by liyanhrxy** [comment]
yes, i sure the port 30303 is oppened !! And it seem to be working ,but the errors made me feeling bad?? i don't konw where is going wrong ?? the geth(ETH) client works well in the same environment .of course ,i 
never starting them together!!!

**Comment by whilei** [comment]
I would categorize this as a logging misinformation issue, thanks for reporting it @liyanhrxy .

**Comment by liyanhrxy** [comment]
Can I  use the ETH client instead of ETC client to sync the ETC blockchain ???

**Comment by liyanhrxy** [comment]
I find that in the ETC's main page ,the link of parity client is unavailable. Is that mean the new parity client would  not support  the ETC blockchain anymore ???

**Comment by whilei** [comment]
You can use Parity for ETC:
- https://wiki.parity.io/Chain-specification#chain-presets-available
-

**Comment by liyanhrxy** [comment]
Thank you so much !!!!!!!!
