### ISSUE TITLE
Client node keeping generate new block when issue no transaction, is this right?

### ISSUE THREAD

**Issue by code-brewer** [ethereumproject/go-ethereum#588]
My Private Chain was settup as follow steps:

1) I create genesis.json adopting PoW using puppeth and then add some my own account, finall got genesis as bellow:

{
  "config": {
    "chainId": 7654,
    "homesteadBlock": 1,
    "eip150Block": 2,
    "eip150Hash": "0x0000000000000000000000000000000000000000000000000000000000000000",
    "eip155Block": 3,
    "eip158Block": 3,
    "byzantiumBlock": 4,
    "ethash": {}
  },
  "nonce": "0x0",
  "timestamp": "0x5af2bde9",
  "extraData": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "gasLimit": "0x47b760",
  "difficulty": "0x1",
  "mixHash": "0x0000000000000000000000000000000000000000000000000000000000000000",
  "coinbase": "0x0000000000000000000000000000000000000000",
  "alloc": {
    "0000000000000000000000000000000000000000": {
      "balance": "0x1"
    },
    "0000000000000000000000000000000000000001": {
      "balance": "0x1"
    },
        
        ...

    "00000000000000000000000000000000000000fe": {
      "balance": "0x1"
    },
    "00000000000000000000000000000000000000ff": {
      "balance": "0x1"
    },
            "9e417a4d723849d56784e7709023a1f737d60017":{"balance": "0x200000000000000000000000000000000000000000000000000000000000000"},
        "8c99950df5960e5459c854fa3841e0717a68bb54":{"balance": "0x200000000000000000000000000000000000000000000000000000000000000"}
  },
  "number": "0x0",
  "gasUsed": "0x0",
  "parentHash": "0x0000000000000000000000000000000000000000000000000000000000000000"
}

2) Then,  i setup private chain using bootnode mechanism. 

3)  start up first-node and connect to it, i saw repeating mining and new block created message:

 ./go-ethereum/build/bin/geth  --datadir ./ethereum/go-ethereum/xyz_datadir/01  --ethash.dagdir ./ethereum/go-ethereum/xyz_datadir/01 --syncmode full --gasprice 1   --unlock 0x8c99950df5960e5459c854fa3841e0717a68bb54 --password . /ethereum/go-ethereum/xyz_datadir/01/password.txt   --networkid 7654 --ipcpath=/tmp/geth//01/geth.ipc --port 61901 --rpc --rpccorsdomain '*' --rpcaddr 192.168.1.26 --rpcport 8101  --rpcapi 'admin,db,eth,debug,miner,net,shh,txpool,personal,web3' --bootnodes enode://713cf7befdab937e196abadde115362280b7b2ca6e148d0bc632cf6659c0ebb50db38e51e5ca8be0e8f38ef24d061f1ec8ed6c79b78fc2bbe050f84553d8349d@192.168.1.26:30301  --mine console
INFO [05-09|17:52:59] Maximum peer count                       ETH=25 LES=0 total=25
INFO [05-09|17:52:59] Starting peer-to-peer node               instance=Geth/v1.8.7-unstable-86be91b3/darwin-amd64/go1.9.3
INFO [05-09|17:52:59] Allocated cache and file handles         database=~/Programming/Work/ethereum/go-ethereum/xyz_datadir/01/geth/chaindata cache=768 handles=1024
WARN [05-09|17:52:59] Upgrading database to use lookup entries
INFO [05-09|17:52:59] Initialised chain configuration          config="{ChainID: 7654 Homestead: 1 DAO: <nil> DAOSupport: false EIP150: 2 EIP155: 3 EIP158: 3 Byzantium: 4 Constantinople: <nil> Engine: ethash}"
INFO [05-09|17:52:59] Disk storage enabled for ethash caches   dir=~/Programming/Work/ethereum/go-ethereum/xyz_datadir/01/geth/ethash count=3
INFO [05-09|17:52:59] Disk storage enabled for ethash DAGs     dir=~/Programming/Work/ethereum/go-ethereum/xyz_datadir/01             count=2
INFO [05-09|17:52:59] Initialising Ethereum protocol           versions="[63 62]" network=7654
INFO [05-09|17:52:59] Database deduplication successful        deduped=0
INFO [05-09|17:52:59] Loaded most recent local header          number=0 hash=d9a673…bf0bf5 td=1
INFO [05-09|17:52:59] Loaded most recent local full block      number=0 hash=d9a673…bf0bf5 td=1
INFO [05-09|17:52:59] Loaded most recent local fast block      number=0 hash=d9a673…bf0bf5 td=1
INFO [05-09|17:52:59] Regenerated local transaction journal    transactions=0 accounts=0
INFO [05-09|17:52:59] Starting P2P networking
INFO [05-09|17:53:02] UDP listener up                          self=enode://ff7ac1bc60ea52d197d61d56066ae68a04a3737943e84b2ad69de8eb8ebe9359babbfd0ef069339582e9e6580f30aa05d431326039a36bfc1d3b2a9d10666038@[::]:61901
INFO [05-09|17:53:02] RLPx listener up                         self=enode://ff7ac1bc60ea52d197d61d56066ae68a04a3737943e84b2ad69de8eb8ebe9359babbfd0ef069339582e9e6580f30aa05d431326039a36bfc1d3b2a9d10666038@[::]:61901
INFO [05-09|17:53:02] IPC endpoint opened                      url=/tmp/geth/01/geth.ipc
INFO [05-09|17:53:02] HTTP endpoint opened                     url=http://192.168.1.26:8101 cors='*' vhosts=localhost
INFO [05-09|17:53:02] Unlocked account                         address=0x8c99950dF5960E5459c854fA3841e0717a68Bb54
INFO [05-09|17:53:02] Transaction pool price threshold updated price=1
INFO [05-09|17:53:02] Etherbase automatically configured       address=0x8c99950dF5960E5459c854fA3841e0717a68Bb54
INFO [05-09|17:53:02] Starting mining operation
INFO [05-09|17:53:02] Commit new mining work                   number=1 txs=0 uncles=0 elapsed=174.602µs
Welcome to the Geth JavaScript console!

instance: Geth/v1.8.7-unstable-86be91b3/darwin-amd64/go1.9.3
coinbase: 0x8c99950df5960e5459c854fa3841e0717a68bb54
at block: 0 (Wed, 09 May 2018 17:22:49 CST)
 datadir: ~/Programming/Work/ethereum/go-ethereum/xyz_datadir/01
 modules: admin:1.0 debug:1.0 eth:1.0 miner:1.0 net:1.0 personal:1.0 rpc:1.0 txpool:1.0 web3:1.0

 INFO [05-09|17:53:04] Generating DAG in progress               epoch=0 percentage=0 elapsed=478.286ms
INFO [05-09|17:53:05] Generating DAG in progress               epoch=0 percentage=1 elapsed=957.876ms
INFO [05-09|17:53:05] Generating DAG in progress               epoch=0 percentage=2 elapsed=1.456s
        ...

INFO [05-09|17:53:53] Generating DAG in progress               epoch=0 percentage=98 elapsed=49.373s
INFO [05-09|17:53:54] Generating DAG in progress               epoch=0 percentage=99 elapsed=50.226s
INFO [05-09|17:53:54] Generated ethash verification cache      epoch=0 elapsed=50.228s
INFO [05-09|17:53:57] Successfully sealed new block            number=1 hash=b9cb83…61ac74
INFO [05-09|17:53:57] 🔨 mined potential block                  number=1 hash=b9cb83…61ac74
INFO [05-09|17:53:57] Commit new mining work                   number=2 txs=0 uncles=0 elapsed=372.213µs
INFO [05-09|17:53:57] Successfully sealed new block            number=2 hash=8679d7…a928d8
INFO [05-09|17:53:57] 🔨 mined potential block                  number=2 hash=8679d7…a928d8
INFO [05-09|17:53:57] Commit new mining work                   number=3 txs=0 uncles=0 elapsed=166.117µs
INFO [05-09|17:53:58] Successfully sealed new block            number=3 hash=9edbfc…ce2848
INFO [05-09|17:53:58] 🔨 mined potential block                  number=3 hash=9edbfc…ce2848
INFO [05-09|17:53:58] Commit new mining work                   number=4 txs=0 uncles=0 elapsed=133.898µs
INFO [05-09|17:53:58] Successfully sealed new block            number=4 hash=649918…47e8e7
INFO [05-09|17:53:58] 🔨 mined potential block                  number=4 hash=649918…47e8e7
INFO [05-09|17:53:58] Mining too far in the future             wait=2s
         ...
```
INFO [05-09|17:54:26] 🔗 block reached canonical chain          number=17 hash=eaa5a9…6db05b
INFO [05-09|17:54:26] 🔨 mined potential block                  number=22 hash=4e52eb…b10bf3
INFO [05-09|17:54:26] Commit new mining work                   number=23 txs=0 uncles=0 elapsed=132.578µs
INFO [05-09|17:54:26] Generating DAG in progress               epoch=1 percentage=29 elapsed=28.544s
INFO [05-09|17:54:27] Successfully sealed new block            number=23 hash=661548…6374c8
```
         ...  then following is repeating above  message  ... 

> eth.getBlock(0)
{
  difficulty: 1,
  extraData: "0x0000000000000000000000000000000000000000000000000000000000000000",
  gasLimit: 4700000,
  gasUsed: 0,
  hash: "0xd9a6737cba5463a85be80878cd72b49c5085ad090fee2da0360ed37d9fbf0bf5",
  logsBloom: "0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000",
  miner: "0x0000000000000000000000000000000000000000",
  mixHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  nonce: "0x0000000000000000",
  number: 0,
  parentHash: "0x0000000000000000000000000000000000000000000000000000000000000000",
  receiptsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  sha3Uncles: "0x1dcc4de8dec75d7aab85b567b6ccd41ad312451b948a7413f0a142fd40d49347",
  size: 540,
  stateRoot: "0x1d84e266f399f2ce27f430ddb5bdf825dc3bb74c239e8e3ffcf36c2cfab09461",
  timestamp: 1525857769,
  totalDifficulty: 1,
  transactions: [],
  transactionsRoot: "0x56e81f171bcc55a6ff8345e692c0f86e5b48e01b996cadc001622fb5e363b421",
  uncles: []
}

**Comment by code-brewer** [comment]
**Isn't it waste storage and network resource if allow mining out new block even there is no transaction ?**

**Comment by realcodywburns** [comment]
the short answer is yes, it is wasteful but necessary to maintain difficulty and blocktimes.

You're using the ethereum foundation version of geth, you can use clique PoA rather than PoW with it and make it more efficient.

**Comment by code-brewer** [comment]
@realcodywburns 

Thanks, i got it. 

So, my `issue` is really not a issue.  Will this post be remove or move to some other forum ?

**Comment by whilei** [comment]
Closing since answered and other geth.
