### ISSUE TITLE
etc main network not support eth_getLogs?

### ISSUE THREAD

**Issue by ghost** [ethereumproject/go-ethereum#639]
![image](https://user-images.githubusercontent.com/1717368/42091563-77e70e68-7bd8-11e8-8139-6709406b5297.png)

![image](https://user-images.githubusercontent.com/1717368/42091577-82c99116-7bd8-11e8-8461-5aa2b7def774.png)

really?

**Comment by yourihua** [comment]
and i change main network to epool.io from gastracker.io, it can be work.
why?
