### ISSUE TITLE
mainnet synchronisation problem

### ISSUE THREAD

**Issue by Geam** [ethereumproject/go-ethereum#642]
Hello, I'm running a `geth classic v5.4.1-a3d20f6` node on the ethereum classic mainnet and event though I start it with the `--fast` option the 2018-06-29 at noon it still haven't finish synchronisation. I've restart it earlier because I've made a mistake on the rpc configuration and it's still the same.

In fact, it seems like it's stuck because in a client attached when I run
```
> eth.syncing
{
  currentBlock: 6110214,
  highestBlock: 6111676,
  knownStates: 10177093,
  pulledStates: 10147484,
  startingBlock: 6104939
}
```
Only the knownStates & pulledStates get updated the other didn't change since a few hours ago. And on the terminal where the node is running, I've got
```
[...]
2018-07-03 17:45:45 Fast      #6110214 of  #6111676   99.98%          0/ 0 blk/mgas sec     24/25 peers
2018-07-03 17:46:46 Fast      #6110214 of  #6111676   99.98%          0/ 0 blk/mgas sec     24/25 peers
2018-07-03 17:47:45 Fast      #6110214 of  #6111676   99.98%          0/ 0 blk/mgas sec     24/25 peers
2018-07-03 17:48:45 Fast      #6110214 of  #6111676   99.98%          0/ 0 blk/mgas sec     24/25 peers
```
I run my node with
```
geth-etc-v5.4.1-a3d20f6 \
        --fast \
        --rpcaddr "127.0.0.1" \
        --rpcport "8545" \
        --rpc \
        --rpcapi "db,eth,net,web3" \
        --nat=none \
        --cache=2054
```
It is an expected behavior or did a miss something ?

Any help would be appreciated though I don't know if this is the best place to ask.

EDIT : between the moment I wrote the message (one hour ago on reddit) and now, it has progress a little but it show the same behavior but on block 6111518.

**Comment by splix** [comment]
@Geam please try version v5.4.3

**Comment by Geam** [comment]
Hello,
So this morning I've checked and it seems that it has finished syncing on `v5.4.1`, it just take a really long time. I don't really now when it get unstuck but the fast sync had take me ~4 days and half.
@splix I've updated but as the sync has finish prior to updating I can't tell if it change something.
Sorry for the unneeded noise on this repo issues and thanks for the reply
