### ISSUE TITLE
Geth eth_syncing not working

### ISSUE THREAD

**Issue by ymatagne** [ethereumproject/go-ethereum#646]
Hello,

I've small problem with my geth client : eth_syncing not working :

journalctl -xf -u getc.service 
-- Logs begin at Wed 2018-07-11 14:14:37 UTC. --
Jul 11 15:13:37 ip-10-50-0-175 geth[2543]: 2018-07-11 15:13:37 Import    #6161312              431bdfdb          0/ 0 txs/mgas          1/25 peers
Jul 11 15:13:42 ip-10-50-0-175 geth[2543]: 2018-07-11 15:13:42 Import    #6161313              75e126b2          1/ 0 txs/mgas          1/25 peers
Jul 11 15:13:47 ip-10-50-0-175 geth[2543]: 2018-07-11 15:13:47 Import    #6161314              bfffe037          1/ 0 txs/mgas          1/25 peers
Jul 11 15:14:05 ip-10-50-0-175 geth[2543]: 2018-07-11 15:14:05 Import    #6161315              b2bd5c94          0/ 0 txs/mgas          1/25 peers
Jul 11 15:14:11 ip-10-50-0-175 geth[2543]: 2018-07-11 15:14:11 Import    #6161316              1cfa0638         18/ 0 txs/mgas          1/25 peers
Jul 11 15:14:14 ip-10-50-0-175 geth[2543]: 2018-07-11 15:14:14 Import    #6161317              bf7fae37          2/ 0 txs/mgas          1/25 peers
**Jul 11 15:16:14 ip-10-50-0-175 geth[2543]: 2018-07-11 15:16:14 Sync      #6161317              bf7fae37     0/   0/ 0 blk/txs/mgas sec  5/25 peers
Jul 11 15:17:14 ip-10-50-0-175 geth[2543]: 2018-07-11 15:17:14 Sync      #6161317              bf7fae37     0/   0/ 0 blk/txs/mgas sec  6/25 peers
Jul 11 15:18:14 ip-10-50-0-175 geth[2543]: 2018-07-11 15:18:14 Sync      #6161317              bf7fae37     0/   0/ 0 blk/txs/mgas sec  5/25 peers
Jul 11 15:19:14 ip-10-50-0-175 geth[2543]: 2018-07-11 15:19:14 Sync      #6161317              bf7fae37     0/   0/ 0 blk/txs/mgas sec  3/25 peers**

curl -s --data '{"method":"eth_syncing","params":[],"id":1,"jsonrpc":"2.0"}' -H "Content-Type: application/json" -X POST localhost:8545
**{"jsonrpc":"2.0","id":1,"result":false}**

curl https://api.gastracker.io/v1/blocks/latest
{"offset":0,"items":[{"height":**6161369**,"hash":"0x9e1e49bb91d3cd7a11138d29cc6e4b16e0758a2cc9f3ffda8b0b4d48eb0c3482","timestamp":"2018-07-11T15:30:02","miningTime":1,"transactions":4,"value":{"hex":"0x985dbff4638f3235","wei":"10979142522962391605","ether":10.9791},"gasMega":0.0840,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"},{"height":6161368,"hash":"0x3104b66a17e5e2503e4937fbdcc191d933e161f8b8f466fee70a1b7b8c84d0cd","timestamp":"2018-07-11T15:30:01","miningTime":1,"transactions":0,"value":{"hex":"0x0","wei":"0","ether":0.0},"gasMega":0.0000,"miner":"0xc91716199ccDe49dC4fAFaeB68925127AC80443f"},{"height":6161367,"hash":"0x747ba5305212efceba076eaef408b8fe9de9035618fc5ce7d67771adccf5655c","timestamp":"2018-07-11T15:30:00","miningTime":3,"transactions":1,"value":{"hex":"0x17cb6f19dbf9000","wei":"107161640000000000","ether":0.1072},"gasMega":0.0211,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"},{"height":6161366,"hash":"0xb9245b2307159530cb33bf1084c7b4c8da020445c3c6edb7885eb815449956c3","timestamp":"2018-07-11T15:29:57","miningTime":8,"transactions":1,"value":{"hex":"0xd534a8e295fc00","wei":"60012070000000000","ether":0.06},"gasMega":0.0210,"miner":"0xf35074bbD0a9AEE46F4Ea137971FEEC024Ab704e"},{"height":6161365,"hash":"0x8b2cd8cf8680a7e2622c2927c15b2f38e2395130b06ed582e5a475573a3c2610","timestamp":"2018-07-11T15:29:49","miningTime":22,"transactions":4,"value":{"hex":"0xa7a4c312904db6a79e","wei":"3092478613763162285982","ether":3092.4786},"gasMega":0.0841,"miner":"0xDf7D7e053933b5cC24372f878c90E62dADAD5d42"},{"height":6161364,"hash":"0x3ea29ffcf0e995c1843590085eb7eff4dbdffb7fc579f03c16cd571568f5e3a6","timestamp":"2018-07-11T15:29:27","miningTime":10,"transactions":3,"value":{"hex":"0x54a62420bf581d71","wei":"6099602468387691889","ether":6.0996},"gasMega":0.0631,"miner":"0x30bA093403Cbcef743868B8ae9046ed2eA29a233"},{"height":6161363,"hash":"0xdc01cbd83bfd011b739d079307ed85a315d611fe6c3e0d4e4a50c001d8992f5b","timestamp":"2018-07-11T15:29:17","miningTime":21,"transactions":0,"value":{"hex":"0x0","wei":"0","ether":0.0},"gasMega":0.0000,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"},{"height":6161362,"hash":"0xf162678779d016dea0b678ab1eb880ccaaf5c98abd7cdb61dcc4f730ccf45c76","timestamp":"2018-07-11T15:28:56","miningTime":6,"transactions":36,"value":{"hex":"0xabdb2cc54c1e50074a","wei":"3170186451528331560778","ether":3170.1865},"gasMega":0.7788,"miner":"0x004730417CD2B1D19f6bE2679906dEd4fA8A64e2"},{"height":6161361,"hash":"0xf2747e4ea956aaa994897e32768fd44f860f922ed6783a380e651b04da5fe849","timestamp":"2018-07-11T15:28:50","miningTime":8,"transactions":2,"value":{"hex":"0x379c993baac42400","wei":"4007246250000000000","ether":4.0072},"gasMega":0.0421,"miner":"0xDf7D7e053933b5cC24372f878c90E62dADAD5d42"},{"height":6161360,"hash":"0x86449c3c1724658a1feacd08fcdfac5bc60e116a74c0f9650bade1d94cef6a91","timestamp":"2018-07-11T15:28:42","miningTime":36,"transactions":6,"value":{"hex":"0x40591597144c48f80","wei":"74188176479670800256","ether":74.1882},"gasMega":0.1262,"miner":"0xDf7D7e053933b5cC24372f878c90E62dADAD5d42"},{"height":6161359,"hash":"0x1fa388161a8dcb3b6cb316ce7f3126c96b71d02ce643eadffe09b75bba6a2639","timestamp":"2018-07-11T15:28:06","miningTime":7,"transactions":0,"value":{"hex":"0x0","wei":"0","ether":0.0},"gasMega":0.0000,"miner":"0x1C0FA194a9d3B44313DCD849F3C6be6Ad270a0A4"},{"height":6161358,"hash":"0x9ee1f5df9cfa33c97778c1631e641f6ba4c35febf4a0883394af8049fa459fcd","timestamp":"2018-07-11T15:27:59","miningTime":13,"transactions":2,"value":{"hex":"0x7c5c05939646d400","wei":"8961043490000000000","ether":8.961},"gasMega":0.0421,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"},{"height":6161357,"hash":"0x5a1c94188807184e9569f586d5ae94b065ddd34651af8091f7938fde9aeabfdc","timestamp":"2018-07-11T15:27:46","miningTime":7,"transactions":9,"value":{"hex":"0x4d5757e7b37d2266","wei":"5573019716554662502","ether":5.573},"gasMega":0.2346,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"},{"height":6161356,"hash":"0xcea8c02012fb299ba825ecfba13f7df9419bf5efa1d2a44f7dede3aecce54f34","timestamp":"2018-07-11T15:27:39","miningTime":13,"transactions":0,"value":{"hex":"0x0","wei":"0","ether":0.0},"gasMega":0.0000,"miner":"0xc91716199ccDe49dC4fAFaeB68925127AC80443f"},{"height":6161355,"hash":"0x53ae45f6e08f1b0d0f31cfda03c813f7dd73795c3740cad71f8c7f13cf393d0c","timestamp":"2018-07-11T15:27:26","miningTime":9,"transactions":5,"value":{"hex":"0x1a466540b937c72800","wei":"484687877636000000000","ether":484.6879},"gasMega":0.1620,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"},{"height":6161354,"hash":"0x7fdbec4587682a9ea19fe4dc98b28b5de84564c95dbbc855e1351c1683dcef7b","timestamp":"2018-07-11T15:27:17","miningTime":14,"transactions":0,"value":{"hex":"0x0","wei":"0","ether":0.0},"gasMega":0.0000,"miner":"0x919973EB38844313Dc31c41e140700d6e333F8D5"},{"height":6161353,"hash":"0x8666faf769b2a947177a37fdd8b1e3b05c057f53860e6ed9028f47bdce85c632","timestamp":"2018-07-11T15:27:03","miningTime":42,"transactions":19,"value":{"hex":"0x4257f050e313298200","wei":"1223821762476749980160","ether":1223.8218},"gasMega":0.5376,"miner":"0xf35074bbD0a9AEE46F4Ea137971FEEC024Ab704e"},{"height":6161352,"hash":"0xa8ca3ed277f3ca58ca9d94ee90ad4533de881b6fae0941553c80d7521f6687db","timestamp":"2018-07-11T15:26:21","miningTime":15,"transactions":0,"value":{"hex":"0x0","wei":"0","ether":0.0},"gasMega":0.0000,"miner":"0x24eEcCF68b9772d60f2b5acaBe6bb4C3221C302B"},{"height":6161351,"hash":"0x35cc3b62e44c241fb3f62751a6d7b5b5516ba568d6137727b79d6741c034e6c2","timestamp":"2018-07-11T15:26:06","miningTime":7,"transactions":1,"value":{"hex":"0xde5e63a3f0b4c00","wei":"1001459630000000000","ether":1.0015},"gasMega":0.0211,"miner":"0xDf7D7e053933b5cC24372f878c90E62dADAD5d42"},{"height":6161350,"hash":"0xa697aa3a8c2ca0706a80bdf9edde3d1e78b1c25209d865f85e7c1fe85560ba9c","timestamp":"2018-07-11T15:25:59","miningTime":23,"transactions":6,"value":{"hex":"0x5abc744c6236e4be00","wei":"1673786529395000000000","ether":1673.7865},"gasMega":0.1262,"miner":"0x9EAb4b0fC468A7f5D46228bf5a76cB52370d068D"}]}

I'm running this command : 
`
/usr/bin/geth --rpc --rpcaddr 0.0.0.0 --rpcport 8545 --port 30303 --cache 1024 --ipcdisable
`

Do you know what's happening ?

Have a good day,

**Comment by whilei** [comment]
Please can you share the output of `geth version`? If not at latest (v5.4.3) I recommend updating to that. If that doesn't help, attaching the correlated debug logs (by timestamp) from `~/.ethereum-classic/mainnet/logs/` will be helpful, too.

It seems like you may have something strange happening with your peers...

**Comment by ymatagne** [comment]
Hello,
Sure, this is the latest version :
geth version
Geth
Version: v5.4.3-5291a28
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.7
Go OS: linux
Go Arch: amd64
Machine ID: 31356a3a
GOPATH=
GOROOT=/usr/local/go

**Comment by ymatagne** [comment]
Sorry, for the log, i m waiting to reproduce the problem. Because if I restart geth, it's work after.

On the mainnet/log/geth.WARNING : 
Log file created at: 2018/07/17 12:00:13
Running on machine: ip-10-50-0-202
Binary: Built with gc go1.9.6 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0717 12:00:13.210422 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:00:13.214824 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:15:13.211072 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:15:13.214936 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:30:13.211212 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:30:13.215054 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered


cat mainnet/log/geth.ip-10-50-0-202.admin.log.ERROR.20180717-120013.2477
Log file created at: 2018/07/17 12:00:13
Running on machine: ip-10-50-0-202
Binary: Built with gc go1.9.6 for linux/amd64
Log line format: [IWEF]mmdd hh:mm:ss.uuuuuu threadid file:line] msg
E0717 12:00:13.210422 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:00:13.214824 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:15:13.211072 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:15:13.214936 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:30:13.211212 p2p/nat/nat.go:114] Network port udp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
E0717 12:30:13.215054 p2p/nat/nat.go:114] Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered


cat mainnet/log/geth.ip-10-50-0-202.admin.log.INFO.20180717-120000.2477
I0717 12:36:30.048305 eth/api.go:1155] receipt not found for transaction 0x2f2ed87838191eca26215c9a5725b3c42e803f11db0c3ab8e2379761b4a9ff88
I0717 12:36:30.072421 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:30.093089 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:30.107988 eth/api.go:1155] receipt not found for transaction 0x2f2ed87838191eca26215c9a5725b3c42e803f11db0c3ab8e2379761b4a9ff88
I0717 12:36:30.132119 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:30.152753 eth/api.go:1155] receipt not found for transaction 0xb686d42438e25f02d3eebb71a5c7d47f3ca746cf45f5b1c4264a29da77483777
I0717 12:36:30.171249 eth/api.go:1155] receipt not found for transaction 0xe23d4157201bad9f25dd80657a683dfd0d5b351b43b70b2ee435fc1f213040bf
I0717 12:36:30.193014 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:30.210764 eth/api.go:1155] receipt not found for transaction 0xe23d4157201bad9f25dd80657a683dfd0d5b351b43b70b2ee435fc1f213040bf
I0717 12:36:30.239385 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:30.261746 eth/api.go:1155] receipt not found for transaction 0xb686d42438e25f02d3eebb71a5c7d47f3ca746cf45f5b1c4264a29da77483777
I0717 12:36:30.276283 eth/api.go:1155] receipt not found for transaction 0x2f2ed87838191eca26215c9a5725b3c42e803f11db0c3ab8e2379761b4a9ff88
I0717 12:36:30.303894 eth/api.go:1155] receipt not found for transaction 0x128af85b12f284dca2940c11eafbc1d492f3f8b83ec4b567225ab769feea3260
I0717 12:36:30.567539 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:31.818694 eth/peer.go:241] Peer 8924f6e91a89e442 [eth/63] fetching 2 block bodies first=0x182801317c02d1c5b8c35f488fceb990fc4437b071c3b01cb075f4b170957899
I0717 12:36:32.567642 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:34.233438 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:34.567747 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:35.915375 eth/api.go:1155] receipt not found for transaction 0x703004d292f8363aca174848c76fd51e89c7052b7c0ec57b3347739be484623f
I0717 12:36:35.940753 eth/api.go:1155] receipt not found for transaction 0x4da040edd26b6fc0422a015a0e179aa68c49f62610f348f34cf320a02e0f12ee
I0717 12:36:35.968284 eth/api.go:1155] receipt not found for transaction 0xe3f1f79eb488c2c5d1fc21b61e2236e18c7cd1ce03fd3627d0854ab1700aefa7
I0717 12:36:36.006777 eth/api.go:1155] receipt not found for transaction 0x4620aff0015f5fb303aab91c09ca2e422becb7b846f1cbc8535adfbf010e0cd4
I0717 12:36:36.034334 eth/api.go:1155] receipt not found for transaction 0x5f4ea9dff91e2e29e893ad941efc258ec76bb88b39994eaca6689d05b96942b8
I0717 12:36:36.059114 eth/api.go:1155] receipt not found for transaction 0x5a31965f3ada6351142585065793d79c8dd35826b2f2740ba8280373ed3c93c6
I0717 12:36:36.567851 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:37.918703 eth/peer.go:241] Peer f9002fa167647e0e [eth/63] fetching 2 block bodies first=0x182801317c02d1c5b8c35f488fceb990fc4437b071c3b01cb075f4b170957899
I0717 12:36:38.567956 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:40.327655 eth/api.go:1155] receipt not found for transaction 0xe553840ca0d6bce1f6d1b08c3556dcf20ff0512a0156acd3d14541d228310a55
I0717 12:36:40.370818 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:40.388197 eth/api.go:1155] receipt not found for transaction 0xe553840ca0d6bce1f6d1b08c3556dcf20ff0512a0156acd3d14541d228310a55
I0717 12:36:40.409411 eth/api.go:1155] receipt not found for transaction 0xb686d42438e25f02d3eebb71a5c7d47f3ca746cf45f5b1c4264a29da77483777
I0717 12:36:40.435886 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:40.462423 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:40.568061 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:42.568165 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:44.018690 eth/peer.go:241] Peer 3f4991b53e0116a8 [eth/63] fetching 2 block bodies first=0x182801317c02d1c5b8c35f488fceb990fc4437b071c3b01cb075f4b170957899
I0717 12:36:44.266424 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:44.300540 eth/api.go:1155] receipt not found for transaction 0xe23d4157201bad9f25dd80657a683dfd0d5b351b43b70b2ee435fc1f213040bf
I0717 12:36:44.333212 eth/api.go:1155] receipt not found for transaction 0xe23d4157201bad9f25dd80657a683dfd0d5b351b43b70b2ee435fc1f213040bf
I0717 12:36:44.362145 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:44.379379 eth/api.go:1155] receipt not found for transaction 0x2f2ed87838191eca26215c9a5725b3c42e803f11db0c3ab8e2379761b4a9ff88
I0717 12:36:44.414161 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:44.439609 eth/api.go:1155] receipt not found for transaction 0xb686d42438e25f02d3eebb71a5c7d47f3ca746cf45f5b1c4264a29da77483777
I0717 12:36:44.464555 eth/api.go:1155] receipt not found for transaction 0xb686d42438e25f02d3eebb71a5c7d47f3ca746cf45f5b1c4264a29da77483777
I0717 12:36:44.489143 eth/api.go:1155] receipt not found for transaction 0xf80c8b5799d288170233b0c327aa77f3306440cf8ea5ad19155f1bdae6f5704f
I0717 12:36:44.508086 eth/api.go:1155] receipt not found for transaction 0xe23d4157201bad9f25dd80657a683dfd0d5b351b43b70b2ee435fc1f213040bf
I0717 12:36:44.543560 eth/api.go:1155] receipt not found for transaction 0x61885585a6890a99e0644f2ad1a44b0d01887ca06fc79ee34a2b1796c36b185d
I0717 12:36:44.568281 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s
I0717 12:36:46.124311 eth/api.go:1155] receipt not found for transaction 0x5a31965f3ada6351142585065793d79c8dd35826b2f2740ba8280373ed3c93c6
I0717 12:36:46.139714 eth/api.go:1155] receipt not found for transaction 0x4620aff0015f5fb303aab91c09ca2e422becb7b846f1cbc8535adfbf010e0cd4
I0717 12:36:46.177371 eth/api.go:1155] receipt not found for transaction 0x0bc8efa0ed2352d958d73b61cf82b3849bb51ce9d1c6e56ae903aafa597797e2
I0717 12:36:46.568411 eth/downloader/downloader.go:1603] Quality of service: rtt 2s, conf 1.000, ttl 6.000006s

**Comment by Frankenmine** [comment]
Try this - http://coinregister.co.uk/beginners-mining-guide/geth-emerald-wallet-etc-guide/

**Comment by lostinblue** [comment]
Try again with my newest build. I'm getting this geth back to not just usable but better coded than the original before I move into my next project. Partial favor to a friend who helped me too.
