### ISSUE TITLE
Txpool is constantly growing

### ISSUE THREAD

**Issue by korjavin** [ethereumproject/go-ethereum#649]
## System information

Linux

Commit tag v5.4.3

## Expected behavior

txpool should be in some limits
## Actual behavior

txpool is growing up until node restarted

## Steps to reproduce the behaviour

Start, wait, check txpool.status

![image](https://user-images.githubusercontent.com/148765/42761832-f5a4886a-890e-11e8-85c4-b3be92be17a2.png)

**Comment by tzdybal** [comment]
@korjavin are you plotting `pending` or `queued` transactions from `txpool.status`?

**Comment by korjavin** [comment]
It's the sum of pending+queued

**Comment by tzdybal** [comment]
Results of overnight experimentation:
![txpool](https://user-images.githubusercontent.com/1138893/43003027-4004ad12-8c2b-11e8-9c21-b19955ac74eb.png)

**Comment by korjavin** [comment]
@tzdybal are you sure you not messed queued/pending?
And what is the x-axis?

**Comment by tzdybal** [comment]
@korjavin yes, you're right - labels are messed.

X axis is time, 1 unit corresponds to 10 or 15 seconds.

**Comment by tzdybal** [comment]
Resolved with #652 .

**Comment by tzdybal** [comment]
Closed to fast - changes are not merged yet.
