### ISSUE TITLE
Configure chains from command line

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#65]
Provide a special command line option to select chain to follow (existing ETH, ETC, testnet or a custom private chain)
- [ ] named configs
- [ ] testnet config
- [ ] select chain from command line option
- [ ] own subdir for each chain (./chaindata -> ./chaindata-classic, ./testnet -> ./chaindata-testnet, and so on) - #100 
- [ ] read chain config from external JSON file - #131

**Comment by pascaldekloe** [comment]
https://github.com/ethereum/wiki/wiki/Ethereum-Chain-Spec-Format

**Comment by splix** [comment]
Ethereum-Chain-Spec-Format isn't really good representation, especially if you have protocol upgrades on the chain

**Comment by splix** [comment]
Proposed format #131 (but in json)

**Comment by whilei** [comment]
Closing via #189.
