### ISSUE TITLE
Syncing issues -  0/   0/ 0 blk/txs/mgas sec  3/25 peers

### ISSUE THREAD

**Issue by Frankenmine** [ethereumproject/go-ethereum#651]
I am launching `geth` from cmd using batch file `\Desktop\geth.exe --datadir B:\Ethereum_Classic_Node --rpc --cache=2048` 

At first it is fine connecting to 8/25 peers max at any one time. This continues until around block #1,900,000 where it starts dropping peers and slowing down. Eventually it drops to 1/25 peers and stays there sometimes freezing completely forcing me to use `ctrl+c` to restart. 

On restarting the sync continues very slowly and it displays `Sync      #2422840 of  #6211256 4c92d360     0/   0/ 0 blk/txs/mgas sec  1/25 peers` and sometimes `Sync      #2422848 of  #6211256 c25b073c     0/   1/ 0 blk/txs/mgas sec  1/25 peers`

I'm doubting it will be possible to complete a full sync at this speed, am I doing something wrong? 

cmd display after `ctrl+c` restart.
![geth](https://user-images.githubusercontent.com/41147764/42967793-43add62e-8b99-11e8-8119-ba4a86a61676.jpg)

**Comment by tzdybal** [comment]
Could you please attach logs from `B:\Ethereum_Classic_Node\mainnet\log`?

**Comment by Frankenmine** [comment]
V5.4.3-5291a28 is what I am running. How do I attach logs just upload .gz file? I cannot open logs once unzipped

**Comment by splix** [comment]
JFYI, period between 2,400,000 to 2,500,000 was affected by a DoS attack on Ethereum. This range contains very heavy transactions, and it consumes a lot of resources to process and it usually takes several days just for that range

**Comment by Frankenmine** [comment]
Thanks for the info, is it normal within this range to be receiving 0/ 0/ 0 blk/txs/mgas? I have since decreased max peers to 15 which seems to help with keeping the ones I can connect to connected.

Also as I said previously Geth seems more often than not to connect to the eth blockchain (6,006,931) instead of the etc one (6,224,620), any ideas on this?

**Comment by tzdybal** [comment]
I would try to increase max peers to something between 50 and 100.

ETH and ETC use the same network, there are more ETH nodes than ETC nodes, so there's greater chance to connect to ETH node (this is my guess).

**Comment by Frankenmine** [comment]
Have tried increasing and decreasing max peers between 5 and 105 in increments of 10 but still always low 4 max. It is working, just passed diehard yesterday and not receiving 0/ 0/ 0 since clearing the DAO hard fork.

Still looking for an answer about the failed proto - too many peers warning logs.

Thanks.

**Comment by tzdybal** [comment]
I think that for some reasons you're only able to connect to very limited number of servers (because of firewall somewhere in the network, etc). And the ones you can connect to are busy and reject connections - that's why you get the "Too many peers" response. I saw the same error in the past, but for testnet.

**Comment by Frankenmine** [comment]
Got it sorted, woohoo! Thanks guys. 

I had created geth.exe TCP and UDP rules for any port and also rules for port 30303 specifically
