### ISSUE TITLE
geth personal.sendTransaction not working

### ISSUE THREAD

**Issue by blockplus** [ethereumproject/go-ethereum#656]
Here is my try on geth(testnet):
> personal.sendTransaction({"from":"0xf2deaac3a210440401952f28697613e254a4e4cd","to":"0xb558b8f98955897c1bd81f606eea3d34b81b6c4c","gas":"0x5208","gasPrice":"0x5f5e100","value":"0x8ac7211b9826f800"}, "passphrase")
"0xb959c08f36a84e6693e3df2a1f3bb0b39f769fe18e9726c72d3aa08b8f9dfbf8"

I got the tx hash, **0xb959c08f36a84e6693e3df2a1f3bb0b39f769fe18e9726c72d3aa08b8f9dfbf8**, and did try to confirm the tx.
> debug.traceTransaction("0xb959c08f36a84e6693e3df2a1f3bb0b39f769fe18e9726c72d3aa08b8f9dfbf8")
Error: tx 'b959c08f36a84e6693e3df2a1f3bb0b39f769fe18e9726c72d3aa08b8f9dfbf8' not found
    at web3.js:3119:20
    at web3.js:6086:15
    at web3.js:5050:36
    at <anonymous>:1:1

As you can see, could not get the tx using **debug.traceTransaction**, http://mordenexplorer.ethertrack.io/err404/tx/0xb959c08f36a84e6693e3df2a1f3bb0b39f769fe18e9726c72d3aa08b8f9dfbf8 as well.

I would like to get the solution as soon as possible. Best

**Comment by tzdybal** [comment]
Have you tried to send the transaction again?

morden network has chain splits, so I guess that your transaction existed on one of competing chains, but better/longer chain was found, and your transaction is not a part of canonical chain right now.

I checked out my morden node, and I can't find your transaction.

**Comment by blockplus** [comment]
Great! It works now.
Thank you for your help.
