### ISSUE TITLE
How to create and signature a transaction manually like ethereum/go-ethereum

### ISSUE THREAD

**Issue by kazaff** [ethereumproject/go-ethereum#658]
Hi there~

In the project `go-ethereum`, you will find [the key method](https://github.com/ethereum/go-ethereum/blob/master/accounts/keystore/keystore.go#L301).
Base on this method, We can sign a tx and send it by `eth_sendRawTransaction` RPC.

But in our this project, how shall we do?
Or ONLY use [eth_sendtransaction](https://github.com/ethereumproject/go-ethereum/wiki/JSON-RPC#eth_sendtransaction)?

**Comment by splix** [comment]
There is `eth_sendRawTransaction` in ETC Geth as well.

For offline transactions it's recommended to use emerald-cli
- https://github.com/ETCDEVTeam/emerald-cli
- http://docs.etcdevteam.com/html/emerald-cli/usage-sign.html

**Comment by whilei** [comment]
Closing, as apparently resolved.
