### ISSUE TITLE
Unable To Find Morden Bootnodes

### ISSUE THREAD

**Issue by etscrivner** [ethereumproject/go-ethereum#672]
Hey all,

I have several Ethereum classic nodes that I would love to play around with on testnet. Unfortunately, it seems as though the current Morden bootnodes are either dead or not working as intended. My node essentially comes up and is unable to find any peers.

Are there any updated sets of bootnodes?

**Comment by tzdybal** [comment]
You can find some information about working morden nodes in following issues:
https://github.com/ethereumproject/volunteer/issues/20
https://github.com/ethereumproject/go-ethereum/issues/487
https://forum.ethereumclassic.org/t/bootnode-listing-testnet/176

You should be able to get few nodes - maybe you'll be able to connect to something useful. 

Right now, I'm not able to sync morden node. So I can't fully recommend my own node.

**Comment by etscrivner** [comment]
@tzdybal Thank you, appreciate the information. I've already tried most of the peers listed on these resources, and notice that the activity on them is 6+ months old. I too have not been able to connect to the testnet and am wondering if it is still running?

**Comment by tzdybal** [comment]
A little update from @ethernodeio:
```
US Mid West
"enode://4d43e17a4abea739ffa570c1baf49880f26026ea015d61d46afb5a50ca511c653bcdb44740a4c6b481f6c858c721ca9b6bb253a4f4dfca39ac55d6aec817defd@45.76.16.12:30303"

US East Coast
"enode://2c35e0566a964a271740fef9482ab4308c59a2cc7946b27dad13d2854136d096849ebe614f90e5253e1328de2062511bf20b87bf0b00b2451b3b863c83d5dfd0@149.28.50.115:30303"

US West Coast
"enode://91887d1ae35855e4802cd88af023f2da66c219d0cdd88f18abbc414934292c7ff7a346fc93a7ac99745a9e0655454018ada366dd69eecb2d29c0d567b642fd79@149.28.202.90:30303"
```

**Comment by Irvingyao** [comment]
Hi,

Could  anyone provide me an active morden peer?

Thanks!
