### ISSUE TITLE
How do I upgrade from old version to the latest version?

### ISSUE THREAD

**Issue by wannabit-jayb** [ethereumproject/go-ethereum#673]
How do I quickly upgrade from old version to the latest version?

My ethereum classic node stops after a while, so I debugged error log files and I found the below line.

```
Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
Network port tcp:30303 could not be mapped: no UPnP or NAT-PMP router discovered
...
```

After I search a bit on Google, I found [this #613 ](https://github.com/ethereumproject/go-ethereum/issues/613)

I `geth version` to look up what version I downloaded, but I can't seem to find it.

```
Geth
Version: source
Protocol Versions: [63 62]
Network Id: 1
Go Version: go1.9.4
Go OS: linux
Go Arch: amd64
Machine ID: xxxxxxxxx
GOPATH=
GOROOT=/usr/lib/go-1.9
```

When I installed this ethereum classic node, I built from source.

```
$ go get -v github.com/ethereumproject/go-ethereum/...`
$ go get -v github.com/ethereumproject/go-ethereum/...`
```

Is there another command for looking up what version of geth I have, and upgrade from it to the latest version?

**Comment by whilei** [comment]
To upgrade, you can pull latest `master` branch and rebuild from source:

```
$ cd $GOPATH/src/github.com/ethereumproject/go-ethereum
$ git pull origin master
$ make install_geth
```

Using the `make` command to do the build will set the `Version: xxx` value.

To see what geth source version you currently have, you can 

```
$ cd $GOPATH/src/github.com/ethereumproject/go-ethereum
$ git rev-parse HEAD
```

**Comment by whilei** [comment]
Closing, since I expect the above can resolve the issue.
