### ISSUE TITLE
AppVeyor use wrong version of sputnikvm-ffi

### ISSUE THREAD

**Issue by tzdybal** [ethereumproject/go-ethereum#675]
AppVeyor script checks out the latest sputnikvm-ffi version, instead of using the one from `vendor` directory.

**Comment by whilei** [comment]
This related to https://ci.appveyor.com/project/splix/go-ethereum/builds/19371856? @ #671

**Comment by tzdybal** [comment]
I found it while working in this, but it's not strictly related.
