### ISSUE TITLE
Incorrect img logo on Wiki/Home page

### ISSUE THREAD

**Issue by Lomey** [ethereumproject/go-ethereum#677]
Your logo image on Wiki/Home page is :
![image](https://user-images.githubusercontent.com/16382694/46794697-113c2700-cd51-11e8-9d5b-a7d81aa36518.png)
But Ethereum Classic logo is green. So it is a little bit confusing. Please change on Ethereum Classic green logo like this:
![image](https://user-images.githubusercontent.com/16382694/46794899-86a7f780-cd51-11e8-96a1-3888bebe6c01.png)

**Comment by whilei** [comment]
Fixed! https://github.com/ethereumproject/go-ethereum/wiki
