### ISSUE TITLE
how to connect and sync the data from

### ISSUE THREAD

**Issue by kazaff** [ethereumproject/go-ethereum#682]
How to connect and sync the data from etc main chain?

**Comment by kazaff** [comment]
I ran the geth, but I found it did not sync the data from etc main chain, not testnet either.

It seem that geth connect the eth chain.

What can I do?

**Comment by whilei** [comment]
Please share your logs if possible, relevant details of your client and runtime environment, eg.

```
$ geth version
$ uname -a
$ tail -n1000 $HOME/.ethereum-classic/mainnet/log/geth.INFO
```

and steps to reproduce.

**Comment by whilei** [comment]
Closing since too little information provided.
