### ISSUE TITLE
Not connected to Ethereum Classic main network. 

### ISSUE THREAD

**Issue by parkhanju** [ethereumproject/go-ethereum#690]
I downloaded geth-classic-linux-v5.5.2-be43774.zip.
When I run the geth node, it continues to connect to the Ethereum mainnet.

$ geth --cache=1024 --rpc --rpcaddr 127.0.0.1 --rpcport 8545 --rpcapi "eth,net,web3" console

INFO [11-23|14:21:32.910] Maximum peer count                       ETH=25 LES=0 total=25
INFO [11-23|14:21:32.911] Starting peer-to-peer node               instance=Geth/v1.8.18-stable-58632d44/linux-amd64/go1.10.4
INFO [11-23|14:21:32.911] Allocated cache and file handles         database=/home/coa/.ethereum/geth/chaindata cache=768 handles=512
INFO [11-23|14:21:33.050] Initialised chain configuration          config="{ChainID: 1 Homestead: 1150000 DAO: 1920000 DAOSupport: true EIP150: 2463000 EIP155: 2675000 EIP158: 2675000 Byzantium: 4370000 Constantinople: <nil> Engine: ethash}"
INFO [11-23|14:21:33.050] Disk storage enabled for ethash caches   dir=/home/coa/.ethereum/geth/ethash count=3
INFO [11-23|14:21:33.050] Disk storage enabled for ethash DAGs     dir=/home/coa/.ethash               count=2
INFO [11-23|14:21:33.050] Initialising Ethereum protocol           versions="[63 62]" network=1
INFO [11-23|14:21:33.051] Loaded most recent local header          number=0 hash=d4e567…cb8fa3 td=17179869184 age=49y7mo1w
INFO [11-23|14:21:33.051] Loaded most recent local full block      number=0 hash=d4e567…cb8fa3 td=17179869184 age=49y7mo1w
INFO [11-23|14:21:33.051] Loaded most recent local fast block      number=0 hash=d4e567…cb8fa3 td=17179869184 age=49y7mo1w
INFO [11-23|14:21:33.051] Loaded local transaction journal         transactions=0 dropped=0
INFO [11-23|14:21:33.052] Regenerated local transaction journal    transactions=0 accounts=0
INFO [11-23|14:21:33.228] New local node record                    seq=3 id=6865349bc17d814b ip=127.0.0.1 udp=30303 tcp=30303
INFO [11-23|14:21:33.229] Started P2P networking                   self=enode://ce0efb4e62ffca39bf40118c96154993c548585626a206d285f3f0fea160fae1545ae90d316bb4fd572e9f5265a7d9a5736b722d317b0bf2a3499a38a6b83a6a@127.0.0.1:30303
INFO [11-23|14:21:33.232] IPC endpoint opened                      url=/home/coa/.ethereum/geth.ipc
Welcome to the Geth JavaScript console!

How can I fix it?

**Comment by splix** [comment]
It doesn't look like Classic Geth output, are you sure you're running right binary?

**Comment by parkhanju** [comment]
Yes, 

I used the geth node in the geth-classic-linux-v5.5.2-be43774.zip folder.

**Comment by splix** [comment]
But it says `Geth/v1.8.18-stable-58632d44/linux-amd64/go1.10.4` and the output looks completely different
