### ISSUE TITLE
Release 5.5.2 missing separate signatures

### ISSUE THREAD

**Issue by petrkr** [ethereumproject/go-ethereum#694]
At new release 5.5.2 there are no separated signatures as been at 5.5.1, it makes more complicated script-based verify as you have to unpack signatures tar and look for right file -- basically it's not supported by automatic processes.

Can you consider put separate signatures as at 5.5.1 (lot of other coins do that).

Thanks

**Comment by whilei** [comment]
Hey @petrkr, thanks for the feedback, and glad to hear that they're useful!

I've just added them to the [5.5.2 release](https://github.com/ethereumproject/go-ethereum/releases/tag/v5.5.2), and will make that standard practice for future ones.

**Comment by whilei** [comment]
Closing as expected resolved. Please reopen otherwise.
