### ISSUE TITLE
Can evm change the account code?

### ISSUE THREAD

**Issue by b00f** [ethereumproject/go-ethereum#696]
As I know the account code should not be changeable after creation. However I found a piece of code that is a bit strange for me:
https://github.com/ethereumproject/go-ethereum/blob/1a8b71b8f3e03775303182df7f446a93234ef89c/core/multivm_processor.go#L156

Why an account's code should change here?

**Comment by lostinblue** [comment]
Haha yeah, thats a nice find. Its from the hard fork. Gravity must of missed it on the update. 

I'm working on a pretty major EVM update in general, its broken from the start, it can be optimized in so many ways it makes my head hurt.
