### ISSUE TITLE
The partner instant exchange SimpleSwap.io

### ISSUE THREAD

**Issue by SimpleSwap** [ethereumproject/go-ethereum#699]
Hi,

I am Nicolas, the manager at SimpleSwap.io, an instant cryptocurrency exchange.

We present a simple and easy-to-use platform that works without registration and limits and allows users to make swaps in just two clicks.

We successfully support ETC on our service for a long time and we have been exchanging ETC for more than 200 coins to our customers. I tried to find contact with your team but without results.

I'm sorry that I invaded here, but maybe you can tell me where I can turn. I would like to make contact so we can have an interaction.

**Comment by lostinblue** [comment]
Please don't advertise here, thats not what this is for. We are volunteers, we dont have time to foster through this. every hour we invest MUST be spent doing something worthwhile. I dont have time to tell you to even close your post, get it? Just close it plz
