### ISSUE TITLE
Change binary name to getc

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#7]
The suggestion was made to migrate to the name getc, which makes sense and will help avoid future confusion when dealing with multiple chains.

**Comment by jwg4** [comment]
I am not sure this is moving in the right direction. Doesn't this release of geth stay compatible with all Ethereum blockchains, EXCEPT one which had a dodgy block reimbursing the DAO? This client could be used for Ethereum testnets, private Ethereum chains, etc. Renaming to `getc` makes it look like it is a specifically different version, only for the Ethereum Classic chain. In fact, it is 'official' `geth` which was patched to work with a special chain.

**Comment by whatisgravity** [comment]
Changing the name of the command will not affect backwards compatibility. 

To be clear, I do agree this chain is Ethereum, the other change should change their name since they are the ones that decided to make changes to the original protocol we all agreed upon. However we also need to be willing to make compromises to make progress. In the short term, in order to increase usability I believe we can implement changes which make it easier to run both clients. 

It is the original go-ethereum with code removed to make it operate specifically with the *original* chain.

**Comment by arvicco** [comment]
I would think that having both commands work simultaneously via alias is preferable. There is a lot of legacy documentation online regarding geth usage.

**Comment by whatisgravity** [comment]
@arvicco That is a good point, this change would not really affect the ability to run both clients on the same terminal. I will adjust the proposal and forthcoming patch to only change the minimal amount to work on the same terminal without additional flags that way old documentation remains relevant as possible.

**Comment by mmgen** [comment]
I'm against this change.  It looks silly and is confusing.  getc is a C function.

**Comment by jwg4** [comment]
before the fork happened, and shortly afterwards, it was important that people who wanted to stick with or join the classic chain could find this client which guaranteed not to implement the hard fork. Now out seems to me that the best strategy would be to make it possible for a single client to support both chains with minor configuration. Perhaps we should be 1. trying to propose these changes to the mainline berth, to see if it could support classic put of the box, for example using two aliases to the same executable to choose which chain or 2. if this approach is not successful, to make this version of the client support both chains, again with aliases or similar
