### ISSUE TITLE
Bad block for 3.0.0

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#70]
#### System information

Geth version: `3.0.0`
#### Backtrace

```
E1017 05:30:09.212822 core/blockchain.go:1137] Bad block #1179407 (0x9e363e48e790f6548ebbdb7e50cce5f37c1908108b3e111c4780b6af1ae9daf1)
E1017 05:30:09.212846 core/blockchain.go:1138]     gas used error (1246053 / 1245493)
```

Fixed after resync

A user reported `Bad block #1803253` also

**Comment by splix** [comment]
Another error on my test stand:
````
I1019 03:47:54.657247 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)
E1019 03:48:30.416383 core/blockchain.go:1137] Bad block #2430521 (0xe25a5f8c8eb3e40bca6ee0dc6e1c1725a95156299f4e473084fca43ffc04e518)
E1019 03:48:30.416406 core/blockchain.go:1138]     gas used error (780360 / 764880)
````

**Comment by aesedepece** [comment]
```
E1019 16:41:15.125864 core/blockchain.go:1137] Bad block #1787867 (0x9bff314917c062539502a95b1d5ed0ed82dc9c0c25ddae41001aa0a8f8198410)
E1019 16:41:15.125895 core/blockchain.go:1138]     gas used error (135521 / 135481)
```

**Comment by zz0412** [comment]
oh,i have one.
i sync etc block on #0,

I1020 00:48:58.258134 core/blockchain.go:973] imported 2048 block(s) (0 queued 0 ignored) including 0 txs in 2.664390081s. #39673 [444a73d0 / 2348b7fe]
I1020 00:49:00.653959 core/blockchain.go:973] imported 2048 block(s) (0 queued 0 ignored) including 0 txs in 2.39039266s. #41721 [156d5670 / 7b8f8433]
I1020 00:49:03.792127 core/blockchain.go:973] imported 2048 block(s) (0 queued 0 ignored) including 0 txs in 3.130653359s. #43769 [4bea1163 / 3f5100b4]
I1020 00:49:07.757552 core/blockchain.go:973] imported 2048 block(s) (0 queued 0 ignored) including 0 txs in 3.954993703s. #45817 [561c2243 / cc8e2947]
I1020 00:49:07.785125 miner/worker.go:555] commit new work on block 45818 with 0 txs & 0 uncles. Took 396.586µs
I1020 00:49:11.101432 core/blockchain.go:973] imported 2048 block(s) (0 queued 0 ignored) including 790 txs in 3.258762441s. #47865 [5c888b26 / 445c207d]
I1020 00:49:14.147158 core/blockchain.go:973] imported 2048 block(s) (0 queued 0 ignored) including 1053 txs in 3.039150315s. #49913 [3844001e / e4cedf8c]
E1020 00:49:14.632859 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:49:14.632890 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:49:35.430631 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:49:35.430680 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:49:44.963954 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:49:44.964004 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:49:52.153813 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:49:52.153860 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:50:04.033648 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:50:04.033707 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:50:17.719892 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:50:17.719932 core/blockchain.go:1138]     gas used error (103858 / 103818)
I1020 00:50:21.852080 eth/downloader/downloader.go:301] Synchronisation failed: block header download canceled (requested)
E1020 00:50:29.488783 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:50:29.488828 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:50:56.436783 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:50:56.436827 core/blockchain.go:1138]     gas used error (103858 / 103818)
E1020 00:51:24.615413 core/blockchain.go:1137] Bad block #50111 (0xdd6702c6fe0d54fe3375253e36702aacc71a80a1de9ec374246d7c241905bbf4)
E1020 00:51:24.615456 core/blockchain.go:1138]     gas used error (103858 / 103818)

**Comment by splix** [comment]
It's hard to catch this bug, which makes it worse. If you'll have this issue, please run Geth with `--verbosity 5` and post log output.

It's also very likely that after Geth restart it will continue processing from this block w/o problem.

**Comment by splix** [comment]
It seems that the bug in JITVM, please try to run vs `--jitvm=false` option

**Comment by splix** [comment]
JITVM was disabled at [9e990aa7f08f1f32fef5e0fc5f15834c0b31b4eb]
