### ISSUE TITLE
Coin faucet on kotti testnet

### ISSUE THREAD

**Issue by rvit34** [ethereumproject/go-ethereum#708]
Your morden testnet and faucet is not working now
You have working kotti net but I've not found any faucet for it.
So, how can I deposit account by test ETC?

**Comment by soc1c** [comment]
Join us on Gitter gitter.im/goerli/kotti

Or discord https://discord.gg/5ph3V7

And share your morden or kotti account.

**Comment by soc1c** [comment]
resolved by https://github.com/multi-geth/multi-geth/pull/88

see also http://kottifaucet.me/
