### ISSUE TITLE
can i update 3.0 base on   geth1.4.17(eth)

### ISSUE THREAD

**Issue by yangllsdev** [ethereumproject/go-ethereum#72]
#### System information

Geth version: `geth 1.4.17`
OS & Version: Linux
Commit hash : (if `develop`)

 hello

     i use geth1.4.17 right now with parameter --oppose-hard-fork
    can i update version 3.0 base on geth1.4.17(eth)

    thanks

**Comment by splix** [comment]
Yes, you should update to Classic Geth 3.0 to continue in ETC chain. 

EF Geth 1.4 with `--oppose-hard-fork` is going to stop providing compatibility with ETC on block 2463000

**Comment by yangllsdev** [comment]
can 3.0 reuse the chaindata of geth1.4.17

**Comment by splix** [comment]
Yes, sure, it will continue existing chaindata left from geth1.4.17

**Comment by yangllsdev** [comment]
ok thanks , i will try ASAP

**Comment by splix** [comment]
btw, if you'll notice any conflicts, feel free to submit an issue here. we still have time for a fix

**Comment by yangllsdev** [comment]
so nice,

**Comment by yangllsdev** [comment]
so nice
thank you
