### ISSUE TITLE
What is the height of EIP658 hard fork on the main network and morden test network?

### ISSUE THREAD

**Issue by qiluge** [ethereumproject/go-ethereum#720]
The morden hard fork height is 0x4829ba, but main net hard fork height is?
Reference https://github.com/paritytech/parity-ethereum/issues/10870#issuecomment-509970264

**Comment by soc1c** [comment]
Hi, it's block `8772000` - see https://github.com/eth-classic/go-ethereum/pull/77

You can check the release notes here: https://github.com/ethereumproject/go-ethereum/releases

**Comment by soc1c** [comment]
See also the Atlantis EIP with all block numbers

https://github.com/ethereumproject/ECIPs/blob/master/ECIPs/ECIP-1054.md#abstract

**Comment by qiluge** [comment]
Thank you very much, and can you tell me what's chainId of etc mainnet?

**Comment by qiluge** [comment]
https://medium.com/@piyopiyo/list-of-ethereums-major-network-and-chain-ids-2bc58e928508, got it, thank you!
