### ISSUE TITLE
make geth v6.0.9 error

### ISSUE THREAD

**Issue by SalleryWang** [ethereumproject/go-ethereum#727]
# github.com/ethereumproject/go-ethereum/console
console/console.go:117:43: undefined: jsre.BigNumber_JS
console/console.go:120:38: undefined: jsre.Web3_JS
make: *** [cmd/geth] Error 2

**Comment by soc1c** [comment]
please report to the developers directly https://github.com/etclabscore/go-ethereum/issues/

and include your go version and full cli output
