### ISSUE TITLE
Sign releases, tags and binaries for trusted & secure distribution

### ISSUE THREAD

**Issue by brutuscat** [ethereumproject/go-ethereum#74]
Hi guys, thank you for the great work you are doing on the miner! 

I was thinking that it would really helpful and would add a lot trust (when running a binary) if you could sign the releases, the tags and the binaries that you ship:

- [Git Tools - Signing Your Work] (https://git-scm.com/book/en/v2/Git-Tools-Signing-Your-Work)
- [Signing tags using GPG
](https://help.github.com/articles/signing-tags-using-gpg/)
- [example to create and sign Github releases](https://wiki.debian.org/Creating%20signed%20GitHub%20releases) 

Keep it coming!

**Comment by ericsomdahl** [comment]
We are actually already doing this:  if you look at [Our main binary distributions](https://bintray.com/ethereumproject/GoEthereumClassic/go-ethereum) you will see that we provide a GPG signature file for each binary.

The public signing key can be found [here](https://github.com/ethereumproject/volunteer/blob/master/Client-Restoration/code_signing.asc)

**Comment by brutuscat** [comment]
@ericsomdahl great! Could you also publish the asc on the files released using github? That would be great :)

Thank you!

**Comment by pierreozoux** [comment]
Hello!

Just tried right now to verify signature, and got this:

```
wget https://raw.githubusercontent.com/ethereumproject/volunteer/master/Client-Restoration/code_signing.asc
gpg --import code_signing.asc
gpg: key 60A7A81C: public key "Eric Somdahl (Code signing) <eric.somdahl@ethereumclassic.org>" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
gpg --verify ./geth-classic-linux-v3.3.0-1-gdd95f05.zip.sig 
gpg: assuming signed data in `./geth-classic-linux-v3.3.0-1-gdd95f05.zip'
gpg: Signature made Thu 09 Mar 2017 07:04:42 PM WET using RSA key ID FC7BBDEF
gpg: Can't check signature: public key not found
```

Could you help, or update the documentation on the release page?

Thanks a lot for your work!

**Comment by pierreozoux** [comment]
And actually here, there is no signature for ./geth-classic-linux-v3.3.0-1-gdd95f05.zip:

```
https://bintray.com/ethereumproject/GoEthereumClassic/go-ethereum#files
```

I'm a bit worried, I'll wait before executing this bin on my machine.

**Comment by splix** [comment]
You can import pgp keys of our volunteers from here: https://github.com/ethereumproject/volunteer/tree/master/Volunteer-Public-Keys

**Comment by pascaldekloe** [comment]
@ericsomdahl, I added your signature to the public key servers so this won't be an issue anymore.
