### ISSUE TITLE
nil pointer dreference

### ISSUE THREAD

**Issue by realcodywburns** [ethereumproject/go-ethereum#77]
#### System information

Geth version: `geth version` 3.0.0
OS & Version: Linux
Commit hash : (if `develop`)
#### Expected behaviour

after install trying to fast sync
#### Actual behaviour

throws invalid memory address or nil pointer dereference

**Comment by splix** [comment]
@realcodywburns can you add error output also?

**Comment by realcodywburns** [comment]
Even with verbosity at 6 it would never give me anything past the geth flag version number and then crash

the error was resolved by cloning into /github.com/ethereumproject/go-ethereum instead of ~/go-ethereum.

**Comment by pascaldekloe** [comment]
Most likely you got conflicting versions on you GOPATH before @realcodywburns.

**Comment by pascaldekloe** [comment]
Normally, to get started with Go projects you 1) make a project directory, 2) set `GOPATH` to the respective project directory and 3) clone with `go get github.com/ethereumproject/go-ethereum`. Once we get rid of `godep` the get operation no longer downloads dependencies.
