### ISSUE TITLE
Daemonize

### ISSUE THREAD

**Issue by whatisgravity** [ethereumproject/go-ethereum#8]
Users on reddit were asking about this, does not yet seem to be added yet. 

https://github.com/ethereum/go-ethereum/issues/2608

It should be easy to add if it does not get added to upstream soon.

**Comment by LeChuckDE** [comment]
Wrote a upstart script for it ... easy like hell ....

**Comment by whatisgravity** [comment]
Yeah, that is how I would handle it too, but it would be a trivial addition. Would you mind sharing your script for the benefit of others if you have not already?

Other solutions include using screen or

    nohup ./geth &

However I prefer alternative methods.

**Comment by LeChuckDE** [comment]
`
description "Start geth-node for Ethereum Classic"

env DAEMON=/Path/to/geth-binary/geth
env CONFIG=" --oppose-dao-fork --fast --cache 512 --rpc --rpcaddr 127.0.0.1 --rpcport 8275 --rpcapi web3,admin,eth,net console"

start on filesystem or runlevel [2345]
stop on runlevel [!2345]

setuid <geth username>
setgid <geth username>

kill signal INT

respawn
respawn limit 10 5
umask 022

pre-start script
	test -x $DAEMON || { stop; exit 0; }
end script

# Start
script
	exec $DAEMON $CONFIG
end script
`

here that is mine.

Save it as geth-etclassic.conf under your homedirectory

sudo cp ~/geth-etclassic.conf /etc/init/
then you could start it with:
start geth-etclassic (restart and stop also possible)
to get output:
tailf /var/log/geth-etclassic.log

to work with it start a geth attach with same user like geth is running

**Comment by LeChuckDE** [comment]
with screen :  
sudo apt-get -Y install screen

screen -S geth-etclassic
geth c --oppose-dao-fork --fast --cache 512 --rpc --rpcaddr 127.0.0.1 --rpcport 8275 --rpcapi web3,admin,eth,net console

Press Ctrl(keep pressed) + A + D +Release Crtl to leave screen session. 
to reattach:

screen -r geth-etclassic

**Comment by whatisgravity** [comment]
Thanks, I'm sure those will help others and if I see that question get asked again I can simply link them here. We can also eventually incorporate it into a wiki page or some guide.

**Comment by MatBenetti** [comment]
i'd prefer to have this feature embedded into the cli
`geth --daemon --logfile "/var/log/geth.log"`

**Comment by whatisgravity** [comment]
I'm still interested in adding the daemon flag or separate daemon binary. If anyone is interested in creating a pull request for this issue, reach out. If no one volunteers I will add these changes before the next release.

**Comment by mikeyb** [comment]
A slightly easier one liner screen command to drop geth into the background

### Screen Examples
#### General startup of client
`screen -S geth -d -m bash -lc 'geth --oppose-dao-fork --fast console'`
#### Start client and unlock first wallet
`screen -S geth -d -m bash -lc 'geth --oppose-dao-fork --fast --unlock 0 console'`

### Attach to screen running geth
`screen -x geth`

### Detach from the screen when done
`ctrl+a` then `d`

**Comment by pascaldekloe** [comment]
Go has issues with deamonizing: https://github.com/golang/go/issues/227
We could ship with some example configurations like Unix init scripts, supervisord, etc...

**Comment by camstuart** [comment]
I would have thought that a systemd unit file such as this one: https://gist.github.com/swaldman/e58a866eafc4ff043c4099e394901a1e would be the way to go.

Systemd will capture stdout/err and direct it to anywhere you want. By default, it goes to syslog.

So perhaps maybe some gists of systemd for linux OS's and launchd for OSX with instructions would satisfy this requirement? I would be happy to do this.

**Comment by whilei** [comment]
That sounds great @camstuart. I've used `systemctl` for this before and it works fine (using then `journalctl` to monitor logs, and `logrotate` for, well, log rotation).

A gist or gists would be very welcome :+1:

**Comment by camstuart** [comment]
Ok @whilei I'll see what I can do. where would the gists live? this repo? I have never contributed a gist before. is it similar to a PR. If you have a guide, then I'll get get up to speed on it.

**Comment by whilei** [comment]
I think the gist should be separate from this repo. One solution would be if you create a gist.github.com, then a link to that gist could be included in the wiki at an appropriate spot.

Open to other solutions as well.

**Comment by camstuart** [comment]
Yeah sounds good @whilei, will do
