### ISSUE TITLE
Gas Price round 2

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#83]
Reprice EXP and BALANCE

**Comment by arvicco** [comment]
Should we add this reprice as part of ECIP-1050 as well? Because if we decide to have it as part of a hard fork, we need to have it both in Parity and Geth....

@elaineo @realcodywburns @ericsomdahl

**Comment by elaineo** [comment]
@arvicco did ETH create a new EIP, or add it to the old one?

**Comment by arvicco** [comment]
I don't think they did either, at this point. Even ETH reprice target is not known yet.
