### ISSUE TITLE
Bad block "gas used error"

### ISSUE THREAD

**Issue by qkdev** [ethereumproject/go-ethereum#87]
I1020 16:48:20.232891 core/blockchain.go:762] imported 0 receipt(s) (1 ignored) in 466.872µs. #2471261 [e370a64b▒ / e370a64b▒]
I1020 16:48:20.232972 core/blockchain.go:280] committed block #2471261 [e370a64b▒] as new head
E1020 16:48:33.826241 core/blockchain.go:1137] Bad block #2471263 (0x90ef5fe9ca47ac0eab6bd44ddebc138e76543c378fa63003b76c7aee593266be)
E1020 16:48:33.826343 core/blockchain.go:1138]     gas used error (1179877 / 1179837)

#### System information

Geth version: `Version: 3.0.0-stable`
OS & Version: Ubuntu 16
Commit hash : (if `develop`)

#### Backtrace

````
[backtrace]
````

**Comment by splix** [comment]
@qkdev can you also provide beginning of the output? upto `I1020 21:42:22.629482 eth/backend.go:201] Blockchain DB Version: 3`?

**Comment by splix** [comment]
dup #70

**Comment by qkdev** [comment]
`I1020 16:56:43.681231 ethdb/database.go:83] Alloted 1024MB cache and 1024 file handles to /root/.ethereum/chaindata
I1020 16:56:51.831333 cmd/utils/flags.go:853] --------------------------------------------------------------------------------------------------------------
I1020 16:56:51.831358 cmd/utils/flags.go:854] Loading blockchain: genesis block "0xd4e56740f876aef8c010b86a40d5f56745a118d0906a34e69aec8c0db1cb8fa3".
I1020 16:56:51.831365 cmd/utils/flags.go:855] 4 blockchain hard-forks associated with this genesis block:
I1020 16:56:51.831376 cmd/utils/flags.go:871]  Homestead hard-fork at block 1150000
I1020 16:56:51.831387 cmd/utils/flags.go:871]  ETF hard-fork at block 1920000 resulted in a network split (support: false)
I1020 16:56:51.831395 cmd/utils/flags.go:871]  GasReprice hard-fork at block 2500000
I1020 16:56:51.831402 cmd/utils/flags.go:871]  Diehard hard-fork at block 3000000
I1020 16:56:51.831409 cmd/utils/flags.go:873] Geth is configured to use the Ethereum (ETC) classic/original blockchain!
I1020 16:56:51.831417 cmd/utils/flags.go:874] --------------------------------------------------------------------------------------------------------------
I1020 16:56:51.831497 ethdb/database.go:171] closed db:/root/.ethereum/chaindata
I1020 16:56:51.832107 ethdb/database.go:83] Alloted 1024MB cache and 1024 file handles to /root/.ethereum/chaindata
I1020 16:56:52.006737 ethdb/database.go:83] Alloted 16MB cache and 16 file handles to /root/.ethereum/dapp
I1020 16:56:52.010745 eth/backend.go:172] Protocol Versions: [63 62], Network Id: 1
I1020 16:56:52.011489 eth/backend.go:201] Blockchain DB Version: 3
`

**Comment by splix** [comment]
Hm, I thought it can be because of jitvm enabled, but seems that your instance was running without it. 

Is it reproducible each run? Can you run it with `--verbosity 5` then? and provide us a log output before "bad block" error

**Comment by MartinMakowski** [comment]
I also came upon the 'bad block' / 'gas used error' message and was able to resolve it by removing the chaindata directory and re-synching geth v3.0.0 using the --fast option and --jitvm=false

As a quick test after the --fast sync completed I re-ran Geth using the --jitvm=true option and it gave me another Bad Block error:

E1020 23:11:37.080642 core/blockchain.go:1137] Bad block #2475972 (0x5026775c43dca354a461bd42e57c2aac92c376856f95c35299c69fe0664e944f)
E1020 23:11:37.080668 core/blockchain.go:1138]     gas used error (856820 / 854300)

I exited geth and ran it a final time with --jitvm=false and it got past the bad block and synced to the latest block in chain correctly.

There definitely may be an issue related to the JITVM after all. 

If you need any additional testing and logging around this issue please let me know.

Thank you,
Martin

**Comment by splix** [comment]
@MartinMakowski good job Martin, there're more and more evidences that this can be caused by JitVM. Thank you.

**Comment by MartinMakowski** [comment]
I also came upon the 'bad block' / 'gas used error' message and was able to
resolve it by removing the chaindata directory and re-synching geth 3.0.0
using the --fast option and --jitvm=false
Now my chain is up to date and I did not see the bad block error again.
Let me know if there is any test scenarios you would like me to try to
narrow this down further.

Thanks for all the hard work to ETC Dev Team!

Cheers,
Martin

**Comment by MartinMakowski** [comment]
As a quick test after the --fast sync completed I re-ran Geth using the
--jitvm=true option and it gave me another Bad Block error:

E1020 23:11:37.080642 core/blockchain.go:1137] Bad block #2475972
(0x5026775c43dca354a461bd42e57c2aac92c376856f95c35299c69fe0664e944f)
E1020 23:11:37.080668 core/blockchain.go:1138]     gas used error (856820 /
854300)

I exited geth and ran it another time with --jitvm=false and this time it
got past the bad block and is synching correctly.
There definitely may be an issue related to the JITVM after all. If you
need any additional logs let me know.

Thank you,
Martin
