### ISSUE TITLE
Incorrect highest block while fast syncing

### ISSUE THREAD

**Issue by ADumaine** [ethereumproject/go-ethereum#89]
#### System information

Geth version: 3.0.0  (d76ad4e)
OS & Version: Windows 10
Commit hash : (if `develop`)
#### Expected behaviour

The correct highest block is displayed on eth.sync
#### Actual behaviour

highest block showing a block that has not been mined yet. see below
#### Steps to reproduce the behavior

populate a new chain folder using --fast

Used eth.syncing to display progress of a fast sync.  Notice that some of the highest blocks are in the 2,477,xxx range.   It finally started displaying the correct highest block.At this point the current high block is 2,474,200. 

Does this mean there is a node out there that has somehow pushed ahead on the chain?  Is this a problem with the network, differing geth/parity versions, or geth 3.0?

```
> eth.syncing
{
  currentBlock: 1101977,
  highestBlock: 2477196,
  knownStates: 3649533,
  pulledStates: 3616738,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 1693224,
  highestBlock: 2477259,
  knownStates: 5402285,
  pulledStates: 5372460,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 1695728,
  highestBlock: 2477267,
  knownStates: 5373067,
  pulledStates: 5373066,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 1918544,
  highestBlock: 2477325,
  knownStates: 5590737,
  pulledStates: 5574383,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 2069711,
  highestBlock: 2474123,
  knownStates: 6006805,
  pulledStates: 5941296,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 2222595,
  highestBlock: 2474123,
  knownStates: 6426266,
  pulledStates: 6395442,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 2472350,
  highestBlock: 2474154,
  knownStates: 6838079,
  pulledStates: 6838079,
  startingBlock: 0
}
> eth.syncing
{
  currentBlock: 2472772,
  highestBlock: 2474162,
  knownStates: 7577132,
  pulledStates: 7478619,
  startingBlock: 0
}
```

Edit: added build version

**Comment by splix** [comment]
Yes, highestBlock is what node sees on peers. But it's all just preliminary numbers until blocks will be actually processed. There many reason why other peers can have invalid heigh, sometimes too low to to high.
