### ISSUE TITLE
Implement ReplayAttack protection

### ISSUE THREAD

**Issue by splix** [ethereumproject/go-ethereum#93]
Implement ReplayAttack protection by introducing new signature component, based on BlockHash of last fork.

Key elements:
- optional, accept non-protected transactions on validation
- enable signing after block 3,000,000
  - accept new signature
  - sign with new component by default
- use hash of block 1,920,000
- write tests
- cli flag to disable new sign (optional task)
- cli flag to require new sign for mining (optional task)

Reference:
- https://github.com/ethereumproject/ECIPs/pull/10/files
- `/core/types/transaction.go`

**Comment by elaineo** [comment]
Are we decided on [ECIP1011](https://github.com/ethereumproject/ECIPs/pull/10)?

**Comment by splix** [comment]
@elaineo not decided yet, but we want to use this task as a test task for a new developer. We may accept it or not, but it's good enough to get familiar with the code.

**Comment by avtarsehra** [comment]
@splix, thanks this looks good.
