### ISSUE TITLE
lots of error log:    Synchronisation failed: block download canceled (requested)

### ISSUE THREAD

**Issue by yangllsdev** [ethereumproject/go-ethereum#95]
#### System information

Geth version: `geth 3.0.1`
OS & Version: linux
Commit hash : (if `develop`)
#### Expected behaviour

```
there are a lot of error log, does it matter  ?
    Synchronisation failed: block download canceled (requested)
    Synchronisation failed: block header download canceled (requested)
```

   by the way:   the local block is latest.
#### Backtrace

```
[backtrace]
```

**Comment by lotus33** [comment]
Geth version: geth 3.0.1
OS & Version: linux
the same thing I have

I1025 07:03:13.611923 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)
I1025 07:03:43.139787 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)
I1025 07:03:43.665405 eth/downloader/downloader.go:301] Synchronisation failed: block header download canceled (requested)
I1025 07:03:43.907362 eth/downloader/downloader.go:301] Synchronisation failed: block header download canceled (requested)
I1025 07:03:44.110309 eth/downloader/downloader.go:301] Synchronisation failed: block header download canceled (requested)
I1025 07:03:44.325876 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)
I1025 07:03:45.164180 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)
I1025 07:03:48.366478 core/blockchain.go:973] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.435943ms. #2500756 [0580e3a3 / 0580e3a3]
I1025 07:03:48.412933 miner/worker.go:555] commit new work on block 2500757 with 45 txs & 0 uncles. Took 46.226393ms
I1025 07:04:05.490565 core/blockchain.go:973] imported 1 block(s) (0 queued 0 ignored) including 3 txs in 9.56825ms. #2500757 [638a6120 / 638a6120]
I1025 07:04:05.534089 miner/worker.go:555] commit new work on block 2500758 with 45 txs & 0 uncles. Took 43.011258ms
I1025 07:04:06.956506 core/blockchain.go:973] imported 1 block(s) (0 queued 0 ignored) including 0 txs in 6.336412ms. #2500758 [21b4e8aa / 21b4e8aa]
I1025 07:04:07.008976 miner/worker.go:555] commit new work on block 2500759 with 54 txs & 0 uncles. Took 52.26114ms
I1025 07:04:15.347579 eth/downloader/downloader.go:301] Synchronisation failed: block download canceled (requested)

**Comment by splix** [comment]
This message actually means that a peer just disconnected, nothing really bad. But it shouldn't spam log by default

**Comment by splix** [comment]
#96

**Comment by lotus33** [comment]
I think that is bad, very bad.
the height of the units does not meet 1-2 of the unit, usually
and miners work in an empty

for example

```
commit new work on block 2511428 with 1 txs & 0 uncles. Took 7.314114028s
imported 1 block(s) (0 queued 0 ignored) including 11 txs in 20.97702ms. #2511429 [6d165947 / 6d165947]
imported 1 block(s) (0 queued 0 ignored) including 3 txs in 11.51132ms. #2511430 [35112eca / 35112eca]
imported 1 block(s) (0 queued 0 ignored) including 11 txs in 21.852437ms. #2511431 [caa36978 / caa36978]
Synchronisation failed: block download canceled (requested)
Synchronisation failed: block download canceled (requested)
imported 1 block(s) (0 queued 0 ignored) including 0 txs in 7.165259ms. #2511432 [0378a138 / 0378a138]
commit new work on block 2511429 with 0 txs & 0 uncles. Took 50.722645532s
```

note 2511429
