### ISSUE TITLE
Implement Chain Data Bootstrapping mechanism

### ISSUE THREAD

**Issue by ericsomdahl** [ethereumproject/go-ethereum#97]
Implement a mechanism that allows a user to bootstrap the state of the chain on their node, without starting from scratch -- similar to what is found on BTC and derivatives (as described [here](https://bitcointalk.org/index.php?topic=145386.0)).

The state bootstrapper should pre-empt the downloader when the bootstrap file is present.

Part of this task should also be to create a mechanism in the client (or a separate utility altogether) to export the individual LevelDB files from the .ethereum/chainstate folder as 1 single bootstrap.dat file.

The bootstrap.dat file would then be distributed via torrent or other means.

**Comment by splix** [comment]
It seems that `--fast` flag provides similar function

**Comment by ericsomdahl** [comment]
I agree and I believe this issue is low-priority. 

But it seems that even with the --fast flag some users (of Mist on slower computers) are unable to catch up when processing.  [See this URL](https://www.reddit.com/r/ethereum/comments/593dz6/temporary_solution_if_your_mist_cant_catch_up/).

For ETC users who cannot catch up to the current block it will be sufficient to distribute a zip'd copy of a recent chainstate folder.

**Comment by ericsomdahl** [comment]
Upon further reflection -- does it matter if the user downloads 1 bootstrap.dat file or 1 folder containing multiple files?

I think not.  I withdraw my issue :smile:
